### ISSUE TITLE
Problem when use .com instead of .localhost 

### ISSUE THREAD

**Issue by Ichtuus** [dunglas/symfony-docker#102]
When is use this following command

`SERVER_NAME="monsite.com, caddy:80" docker-compose up --build`

Application not display on "monsite.com", its make an SSL error => `SSL_ERROR_INTERNAL_ERROR_ALERT
`
but when i use this

`SERVER_NAME="monsite.localhost, caddy:80" docker-compose up --build`

The application be display on "monsite.localhost"
I think its obvious issu, but I can't solve the problem

Someone else can help me ?

**Comment by dunglas** [comment]
Is your server publicly exposed on the internet? It's mandatory for Caddy to generate the TLS certificate using Let's Encrypt.

**Comment by Ichtuus** [comment]
No i just work locally to upgrade my skills, i search to use another host to my actual caddy server
To use "monsite.com" instead of "monsite.localhost"

I can make that with nginx or apache, but i can't do it with caddy

Actually caddy give this followings url => https://monsite.localhost/

**Comment by Ichtuus** [comment]
Ok i solve my problem with this followings instruction

I change my SERVER_NAME env var in my .env.local file to _monsite.com_ into _http://monsite.com_, to "disabling" ssl and its work ! 

I find  `auto_https disable_redirects` but its available only from v2.1 of caddy

Thanks for your help, i close this issue

**Comment by dunglas** [comment]
Alternatively, you can use a self-signed TLS certificate: https://caddyserver.com/docs/caddyfile/directives/tls

To generate a valid certificate for a real domain, Caddy must be exposed publicly on the internet.

**Comment by rccc** [comment]
> To generate a valid certificate for a real domain, Caddy must be exposed publicly on the internet.

Hello, does this means that starting the container on a produciton server will not be enough ? What do you mean by " exposed publicly " ?
