### ISSUE TITLE
.env.local excluded in .dockerignore

### ISSUE THREAD

**Issue by tillmon** [dunglas/symfony-docker#104]
Why is the `.env.local` excluded in [`.dockerignore`](https://github.com/dunglas/symfony-docker/blob/6cbb384d8b772454a5a1d39770d42446dff4f9d4/.dockerignore#L18-L20)? If I create a `.env.local` it should be available in the `php` container.

**Comment by maxhelias** [comment]
It is available on the container via the volumes on docker-compose.override.yaml.

**Comment by maxhelias** [comment]
Note: More information here https://symfony.com/blog/new-in-symfony-4-2-define-env-vars-per-environment
