### ISSUE TITLE
Adding DO App Platform instructions in the "Deploying in Production" section

### ISSUE THREAD

**Issue by EmilePerron** [dunglas/symfony-docker#122]
Hey folks,

The documentation currently provides instructions on how to deploy to production using a Digital Ocean droplet.
However, there are no instructions on how to deploy using [DO's App Platform](https://www.digitalocean.com/products/app-platform/).

Can projects built with this template be deployed on the App Platform, where docker-compose cannot be used?
If so, I believe it would be great to add some instructions on that subject to the documentation.

If it hasn't been done/attempted yet, I could give it a shot and submit a PR with the adequate documentation if I succeed. However, I am fairly new to Docker / Docker-compose, so I can't guarantee anything at the moment.

Cheers, and great job on the template!

**Comment by Antarian** [comment]
DO's App Platform is service similar to Heroku, Google App Engine, AWS Lightsail, .... As you mentioned no Docker, hugely dependant on language and framework autodetection. Also only supported database for autodetection is PostgreSQL for now. 

PHP manual [https://docs.digitalocean.com/products/app-platform/languages-frameworks/php/](https://docs.digitalocean.com/products/app-platform/languages-frameworks/php/) is also present and I think for Symfony you just need to give it a try and see how many "droplets" it will spin up for your app.

I do not see a point to put documentation for it to this repo. Maybe create community article about App Platform and Symfony on DO's pages directly.

**Comment by EmilePerron** [comment]
@Antarian Fair enough! That's what I figured as well after giving this some more thought.

I'll be using it in the near future for a web app, so when the time comes, I'll use that opportunity to write and publish a community article about it if I feel like I have sufficient knowledge about the subject. 👍

**Comment by maxhelias** [comment]
I agree with @Antarian.
Unfortunately we cannot document every integration for every existing platform.. One or more articles are best suited to the needs of each.

Thanks
