### ISSUE TITLE
Defining the installation directory and dependencies

### ISSUE THREAD

**Issue by entermix** [dunglas/symfony-docker#123]
**Is your feature request related to a problem? Please describe**
It would be great to be able to specify the directory for installing Symfony and dependencies.

This will help you quickly create flexible architecture, for example:

```
docker
docs
web
- backend
-- src
-- public
-- ...
- frontend
-- src
-- public
-- ...
README.md
```

This may be needed if the user wants to add an independent SPA application that needs a separate server, for example.

**Describe the solution you'd like**
Add the ability to specify the directory for installing Symfony and all framework dependencies 

Is it possible? What do you think about this?

Thanks!

**Comment by maxhelias** [comment]
For the moment, the architecture is not planned to move.
For your needs, you can very well integrate this git in another git project (new or existing).
```
your-spa-project
- symfony-docker (api)
- - src
- - ...
- front
- - src
```

**Comment by maxhelias** [comment]
As explained above, I close the issue
