### ISSUE TITLE
Can't run project on windows

### ISSUE THREAD

**Issue by vichanse** [dunglas/symfony-docker#13]
I'm unable to run the project on a windows PC  using docker(FYI i can run the @apiPlatform one)
The php-fpm container exists right after starting
![image](https://user-images.githubusercontent.com/26761479/32263193-f92c12f6-bed8-11e7-8bc4-2b3856de8ef0.png)

It looks like the project hasn't been created. The public folder is empty
![image](https://user-images.githubusercontent.com/26761479/32263235-237f0a5e-bed9-11e7-8544-25df0c14987b.png)

I'm still digging into it tryin' to figure out what's wrong, if you have any idea ;(

**Comment by dunglas** [comment]
can you copy the output of `docker-compose log php` please?

**Comment by vichanse** [comment]
Here is the log

Attaching to symfonydocker_app_1
app_1       |     1/10: http://packagist.org/p/provider-archived$129c1b6decb2493bfda684b4ad33ad96d451a6068365335237ecbaa740ee8b4f.json
app_1       |     2/10: http://packagist.org/p/provider-2013$0a5cce6796d52e8efd2d6f03908055199c0e2fb0b92563fee0092b3c274c9e48.json
app_1       |     3/10: http://packagist.org/p/provider-2017-10$5af6407cb17cce598453dde4476ce158bfe311f40fbf1cc28131345348eea628.json
app_1       |     4/10: http://packagist.org/p/provider-latest$9de23841bf269f94d5f82c40bba3dee26d798c9fa2a4d0b75e567d9adff6ea0d.json
app_1       |     5/10: http://packagist.org/p/provider-2017-04$2169388a5d1bcdff7bd83465542fac53c2f12655fc06319bb1702a1402c9371e.json
app_1       |     6/10: http://packagist.org/p/provider-2014$d8ed7364faaa1abadf8139f1a18cd6f98f2aa14fb43da4881c5e38be2d94ea39.json
app_1       |     7/10: http://packagist.org/p/provider-2015$43ec7ca7d28669022210915139f0ac89effa67a9e8a374094088d2fbb44a416a.json
app_1       |     8/10: http://packagist.org/p/provider-2017-07$7361524edaa892f26decac049b04f8bf38fe0161c423c190b187b8cca2580e14.json
app_1       |     9/10: http://packagist.org/p/provider-2017-01$515eeface3267427a5d712e3a33299624c1209ff17ea6d284de9e6bb2fb2ce0c.json
app_1       |     10/10:        http://packagist.org/p/provider-2016$f0a5e2ba3c2547f43c09fe82f50de4a66d5f26930db777c1be60e76eb9d6d828.json
app_1       |     Finished: success: 10, skipped: 0, failure: 0, total: 10
app_1       | Installing symfony/skeleton (v3.3.5)
app_1       |   - Installing symfony/skeleton (v3.3.5): Downloading (100%)
app_1       | Created project in tmp
app_1       |     1/1:  http://packagist.org/p/provider-latest$1d64e5f21493f8539c798041a93870f433bca9aabecc03e1c407e0e3732ac7b2.json
app_1       |     Finished: success: 1, skipped: 0, failure: 0, total: 1
app_1       | Loading composer repositories with package information
app_1       | Updating dependencies (including require-dev)
app_1       |     1/24: https://codeload.github.com/php-fig/simple-cache/legacy.zip/753fa598e8f3b9966c886fe13f370baa45ef0e24
app_1       |     3/24: https://codeload.github.com/php-fig/cache/legacy.zip/d11b50ad223250cf17b86e38383413f5a6764bf8
app_1       |     3/24: https://codeload.github.com/symfony/polyfill-apcu/legacy.zip/04f62674339602def515bff4bc6901fc1d4951e8
app_1       |     4/24: https://codeload.github.com/symfony/flex/legacy.zip/321a45a4668a583107e7474d077b5b58fdae2b44
app_1       |     5/24: https://codeload.github.com/doctrine/cache/legacy.zip/b3217d58609e9c8e661cd41357a54d926c4a2a1a
app_1       |     6/24: https://codeload.github.com/symfony/cache/legacy.zip/5f78b9728869434a445bdd86d63ef723f93e5433
app_1       |     7/24: https://codeload.github.com/php-fig/container/legacy.zip/b7ce3b176482dbbc1245ebf52b181af44c2cf55f
app_1       |     8/24: https://codeload.github.com/symfony/dotenv/legacy.zip/ac86b6e484ae9224be290f3a0686858ba18d49d5
app_1       |     9/24: https://codeload.github.com/symfony/filesystem/legacy.zip/90bc45abf02ae6b7deb43895c1052cb0038506f1
app_1       |     10/24:        https://codeload.github.com/symfony/yaml/legacy.zip/8c7bf1e7d5d6b05a690b715729cb4cd0c0a99c46
app_1       |     11/24:        https://codeload.github.com/symfony/config/legacy.zip/4ab62407bff9cd97c410a7feaef04c375aaa5cfd
app_1       |     12/24:        https://codeload.github.com/symfony/class-loader/legacy.zip/7572c904b209fa9907c69a6a9a68243c265a4d01
app_1       |     13/24:        https://codeload.github.com/symfony/finder/legacy.zip/773e19a491d97926f236942484cb541560ce862d
app_1       |     14/24:        https://codeload.github.com/symfony/stopwatch/legacy.zip/170edf8b3247d7b6779eb6fa7428f342702ca184
app_1       |     15/24:        https://codeload.github.com/symfony/event-dispatcher/legacy.zip/d7ba037e4b8221956ab1e221c73c9e27e05dd423
app_1       |     16/24:        https://codeload.github.com/symfony/polyfill-mbstring/legacy.zip/2ec8b39c38cb16674bbf3fea2b6ce5bf117e1296
app_1       |     17/24:        https://codeload.github.com/php-fig/log/legacy.zip/4ebe3a8bf773a19edfe0a84b6585ba3d401b724d
app_1       |     18/24:        https://codeload.github.com/symfony/debug/legacy.zip/eb95d9ce8f18dcc1b3dfff00cb624c402be78ffd
app_1       |     19/24:        https://codeload.github.com/symfony/http-foundation/legacy.zip/22cf9c2b1d9f67cc8e75ae7f4eaa60e4c1eff1f8
app_1       |     20/24:        https://codeload.github.com/symfony/http-kernel/legacy.zip/654f047a78756964bf91b619554f956517394018
app_1       |     21/24:        https://codeload.github.com/symfony/routing/legacy.zip/2e26fa63da029dab49bf9377b3b4f60a8fecb009
app_1       |     22/24:        https://codeload.github.com/symfony/console/legacy.zip/116bc56e45a8e5572e51eb43ab58c769a352366c
app_1       |     23/24:        https://codeload.github.com/symfony/dependency-injection/legacy.zip/8ebad929aee3ca185b05f55d9cc5521670821ad1
app_1       |     24/24:        https://codeload.github.com/symfony/framework-bundle/legacy.zip/f440e16fc2ab880f97149552e79d6d2d6fc243db
app_1       |     Finished: success: 24, skipped: 0, failure: 0, total: 24
app_1       | Package operations: 24 installs, 0 updates, 0 removals
app_1       |   - Installing symfony/flex (v1.0.38): Loading from cache
app_1       |   - Installing psr/log (1.0.2): Loading from cache
app_1       |   - Installing symfony/debug (v3.3.10): Loading from cache
app_1       |   - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
app_1       |   - Installing symfony/console (v3.3.10): Loading from cache
app_1       |   - Installing symfony/stopwatch (v3.3.10): Loading from cache
app_1       |   - Installing symfony/routing (v3.3.10): Loading from cache
app_1       |   - Installing symfony/http-foundation (v3.3.10): Loading from cache
app_1       |   - Installing symfony/event-dispatcher (v3.3.10): Loading from cache
app_1       |   - Installing symfony/http-kernel (v3.3.10): Loading from cache
app_1       |   - Installing symfony/finder (v3.3.10): Loading from cache
app_1       |   - Installing symfony/filesystem (v3.3.10): Loading from cache
app_1       |   - Installing psr/container (1.0.0): Loading from cache
app_1       |   - Installing symfony/dependency-injection (v3.3.10): Loading from cache
app_1       |   - Installing symfony/config (v3.3.10): Loading from cache
app_1       |   - Installing symfony/class-loader (v3.3.10): Loading from cache
app_1       |   - Installing symfony/polyfill-apcu (v1.6.0): Loading from cache
app_1       |   - Installing psr/simple-cache (1.0.0): Loading from cache
app_1       |   - Installing psr/cache (1.0.1): Loading from cache
app_1       |   - Installing symfony/cache (v3.3.10): Loading from cache
app_1       |   - Installing doctrine/cache (v1.7.1): Loading from cache
app_1       |   - Installing symfony/framework-bundle (v3.3.10): Loading from cache
app_1       |     Failed to download symfony/framework-bundle from dist: Could not delete /srv/app/tmp/vendor/composer/fded8684/symfony-framework-bundle-f440e16/Tests/Fixtures/Descriptor:
app_1       |     Now trying to download from source
app_1       |   - Installing symfony/framework-bundle (v3.3.10): Cloning f440e16fc2 from cache
app_1       |   - Installing symfony/yaml (v3.3.10): Loading from cache
app_1       |   - Installing symfony/dotenv (v3.3.10): Loading from cache
app_1       | Writing lock file
app_1       | Generating autoload files
app_1       | Symfony operations: 4 recipes (860d7301d9a05e7b8635b0a252ce5cda)
app_1       |   - Configuring symfony/flex (1.0): From github.com/symfony/recipes:master
app_1       |   - Configuring symfony/console (3.3): From github.com/symfony/recipes:master
app_1       |   - Configuring symfony/routing (3.3): From github.com/symfony/recipes:master
app_1       |   - Configuring symfony/framework-bundle (3.3): From github.com/symfony/recipes:master
app_1       | Executing script cache:clear [OK]
app_1       | Executing script assets:install --symlink --relative public [OK]
app_1       |
app_1       |
app_1       |  What's next?
app_1       |
app_1       |
app_1       |   * Run your application:
app_1       |     1. Change to the project directory
app_1       |     2. Execute the php -S 127.0.0.1:8000 -t public command;
app_1       |     3. Browse to the http://localhost:8000/ URL.
app_1       |
app_1       |        Quit the server with CTRL-C.
app_1       |        Run composer require symfony/web-server-bundle for a better web server.
app_1       |
app_1       |   * Read the documentation at https://symfony.com/doc
app_1       |
app_1       | rm: can't remove 'tmp/vendor/symfony/console/Tests/Fixtures': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/console/Tests': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/console': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/dependency-injection/Compiler': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/dependency-injection/Tests/Fixtures/yaml': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/dependency-injection/Tests/Fixtures': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/dependency-injection/Tests': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/dependency-injection': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/framework-bundle/Resources/views/Form': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/framework-bundle/Resources/views': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/framework-bundle/Resources': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/framework-bundle/Tests/Fixtures/Descriptor': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/framework-bundle/Tests/Fixtures': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/framework-bundle/Tests': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony/framework-bundle': Directory not empty
app_1       | rm: can't remove 'tmp/vendor/symfony': Directory not empty
app_1       | rm: can't remove 'tmp/vendor': Directory not empty
app_1       | rm: can't remove 'tmp': Directory not empty

**Comment by vichanse** [comment]
Hey i tried on mac but i'm getting this error 
"NotFoundHttpException No route found for "GET /""
I thought i had just to do docker-compose up -d as you did in ur Symfony 4 run-through presentation at Forum PHP 2017.

Am i missing something?

**Comment by dunglas** [comment]
For Mac it should work. Do you use Docker 4 Mac?

**Comment by vichanse** [comment]
I use docker CE 4 mac

**Comment by dunglas** [comment]
@vichanse you got this screen?

<img width="1552" alt="capture d ecran 2017-11-07 a 00 12 20" src="https://user-images.githubusercontent.com/57224/32468864-5afcaa10-c350-11e7-887d-2d6a9c265813.png">

If yes, it's intended. It's the behavior of Flex without Symfony 3.3 (installed by default). You need to use the beta version of Symfony 4 or 3.4 to get the new homepage.

**Comment by vichanse** [comment]
@dunglas thank you. I had exactly the screen above. I found this article https://dunglas.fr/2017/10/symfony-4-http2-push-and-preloading/ where you talked about "Symfony 4: HTTP/2 Push and Preloading". i used the command line specified in it
##### Optional: use Symfony 4 beta (will default to Symfony 3.3 if you omit this line)
`$ docker-compose build --build-arg STABILITY=beta app`
##### Install Flex and start the project
`$ docker-compose up`

and it's working like a charm 👍 
![screen shot 2017-11-07 at 05 55 42](https://user-images.githubusercontent.com/26761479/32477812-38b4c61e-c381-11e7-8669-a4d0f28a75e6.png)

You should probably update your installation guide for people like me 😜 
By the way, great job👏

**Comment by JulienMarliac** [comment]
Hey,

I'm having the same issue ' rm: can't remove  * ' on Windows, any fix for that ?

**Comment by maxhelias** [comment]
Can you create a new issue with copying the output of your docker log please
And are you on the latest version ?
