### ISSUE TITLE
How to change permissions to current user?

### ISSUE THREAD

**Issue by veego** [dunglas/symfony-docker#132]
All Symfony folders belong to 'root' user, how to change that to the current user?
Is it enough to use `chmod` once for development, or I have to change some docker files?

**Comment by jdreesen** [comment]
According to [the docs](https://github.com/dunglas/symfony-docker/blob/main/docs/troubleshooting.md#editing-permissions-on-linux) changing the owner should be sufficient.

**Comment by veego** [comment]
Thank you, but if I install additional bundles, I have to repeat that command again, for ex. `composer require symfony/security-bundle`, after this the `security.yml` belongs to `root`.

**Comment by RootProgger** [comment]
thats real, on each use of terminal for the container, eg composer or bin/console (migrations, make:entity...), the rights musst be setted again.

**Comment by jdreesen** [comment]
If you use `docker-compose run --rm --user $(id -u):$(id -g) php ...` or `docker-compose exec --user $(id -u):$(id -g) php ...` it should be fine, I guess.

**Comment by maxhelias** [comment]
If the @jdreesen proposal isn't suitable for you, look at here: https://dev.to/acro5piano/specifying-user-and-group-in-docker-i2e I think you should find the best way for you
