### ISSUE TITLE
No releases available for package "pecl.php.net/apcu"

### ISSUE THREAD

**Issue by ostrolucky** [dunglas/symfony-docker#134]
simply run docker-compose up

```
#6 34.27 Build complete.
#6 34.28 Don't forget to run 'make test'.
#6 34.28
#6 34.30 Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20200930/
#6 34.41 find . -name \*.gcno -o -name \*.gcda | xargs rm -f
#6 34.41 find . -name \*.lo -o -name \*.o | xargs rm -f
#6 34.42 find . -name \*.la -o -name \*.a | xargs rm -f
#6 34.42 find . -name \*.so | xargs rm -f
#6 34.42 find . -name .libs -a -type d|xargs rm -rf
#6 34.43 rm -f libphp.la      modules/* libs/*
#6 34.43 rm -f ext/opcache/jit/zend_jit_x86.c
#6 34.44 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
#6 34.44 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
#6 34.44 (1/1) Purging .phpize-deps-configure (20210421.170025)
#6 34.44 OK: 301 MiB in 79 packages
#6 35.03 + pecl install apcu
#6 35.09 No releases available for package "pecl.php.net/apcu"
#6 35.10 install failed
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c set -eux; 	apk add --no-cache --virtual .build-deps 		$PHPIZE_DEPS 		icu-dev 		libzip-dev 		zlib-dev 	; 		docker-php-ext-configure zip; 	docker-php-ext-install -j$(nproc) 		intl 		zip 	; 	pecl install 		apcu 	; 	pecl clear-cache; 	docker-php-ext-enable 		apcu 		opcache 	; 		runDeps="$( 		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions 			| tr ',' '\n' 			| sort -u 			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' 	)"; 	apk add --no-cache --virtual .phpexts-rundeps $runDeps; 		apk del .build-deps]: exit code: 1
ERROR: Service 'php' failed to build
```

**Comment by dunglas** [comment]
It's most likely a network issue or a PECL issue. I'm not sure we can do anything here.

**Comment by ostrolucky** [comment]
Well just remove apcu, opcache is enough

**Comment by dunglas** [comment]
Are you sure about that? It's not what is said in the Symfony documentation (but I'm not sure if it is up to date): https://symfony.com/doc/current/performance.html#install-apcu-polyfill-if-your-server-uses-apc

**Comment by dunglas** [comment]
According to a quick search I just made, APCu is still used by the Doctrine and by the Cache component: 

* https://github.com/symfony/recipes/blob/be987091a077badc8cbc40cd634d6f4448a353f1/symfony/framework-bundle/5.3/config/packages/cache.yaml#L15
* https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/reference/caching.html#caching

**Comment by ostrolucky** [comment]
I'm sorry, isn't this project just a skeleton and people are supposed to adjust it to its needs? You are not breaking anything by dropping apcu here. Change would apply to new users only. You can see on links you provided that APCu is really discouraged for use, so there is no harm to be done to not use it in new projects at least.

**Comment by dunglas** [comment]
Where did you read that using APCu is discouraged? I double checked and didn't find this mention (it's only discouraged in a very specific cache for the cache component, and it looks like it's recommended for Doctrine).

We try to provide production-ready images. I'm not against dropping APCu if it's not commonly used in prod to improve performance, but AFIK it's still the most popular user cache system available.

**Comment by entermix** [comment]
I had the same problem, check the connection with pecl.php.net

**Comment by entermix** [comment]
@ostrolucky I had the same problem, check the connection with pecl.php.net
