### ISSUE TITLE
Ssl error when accessing localhost

### ISSUE THREAD

**Issue by SylvanoTombo** [dunglas/symfony-docker#136]
I followed the documentation but when i accessed https://127.0.0.1 i have an error:

This site can’t provide a secure connection

127.0.0.1 sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

I see in the docker log "caddy":
Warning: "certutil" is not available, install "certutil" with "apt install libnss3-tools" or "yum install nss-tools" and try again

**Comment by dunglas** [comment]
Can you try with `localhost` instead of `127.0.0.1` please?

**Comment by SylvanoTombo** [comment]
It's work great! Thanks!
