### ISSUE TITLE
install full symfony/website-skeleton

### ISSUE THREAD

**Issue by ziat1988** [dunglas/symfony-docker#145]
I would like to have the symfony/website-skeleton.
I have tried to modify Dockerfile to :

 _RUN composer create-project "symfony/website-skeleton ${SYMFONY_VERSION}" . --stability=$STABILITY --prefer-dist --no-dev --no-progress --no-interaction; 
	
But I always have the version skeleton. 
How do I do to install symfony/website-skeleton instead? 
Thanks

**Comment by maxhelias** [comment]
You need to change this line too : https://github.com/dunglas/symfony-docker/blob/main/docker/php/docker-entrypoint.sh#L20

Or you can add each dependency manually after the build

**Comment by ziat1988** [comment]
Thank you for the answer. I have modified that line in docker-entrypoint.sh and after do "docker-compose up"  I have all the packages I need. However, while the console running, it said "Still waiting for db to be ready... Or maybe the db is not reachable. xxx attempts left"
In docker-compose.yml, I have this line:
DATABASE_URL: postgresql://${POSTGRES_USER:-symfony}:${POSTGRES_PASSWORD:-ChangeMe}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-13}
and in .env:
DATABASE_URL="postgresql://db_user:db_password@127.0.0.1:5432/db_name?serverVersion=13&charset=utf8"

So how I can fix it and connect to the database? And what if I want to change to mysql ?
