### ISSUE TITLE
Installing symfony/messenger doesn't update Docker

### ISSUE THREAD

**Issue by simondeeley** [dunglas/symfony-docker#147]
The documentation says that the `symfony/messenger` package is supported by way of auto-configuring a `RabbitMQ` service in Docker. 

I have tried this several times, even from a fresh install of your template, but no additional configuration beyond the normal Symfony stuff occurs. 

Question is - Is the documentation correct? Am I doing something wrong? (for example, are there additional configuration settings I need to apply in order for Docker to auto-configure the `RabbitMQ` service?

**Comment by dunglas** [comment]
Messenger moved from Rabbit to Postgres by default. So the Rabbit service isn't installed anymore. We need to update the docs.

**Comment by simondeeley** [comment]
That makes sense why it doesn't install `RabbitMQ` any more 😉
