### ISSUE TITLE
Cannot autowire service

### ISSUE THREAD

**Issue by SebF33** [dunglas/symfony-docker#166]
When I start Docker-compose up I have this error :

In DefinitionErrorExceptionPass.php line 54:
                                                                                                                                                    
  Cannot autowire service "App\Command\InsuranceCertificateExpirationCommand": argument "$contractRepository" of method "__construct()" reference   
  s class "App\Repository\ContractRepository" but no such service exists. 

This problem is only in Windows environment, it's okay on MacOS for my project.

**Comment by maxhelias** [comment]
This issue is not related to this project. It's probably an issue with the docker configuration on Windows.

**Comment by ChuGui** [comment]
@SebF33 I'm facing the same problem with docker windows 10 and symfony. 
Did you find any solution ?

**Comment by hamza-abed** [comment]
Hello @SebF33 @ChuGui  
I am facing the same problem with same config
any solution please?

**Comment by tsiatka** [comment]
Same issue here, any solution ?

**Comment by 7-zete-7** [comment]
@tsiatka, seems like you environment is not initialized propertly. Try to execute this command in the `php` container to (re-) initialize you project:
```shell
composer install
```

And yes — this issue does not relate to this project.

There is probably a problem with the configuration of the service container or environment.
