### ISSUE TITLE
Multikernel Aplication

### ISSUE THREAD

**Issue by CarlosGude** [dunglas/symfony-docker#167]
Hello everyone:

In my company, we use a multikernel application for different apis. The directory structure is this:

project/
├─ src/
│  ├─ ...
│  └─ Kernel.php
├─ app/
│  ├─ APP1/
│       ├─ ...
│       └─ Kernel.php
│  ├─ APP2/
│  ├─ APP3/
│  └─ ApiKernel.php
├─ ...
└─ public/
    ├─ ...
    ├─ api.php
    └─ index.php

I need to configure a docker, what when, I up the docker, all apis was available in a domanin (custom or localhost:800X)

Can someone help me?

**Comment by maxhelias** [comment]
Hello,

You need to adjust the caddyfile. Mainly added a new route (https://caddyserver.com/docs/caddyfile/directives/route#route) if you want it on another port and mapping this new port on the docker-compose file.

Good luck
