### ISSUE TITLE
API does not found the routes on mode production

### ISSUE THREAD

**Issue by djorellanabmrb** [dunglas/symfony-docker#168]
Hey everyone,

I developed an API with your template, but I have a problem, When the application is deployed on mode "dev",  all routes are founded, but when is changed on mode "prod" does not work (i.e. the routes are not founded, error 404).

Also I have another question, how do you create JWT of the Mercure.

Greeting!

**Comment by maxhelias** [comment]
Hey!

We can't help you to debug your routes. You probably missed your Symfony configuration or a leftover cache, something like that.

For JWT generation, you can use : https://jwt.io/

**Comment by djorellanabmrb** [comment]
You are right, it was failed on my environment file (.env) !
