### ISSUE TITLE
Docker-compose build -> [Makefile:209: php_intl.lo] Error 127 

### ISSUE THREAD

**Issue by djorellanabmrb** [dunglas/symfony-docker#169]
In those days, PHP Docker pushed a new image of the 8-fpm-alpine, that have a problem with Make library:

![make error](https://user-images.githubusercontent.com/70344779/126208492-7e067e53-fa4b-4f58-8e31-0f22b5362337.PNG)

So for me the solution was change of the image on the line 11 of the Dockerfile ( [8.0.8-fpm-alpine3.13](https://hub.docker.com/layers/php/library/php/8.0.8-fpm-alpine3.13/images/sha256-edf14dea600ac1372a68d3fe6f96c98c588191916f024492fd55eda4a50a7784?context=explore)  worked for me)

**Comment by maxhelias** [comment]
Looks like there was a new image available and seems to be fixed.
