### ISSUE TITLE
Building fresh images fail

### ISSUE THREAD

**Issue by Crovitche-1623** [dunglas/symfony-docker#173]
Hello,
When I run `docker-compose build --pull --no-cache` as indicated in the documentation. I always get one of these error messages:

![image](https://user-images.githubusercontent.com/35468476/130694573-2afd6b7d-20f3-4a4a-be09-f9d9fc90b1de.png)
![image](https://user-images.githubusercontent.com/35468476/130694692-615c41a8-1570-48c2-8c86-bfedef37d978.png)
![image](https://user-images.githubusercontent.com/35468476/130694978-761185f2-e4a5-4822-8e76-e6fd4c380886.png)

Where can this be coming from ?
I am on Windows 10 with WSL2 & Docker version 20.10.8.
I hope you can help me, thanks in advance !

**Comment by rowanparker** [comment]
Refer to this issue:
https://github.com/dunglas/symfony-docker/issues/139

It's likely a DNS problem on your end. Try disabling IPv6 on your ethernet adaptor and see if it works.

**Comment by djhipps** [comment]
I also got this faliure on wsl2, Windows 11, 4.1.1, IPv6 disabled. It still did not work. I don't think it is a networking issue.

**Comment by maxhelias** [comment]
As example @rowanparker, this is a known issue that we have already had and investigated many time. Often, it is a network or PECL issue.

You will find all the information here : #139
