### ISSUE TITLE
Production mode does not update project files live

### ISSUE THREAD

**Issue by Jamezsss** [dunglas/symfony-docker#174]
So I tried setting it up for a production server. (Bear with me I am a coder and not a server manager)
It runs fine when I build it in production mode. But when I upload files with rsync to the production environment (Gitlab runner) the changes do not get reflected unless I rebuild the whole production server which means the website needs to be offline and rebuild the server with every update I do to my project. The files are copied correctly though and when I look in the files in my production server it did update. It just doesn't show. I tried clearing cache, checked if copied correctly. Only solution for me is to rebuild the production server. Is this normal?

**Comment by feyyazesat** [comment]
@Jamezsss isn't that normal if you are aiming for immutable releases?

**Comment by Jamezsss** [comment]
I'm not sure about the term immutable although I can imagine this must mean this stack was built this way in order to be super fast and preload all the files in memory or something close to that making it impossible to update the files without rebuilding the production server? So basically a compromise for speed and security? And is it possible or even wise to turn that off or make it like the files will update when being pushed to production server?

**Comment by feyyazesat** [comment]
@Jamezsss you can read it from [here](https://www.sumologic.com/insight/mutable-immutable-infrastructure/)

**Comment by Jamezsss** [comment]
Okay so in short it means all dependencies that aren't needed anymore won't remain on the server basically because the whole server gets rebuild and discards the old data completely. But this also means that even for small changes in twig templates I need to rebuild production while nothing in dependencies changed. Plus I could do this myself in my gitlab-ci runner script to remove not used dependencies myself. And what I got from the article is that it has something to do CI mainly.

**Comment by Jamezsss** [comment]
Also I noticed uploading files to the server aka the docker environment in production mode does not work even when I set the folder owner and rights. It does work if I rerun the docker stack in dev mode.

**Comment by beejaz** [comment]
The idea with docker containers in production is that the environment & files are predefined and come as a "package of one". If you get alot of traffic to your site currently, you could spin up 10 new instances with same docker container image and it will be the same site on all 10 instances/hosts. You are not supposed to edit files IN these containers after they are built. Instead one ci/cd script should build one container image, deploy it to a registry for example and then reload/pull the new container image from the registry on your 10 instances/hosts.

As your last comment, if your production server runs the code in production mode then files are cached. You could probably update the files and run like php bin/console cache:clear to update the cache with the new files but that is wrong way to do it. In dev mode, this doesnt cache the same way.

**Comment by maxhelias** [comment]
Thanks @feyyazesat and @beejaz for the answer ;)

**Comment by Jamezsss** [comment]
That didn't answer my question at all. This way nobody is able to upload any files to any website I make, I have no clue how I am suppose to let people upload document or photo's without setting the whole thing up as dev environment. Why did you close the question exactly?

**Comment by rowanparker** [comment]
Users can upload files to your website, they would just be saved _inside_ the docker container. If you destroy and recreate the containers, then yes, those files would be lost. One solution is to mount a separate volume, that will persist across rebuilds.  Add something like this to the volumes on php:

```
volumes:
  - ./uploads:/srv/app/uploads
```

Store the uploaded files in /srv/app/uploads in your app. They will also be available on your docker host. This would be fine for a single instance of your project.

If your website grew to the point that you needed multiple php containers, you need a way to save those user files separately from the container (so you can launch multiple of them). That's where you might look at a 3rd party storage option (maybe S3).

**Comment by Jamezsss** [comment]
Great! This is mainly what kept me from progressing. I do get better how this docker environment is suppose to work and is optimized for load balancing etc in production mode. And that I can mount my own folders for file uploads instead of rebuilding the containers and indeed I make small projects for now that don't need to be deployed to multiple servers. This is why I got confused with the former answers but learned a lot nonetheless. 

I appreciate all the info guys! :) tyvm

**Comment by maxhelias** [comment]
@Jamezsss You will also have the same problem with your sessions (can be stored in database, redis or something else) and your logs (try monolog).

**Comment by Jamezsss** [comment]
Thanks for the tip Max, I will be looking into it tomorrow and try out what you guys suggested. Thanks for the support :)
