### ISSUE TITLE
"connection failed" on localhost (docker-compose v2)

### ISSUE THREAD

**Issue by GErpeldinger** [dunglas/symfony-docker#179]
Hello,

I am posting this issue in case someone else has the same problem.

I use docker desktop on mac os, from one day to the other, my project using symfony-docker was not working anymore, I kept getting "Connection failed" on my https://localhost/ or http://localhost:80

After a long time looking for the problem, I realized that docker desktop had activated the "Use Docker Compose V2 release candidate" option through the notification center and once unchecked and docker restarted everything was back in order

<img width="1191" alt="Capture d’écran 2021-09-29 à 20 19 20" src="https://user-images.githubusercontent.com/60388866/135326301-3fd78fab-13b7-4bcf-82d5-cdaa6fc08f67.png">

For the V2,

I have tried with the new command "docker compose" (with space), but I have the same result. I don't know if it's a bug with docker compose v2, my configuration or an incompatibility between docker compose v2 and caddy.

I checked the caddy logs and there is no particular error

MacOS : 11.6
Docker engine : 20.10.8
Docker compose : 2.0.0-rc.3
Docker desktop : 4.0.1

**Comment by dunglas** [comment]
Yes it's a known issue that is being worked on by Docker: https://github.com/docker/compose/issues/8557

**Comment by GErpeldinger** [comment]
Oh ! Thanks for the information
