### ISSUE TITLE
Adding PostgreSQL

### ISSUE THREAD

**Issue by gdarquie** [dunglas/symfony-docker#182]
I used this repo for an existing project and I add to adapt the code a little. I met some difficulties when I try to install Psql.

I am not sure if it can help (maybe it was just my customization) or what to do with that (a PR? :-/) so I put it here.

For resolving the problem, i needed to add two lines in Dockerfile: 

In 
```
  apk add --no-cache --virtual .build-deps \
  $PHPIZE_DEPS \
  icu-dev \
  libzip-dev \
  zlib-dev \
```
Add 
```
postgresql-dev \
```
In 

```
docker-php-ext-install -j$(nproc) \
  intl \
  zip \
  ; \
```
Add 
```
  pdo_pgsql \
```

The result

```
  ARG APCU_VERSION=5.1.20
  RUN set -eux; \
  apk add --no-cache --virtual .build-deps \
  $PHPIZE_DEPS \
  icu-dev \
  libzip-dev \
  zlib-dev \
  postgresql-dev \
  ; \
  \
  docker-php-ext-configure zip; \
  docker-php-ext-install -j$(nproc) \
  intl \
  zip \
  pdo_pgsql \
  ; \
  pecl install \
  apcu-${APCU_VERSION} \
  ; \
  pecl clear-cache; \
  docker-php-ext-enable \
  apcu \
  opcache \
  ; \
```

**Comment by rowanparker** [comment]
The same type of issue occurs if you want to add MariaDB or MySQL - you have to add those dependencies manually. This is a result of trying to implement this repo on an existing project.

If you were cloning this repository, then installing doctrine via composer, the Flex recipes automatically updates your Dockerfile to include the required extension (at least for Postgres).

**Comment by bogdaniel** [comment]
Shouldn't the database be separated from the Dockerfile so it can be used in production ?

**Comment by maxhelias** [comment]
With this project, you don't have any database provided.
You can have one configured with recipes or with the maker-bundle but you will need to install the associated php extension on your Dockerfile
