### ISSUE TITLE
website skeleton remove php and caddy services from docker-compose.yml

### ISSUE THREAD

**Issue by CedCannes** [dunglas/symfony-docker#192]
I tried the command provided in the doc :

`SKELETON=symfony/website-skeleton docker-compose up --build`

and when the build of the containers are finished the docker-compose.yaml file was modified, it doesn't have php and caddy services anymore, instead there is a mail and database service.
Here is the content of the git diff just after the build command 

```
diff --git a/docker-compose.override.yml b/docker-compose.override.yml
index 901e2b3..c042a70 100644
--- a/docker-compose.override.yml
+++ b/docker-compose.override.yml
@@ -1,22 +1,14 @@
-version: "3.4"
+version: '3'
 
-# Development environment override
 services:
-  php:
-    volumes:
-      # The "cached" option has no effect on Linux but improves performance on Mac
-      - ./:/srv/app:rw,cached
-      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
-      # If you develop on Mac you can remove the var/ directory from the bind-mount
-      # for better performance by enabling the next line 
-      # - /srv/app/var
-    environment:
-      APP_ENV: dev
+###> symfony/mailer ###
+  mailer:
+    image: schickling/mailcatcher
+    ports: [1025, 1080]
+###< symfony/mailer ###
 
-  caddy:
-    volumes:
-      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
-      - ./public:/srv/app/public:ro
-
-###> symfony/mercure-bundle ###
-###< symfony/mercure-bundle ###
+###> doctrine/doctrine-bundle ###
+  database:
+    ports:
+      - "5432"
+###< doctrine/doctrine-bundle ###
diff --git a/docker-compose.yml b/docker-compose.yml
index 52ab863..a80a8cf 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,66 +1,21 @@
-version: "3.4"
+version: '3'
 
 services:
-  php:
-    build:
-      context: .
-      target: symfony_php
-      args:
-        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
-        SKELETON: ${SKELETON:-symfony/skeleton}
-        STABILITY: ${STABILITY:-stable}
-    restart: unless-stopped
-    volumes:
-      - php_socket:/var/run/php
-    healthcheck:
-      interval: 10s
-      timeout: 3s
-      retries: 3
-      start_period: 30s
-    environment:
-      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
-      DATABASE_URL: postgresql://${POSTGRES_USER:-symfony}:${POSTGRES_PASSWORD:-ChangeMe}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-13}
-      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
-      MERCURE_URL: ${CADDY_MERCURE_URL:-http://caddy/.well-known/mercure}
-      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
-      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}
-
-  caddy:
-    build:
-      context: .
-      target: symfony_caddy
-    depends_on:
-      - php
+###> doctrine/doctrine-bundle ###
+  database:
+    image: postgres:${POSTGRES_VERSION:-13}-alpine
     environment:
-      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
-      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}
-      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}
-    restart: unless-stopped
+      POSTGRES_DB: ${POSTGRES_DB:-app}
+      # You should definitely change the password in production
+      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
+      POSTGRES_USER: ${POSTGRES_USER:-symfony}
     volumes:
-      - php_socket:/var/run/php
-      - caddy_data:/data
-      - caddy_config:/config
-    ports:
-      # HTTP
-      - target: 80
-        published: 80
-        protocol: tcp
-      # HTTPS
-      - target: 443
-        published: 443
-        protocol: tcp
-      # HTTP/3
-      - target: 443
-        published: 443
-        protocol: udp
-
-# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
-###> symfony/mercure-bundle ###
-###< symfony/mercure-bundle ###
+      - db-data:/var/lib/postgresql/data:rw
+      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
+      # - ./docker/db/data:/var/lib/postgresql/data:rw
+###< doctrine/doctrine-bundle ###
 
 volumes:
-  php_socket:
-  caddy_data:
-  caddy_config:
-###> symfony/mercure-bundle ###
-###< symfony/mercure-bundle ###
+###> doctrine/doctrine-bundle ###
+  db-data:
+###< doctrine/doctrine-bundle ###
```

So I deleted and started again without mentioning the skeleton so that it works with the default one.

**Comment by gothick** [comment]
I'm also seeing this—looks like maybe the doctrine bundle recipe clobbers the docker-compose.yml file completely, leaving it with nothing but what the recipe should add? I can't quite figure out what's going on.

**Comment by Sebastien-Lataix** [comment]
Same issue this day

**Comment by mayiencode** [comment]
For website-skeleton, according to Symfony's documentation, now, we need to add "composer require webapp" 

![image](https://user-images.githubusercontent.com/44878079/152680929-14094e67-4f9d-45f7-8bda-0b168395969f.png)

The DockerFile should be update with this.

**Comment by alcidesrh** [comment]
Same issue bu I was able to set up a website skeleton as next:

`
docker-compose build --pull --no-cache // This will install just the basic skeleton.

composer require webapp // This will install the website requires bundles. Note the docker-compose. (yml | prod.yml | 
                                          //override.yml ) all were properly updated.
`

**Comment by mchojrinreloadly** [comment]
> composer require webapp

In order to make this work I had to take a few extra steps:

1. `docker-compose build --pull --no-cache`
2. `docker-compose up -d`
3. `docker-compose exec php composer require webapp`

 Only then could I get a 200 response at `https://localhost`

**Comment by michael-schaefer-eu** [comment]
In addition to the described problem [above](https://github.com/dunglas/symfony-docker/issues/192#issue-1059525023) with the `docker-compose` files, also the `Dockerfile` is _not_ updated with sql drivers, as we found out [in this issue](https://github.com/dunglas/symfony-docker/issues/231).

**Comment by freiondrej-lmc** [comment]
I can confirm that when following https://github.com/dunglas/symfony-docker/issues/192#issuecomment-1075269831, I did not get #233. (the only slight alteration was in step 3. where I had to do `docker-compose exec php sh` and then extra `composer require webapp`, probably due to $PWD mismatch)

**Comment by IvoPereira** [comment]
I am facing exactly the same issue.

My experience has been quite inconsistent even with the workarounds mentioned.

I have literally added the `composer require webapp` to the Dockerfile and the docker-entrypoint, however I started having some other strange issues, like @michael-schaefer-eu pointed out.

This basically is preventing me from using this repo as a repo until I am able to understand deeply what might be causing the issue.

**Comment by MaxiCom** [comment]
I ran into the same issue today!

**Comment by maxhelias** [comment]
The `SKELETON` option has been removed since Symfony has implemented the webapp-pack which replaces the website-skeleton. See more information here https://github.com/dunglas/symfony-docker/issues/269

With this package it changes the way of this project works and corrects your mistake. Don't hesitate to re-open if necessary

**Comment by RudyLaban** [comment]
Just to clarify. After building the image and start the project, if I want a full "web application", I have to run `composer require webapp`?
