### ISSUE TITLE
pdo_mysql extension not installed/enabled

### ISSUE THREAD

**Issue by SundownDEV** [dunglas/symfony-docker#20]
~~~bash
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-pdo_mysql * is missing from your system. Install or enable PHP's pdo_mysql extension.

ERROR: Service 'app' failed to build: The command '/bin/sh -c mkdir -p var/cache var/logs var/sessions     && composer install --prefer-dist --no-dev --no-progress --no-suggest --classmap-authoritative --no-interaction 	&& composer clear-cache 	&& chown -R www-data var' returned a non-zero code: 2
~~~

Ubuntu 18.04 LTS
Docker version 17.12.1-ce, build 7390fc6
docker-compose version 1.17.1, build unknown

**Comment by maxhelias** [comment]
If you've added dependencies to Symfony skeleton, they are currently not supported on the Docker. You will need to add the necessary services and php extensions related to your dependencies.
Currently, there is work to automate this action with [Flex](symfony/flex#128) & [Recipes](symfony/recipes#113). Do not hesitate to make returns 😉

**Comment by SundownDEV** [comment]
Thank you @maxhelias 

Adding `RUN docker-php-ext-install pdo pdo_mysql` in the Dockerfile fixed the error.
