### ISSUE TITLE
Is it a good idea to use only one Dockerfile?

### ISSUE THREAD

**Issue by relthyg** [dunglas/symfony-docker#201]
I was wondering if the current setup with two build stages for PHP and Caddy makes really sense. I mean, when building the Caddy service, the whole `php_symfony` stage is run as well, albeit this is not needed.

Would it rather make sense to provide two different Dockerfiles, one for PHP and one for Caddy?

**Comment by tuxfy** [comment]
I had the same thoughts while adding a node container.

**Comment by dunglas** [comment]
This is needed because of the static files provided by the Symfony app: https://github.com/dunglas/symfony-docker/blob/main/Dockerfile#L131
So I'm not sure that it makes sense to use two different Dockerfiles.

**Comment by relthyg** [comment]
Ah, ok, I didn't get that. Sorry for bothering.
