### ISSUE TITLE
Install xdebug in dev by default?

### ISSUE THREAD

**Issue by relthyg** [dunglas/symfony-docker#202]
Do we maybe want something like

    ARG XDEBUG_VERSION=3.1.2
    ARG APP_ENV=dev
    ENV APP_ENV ${APP_ENV}
    RUN if [ "${APP_ENV}" == 'dev' ]; then \
		    apk add --no-cache --virtual .build-deps \
			    $PHPIZE_DEPS \
		    ; \
		    \
		    pecl install \
			    xdebug-${XDEBUG_VERSION} \
		    ; \
		    pecl clear-cache; \
		    docker-php-ext-enable \
			    xdebug \
		    ; \
		    \
		    runDeps="$( \
			    scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
				    | tr ',' '\n' \
				    | sort -u \
				    | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
		    )"; \
		    apk add --no-cache --virtual .phpexts-rundeps $runDeps; \
		    \
		    apk del .build-deps; \
        fi

instead of just documenting how to make use of it?

**Comment by dunglas** [comment]
Now that XDebug 3 can run with almost 0 overhead, why not, as long as we set `XDEBUG_MODE=off` by default.
We must also do the same thing in API Platform's Docker distribution then.

**Comment by Growiel** [comment]
Not everybody uses it, the document is clear about how adding it, I say keep it that way (just update the doc for Xdebug 3.1.2).

**Comment by grambas** [comment]
> Not everybody uses it, the document is clear about how adding it, I say keep it that way (just update the doc for Xdebug 3.1.2).

 I think, argument that not everybody uses it not quit strong,. I could say, that git which is installed in this container is also not necessary for php image where code is copied during buld process. XDebug helps for debbuging a lot, and it could be good practice to include it by default or with enable/disable ENV. Especially if it has almost zero overhead if it is disabled as @dunglas says.
