### ISSUE TITLE
Bug SYMFONY_VERSION=4.4.* docker-compose up --build or other cmd

### ISSUE THREAD

**Issue by MakFly** [dunglas/symfony-docker#206]
Hi everyone , 

I try to install a project symfony docker but i have this message after run cmd : SYMFONY_VERSION=4.4.* docker-compose up --build

ERROR: Invalid interpolation format for "build" option in service "php": "${SYMFONY_VERSION:-}"

**Comment by maxhelias** [comment]
I am not able to reproduce the issue... Are you using a recent version of docker? What is your version?

**Comment by hellomedia** [comment]
Getting the same error with
- docker 17.05
- docker-compose 1.11.2

What are the recommended minimum versions ?
