### ISSUE TITLE
Host directory is not mounted when "docker-compose up" with debug config on Windows

### ISSUE THREAD

**Issue by simajkeee** [dunglas/symfony-docker#212]
When execute "docker-compose up"  i can see that the host directory is mounted and when files are changed on the host the changes are applied to files in the container. The problem arise when execute "docker-compose -f docker-compose.yml -f docker-compose.debug.yml up -d" the host directory is not mounted and files in the container cannot be changed trough the host directory. What would you advise to resolve the issue?

**Comment by SanderVerkuil** [comment]
`docker-compose.yml` doesn't mount the directories, and I'm not sure what the contents of your `docker-compose.debug.yml` is, but when you specify files, the `docker-compose.override.yml` is not used. So run the command `docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.debug.yml` mount the volumes. Or copy the `volumes` directive from the `docker-compose.override.yml` into `docker-compose.debug.yml`.

**Comment by simajkeee** [comment]
Now it works, thank you!
