### ISSUE TITLE
Waiting for db to be ready...

### ISSUE THREAD

**Issue by jscepansalt** [dunglas/symfony-docker#215]
https://github.com/dunglas/symfony-docker/blob/fcff96b69136c0acf731084cb64d32ad32b92733/docker/php/docker-entrypoint.sh#L45

I have tried to setup this docker and following error is hidden:
    There are no commands defined in the "dbal" namespace. 
for call 
bin/console dbal:run-sql "SELECT 1".
It prevents to finish docker-entrypoint.sh script.
php-1    | Waiting for db to be ready...
php-1    | Still waiting for db to be ready... Or maybe the db is not reachable. 59 attempts left
php-1    | Still waiting for db to be ready... Or maybe the db is not reachable. 58 attempts left
php-1    | Still waiting for db to be ready... Or maybe the db is not reachable. 57 attempts left

What helped, is to use:
bin/console doctrine:query:sql "SELECT 1"

**Comment by roby-avo** [comment]
Yes i agree with your suggetion to add this, bin/console doctrine:query:sql "SELECT 1"
But in order to resolve the probelm definitly you can add this lines in docker file:
RUN apk add --no-cache libintl icu icu-dev libxml2-dev \
 && docker-php-ext-install intl

# pdo_mysql
RUN docker-php-ext-install pdo_mysql

**Comment by maxhelias** [comment]
The command `doctrine:query:sql` is deprecated since doctrine/doctrine-bundle:2.2.

Sorry but I don't really understand your issue.

**Comment by jscepansalt** [comment]
I had
RUN docker-php-ext-install pdo pdo_mysql 
in my Dockerfile already, so it wouldn't help.

Our project is based on Symfony 4.4 and
it uses doctrine/doctrine-bundle: 1.12

It might help somebody else or the script could be improved by some warning or comment.

**Comment by maxhelias** [comment]
I did some research and the "dbal:run-sql" command was introduced in version "2.2.x" of doctrine/doctrine-bundle. 
A fresh installation of Symfony 4.4 does not have this problem. What is blocking you for this version?

**Comment by Skkay** [comment]
I also had the same issue but with the following error : `/usr/local/bin/docker-entrypoint: line 45: bin/console: Permission denied`.

I fixed it by replacing `chmod +x bin/console; sync` to `chmod 777 bin/console; sync` in the Dockerfile, line 108.

**Comment by maxhelias** [comment]
We changes the way of this project works since Symfony have a webapp-pack instead of the `SKELETON` option and this rework should corrects your mistake. Don't hesitate to re-open if necessary.

See more information here https://github.com/dunglas/symfony-docker/issues/269
