### ISSUE TITLE
How to access to extra services ?

### ISSUE THREAD

**Issue by Romaixn** [dunglas/symfony-docker#225]
Hello, when installing symfony mailer it configures a new service in docker-compose.override.yml : 

```
###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###
```

But how do we access it? With localhost:1080 I have "localhost does not allow connection".

Thanks for your help !

**Comment by maxhelias** [comment]
Hello @Romaixn,
The current configuration lets docker-compose choose an available port for you. We just tell him that we need a mapping on these ports.
You need to look at which port the 1080 is mapped to on your machine.

Too see it use the command "docker-compose ps", in my example docker choose for me "50529" :
![Capture d’écran 2022-03-10 à 11 47 06](https://user-images.githubusercontent.com/12966574/157646251-6bb21c6f-ec66-4c9e-a930-0cdbf695693f.png)
