### ISSUE TITLE
Installing profiler returns error

### ISSUE THREAD

**Issue by agennari** [dunglas/symfony-docker#230]
Hello

I'm tring to install the symfony toolbar (profiler).
But, when I'm building the docker image, I go an error.
How to reproduce: 

- Install fresh project 
- build & up
- run "composer require --dev symfony/profiler-pack" in the php container
- try to build again the image

Got this error during the build step:

```
+ composer run-script --no-dev post-install-cmd

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Error: Class "Symfony\Bundle\TwigBundle\TwigBundle" not found in /srv/app/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:131
```

does anyone already faced this? 
Thanks

**Comment by maxhelias** [comment]
Hello,

It looks like your project has no direct dependency to "symfony/twig-bundle". Try to install the template pack with `composer require symfony/twig-pack`.

BTW, you'll have a better chance of getting quicker and more accurate answers on the right repository 😉
