### ISSUE TITLE
Waiting for db to be ready

### ISSUE THREAD

**Issue by freiondrej-lmc** [dunglas/symfony-docker#231]
Hello,
first of all, thank you for this amazing project!
I used `SKELETON=symfony/website-skeleton SYMFONY_VERSION=5.4.* docker-compose up --build` to create the website-skeleton for Symfony 5.4.3.
After a while, the project told me "To finish the installation please press Ctrl+C to stop Docker Compose and run: docker-compose up --build". After using ctrl+c to stop docker compose, I manually edited docker-compose.yml and docker-compose.override.yml because of [this issue](https://github.com/dunglas/symfony-docker/issues/192) so that there were all services (php, caddy and database, and mailer in override) and ran `docker-compose up --build` as advised.
However, there I got stuck with "Waiting for db to be ready...", then "Still waiting for db to be ready... Or maybe the db is not reachable. N attempts left" 60 times and then the whole process restarted and I again got the "Waiting for db to be ready..." message.
I then even retried without specifying SYMFONY_VERSION and the problem was the same.
Did I do something wrong? I tried to follow the README as closely as possible.
Is it possibly some conincidence of some recent release of a symfony / doctrine package that breaks the functionality? Or is it maybe some docker cache from using the skeleton previously, so I should try `docker system prune` or something like that?   
Thank you!

**Comment by michael-schaefer-eu** [comment]
@freiondrej-lmc can you please check if your dockerfile and docker-compose files are modified as it should happen [automatically](https://github.com/dunglas/symfony-docker/blob/main/docs/extra-services.md#support-for-extra-services) and if the DB container is up and running? Maybe it exits with an error and is not available for some reason ?

**Comment by freiondrej-lmc** [comment]
@michael-schaefer-eu could you possibly try for yourself, whether you get the same behavior as me? If not, then it's probably something about my setup 🤔 (which would be kind of weird, because docker should make this kind of problems disappear, but maybe it's something with docker cache or something like that)

**Comment by michael-schaefer-eu** [comment]
@freiondrej-lmc yes I do get the same behavior as you when I do the following:
- I setup a complete new project and build the docker images , start the containers (php & caddy)
- I go into the php container (`docker-compose exec php sh`) and do `composer require symfony/orm-pack`
- This will change some files, especially in the Dockerfile it will add:

```
###> recipes ###
###> doctrine/doctrine-bundle ###
RUN apk add --no-cache --virtual .pgsql-deps postgresql-dev; \
	docker-php-ext-install -j$(nproc) pdo_pgsql; \
	apk add --no-cache --virtual .pgsql-rundeps so:libpq.so.5; \
	apk del .pgsql-deps
###< doctrine/doctrine-bundle ###
###< recipes ###
```

Now I get the same error that you describe - even if the db container is running :
```
...
php_1       | Still waiting for db to be ready... Or maybe the db is not reachable. 0 attempts left
php_1       | In ExceptionConverter.php line 91:
php_1       |   An exception occurred in the driver: could not find driver 
php_1       | In Exception.php line 30:
php_1       |   could not find driver
```

This means that the php postgresql driver is not installed.

Solution: the **images must be build again** with `docker-compose build --pull --no-cache`

Which should result in

```
php_1       | Waiting for db to be ready...
php_1       | The db is now ready and reachable
...
php_1       | [22-Mar-2022 16:22:03] NOTICE: ready to handle connections
```

**Comment by freiondrej-lmc** [comment]
@michael-schaefer-eu thank you for your suggestion. However even after running `docker-compose build --pull --no-cache`, I still get the `could not find driver` exception (thank you for pointing me at it, I missed that in the output at first), so I suppose the recipe should modify the Dockerfile to install postgres driver in php, but it does not.
You also describe different steps than I followed:
> I setup a complete new project and build the docker images , start the containers (php & caddy)
> I go into the php container (docker-compose exec php sh) and do composer require symfony/orm-pack

I did not need to install orm-pack manually because `SKELETON=symfony/website-skeleton SYMFONY_VERSION=5.4.* docker-compose up --build` (advised in https://github.com/dunglas/symfony-docker/blob/main/docs/build.md#selecting-a-symfony-skeleton and https://github.com/dunglas/symfony-docker/blob/main/docs/build.md#selecting-a-specific-symfony-version) does that automatically. So if I understand you correctly, you don't use this to setup a new project. What do you use to "setup a complete new project"? Just `docker-compose up --build` without the `SKELETON` env var?

Could you please try my approach to setup the project if you get the same behavior as me? The steps I do are:
```
git clone https://github.com/dunglas/symfony-docker.git
cd symfony-docker
SKELETON=symfony/website-skeleton SYMFONY_VERSION=5.4.* docker-compose up --build
# manual fixing of the broken Dockerfile and docker-compose.yml as described in my first comment because of https://github.com/dunglas/symfony-docker/issues/192
docker-compose up --build # as advised by "To finish the installation please press Ctrl+C to stop Docker Compose and run: docker-compose up --build"
```
Many thanks for your time! :)

**Comment by michael-schaefer-eu** [comment]
@freiondrej-lmc I see that I formulated my answer totally _misunderstandable_, sorry for that.

I try again:

When I follow the way you described, the recipe **will not edit the Dockerfile** , so that it has on line 95 this:

```
###> recipes ###
###< recipes ###
```

it means that the _sql drivers_ where not added to the php image, and I get the same error as you (also I have to fix the docker-compose files).

Now I added in the Dockerfile (on line 95) this:

###> recipes ###
###> doctrine/doctrine-bundle ###
RUN apk add --no-cache --virtual .pgsql-deps postgresql-dev; \
	docker-php-ext-install -j$(nproc) pdo_pgsql; \
	apk add --no-cache --virtual .pgsql-rundeps so:libpq.so.5; \
	apk del .pgsql-deps
###< doctrine/doctrine-bundle ###
###< recipes ###

, then of course build images again and it works.
I hope this will solve your error :)

**Comment by freiondrej-lmc** [comment]
@michael-schaefer-eu Oh great! Now it makes perfect sense and it indeed solved the problem for me. Thank you very much :)
Do you think I should rephrase this issue (or maybe close it and create a followup one) narrowing the error to the ORM pack not modifying the Dockerfile? Is this rather a orm-pack issue rather than symfony-docker one? 🤔

**Comment by michael-schaefer-eu** [comment]
@freiondrej-lmc If your problem is solved then you can close this issue, I guess.

I think the real problem is a `flex recipes` issue that is described [here](https://github.com/dunglas/symfony-docker/issues/192#issuecomment-1075269831)

So as I understand it, it's the flex recipes that do something wrong, because of some updates ...

Basically what needs to be done now to create a webapp is to call `composer require webapp` ; which the current Dockerfile does not do.

**Comment by freiondrej-lmc** [comment]
@michael-schaefer-eu Thank you for linking this issue in https://github.com/dunglas/symfony-docker/issues/192#issuecomment-1077481772. Do you think that's sufficient, or should I file a new issue for 
> the Dockerfile is not updated with sql drivers

? And is it a symfony-docker issue, or rather a flex one? (I'm asking in order to choose the right repo to create the issue in)

**Comment by michael-schaefer-eu** [comment]
@freiondrej-lmc in my opinion it doesn't need another issue for that, I think when #192 is solved, then it will automatically fix the Dockerfile issue as well.

As I understand it, it's an issue with this repo, specifically line 92 in [Dockerfile](https://github.com/dunglas/symfony-docker/blob/33deaeb484afceb32efb63aa63fe701edb15bff2/Dockerfile#L92)

So for example, when you execute

```
SKELETON=symfony/website-skeleton docker-compose up --build
```

then the Dockerfile will do this in the build step:

```
RUN composer create-project "symfony/website-skeleton" . --stability=stable --prefer-dist --no-dev --no-progress --no-interaction; \
    composer clear-cache
```

which is outdated, see [docs for 5.4](https://symfony.com/doc/5.4/setup.html#creating-symfony-applications)) :

> The `webapp` option installs all the packages that you usually need to build web applications, so the installation size will be bigger.

So instead the Dockerfile should do somethink like this (_pseudocode_) :
```
RUN composer create-project symfony/skeleton [...]
  if SKELETON == "symfony/website-skeleton" then
    composer require webapp
```

**Comment by freiondrej-lmc** [comment]
@michael-schaefer-eu thank you so much for taking the time in the investigation and opening https://github.com/dunglas/symfony-docker/issues/233. I'm now closing mine as your issue specifies much better what needs to be fixed.
