### ISSUE TITLE
having issue with existing project

### ISSUE THREAD

**Issue by On5-Repos** [dunglas/symfony-docker#232]
executor failed running [/bin/sh -c set -eux; 	mkdir -p var/cache var/log; 	composer install --prefer-dist --no-dev --no-progress --no-scripts --no-interaction; 	composer dump-autoload --classmap-authoritative --no-dev; 	composer symfony:dump-env prod; 	composer run-script --no-dev post-install-cmd; 	chmod +x bin/console; sync]: exit code: 1
ERROR: Service 'php' failed to build : Build failed

**Comment by nicolashohm** [comment]
I had the same issue. It might be a configuration issue (at least for me it was). 

In case you encounter this error, you can run the build step with a more verbose output using this command: `docker-compose build --pull --no-cache --progress=plain`
