### ISSUE TITLE
Fix Dockerfile creating symfony applications

### ISSUE THREAD

**Issue by michael-schaefer-eu** [dunglas/symfony-docker#233]
The current Dockerfile creates a broken Symfony application for the website skeleton.

### Problem

The current Dockerfile has an [outdated command](https://github.com/dunglas/symfony-docker/blob/33deaeb484afceb32efb63aa63fe701edb15bff2/Dockerfile#L92) to create a website / webapp skeleton application. The result will be broken `docker-compose` and `Dockerfile` files with missing services and drivers, as described in #192 in #231.

From the docs for [Symfony 5.2](https://symfony.com/doc/4.4/setup.html#creating-symfony-applications) (and all prior versions):

```
# run this if you are building a traditional web application
$ composer create-project symfony/website-skeleton:"5.2.*" my_project_name

# run this if you are building a microservice, ...
$ composer create-project symfony/skeleton:"5.2.*" my_project_name
```

From the docs for [Symfony 5.3](https://symfony.com/doc/4.4/setup.html#creating-symfony-applications) (and all later versions):

```
# run this if you are building a traditional web application
$ composer create-project symfony/skeleton:"^5.3" my_project_directory
$ cd my_project_directory
$ composer require webapp

# run this if you are building a microservice, ...
$ composer create-project symfony/skeleton:"^5.3" my_project_directory
```

### Possible Solution

Update the Dockerfile with:

```
ARG SKELETON=""
ENV SKELETON ${SKELETON}

RUN if [ "$SKELETON" = "webapp" ] ; \
  then \
    composer create-project symfony/skeleton:"${SYMFONY_VERSION}" . --stability=$STABILITY --prefer-dist --no-dev --no-progress --no-interaction; \
    composer require webapp; \
    composer clear-cache; \
  else \
    composer create-project symfony/skeleton:"${SYMFONY_VERSION}" . --stability=$STABILITY --prefer-dist --no-dev --no-progress --no-interaction; \
    composer clear-cache; \
  fi
```

### Open questions

(need to test): How will version 4.4 behave (as it is [supported](https://symfony.com/releases) until 11/2023) ?

**Comment by michael-schaefer-eu** [comment]
### Lesson learned

The `Dockerfile` is not the only place where this must be fixed. It is the `docker/php/docker-entrypoint.sh` which executes the 

```
composer create-project ... 
``` 

a second time, because with `docker-compose -up` the complete directory is mounted into the container, overwriting all files that were created during the build step :exploding_head: 

Unfortunately updating `docker-entrypoint.sh` leads to some new issue and does not create a `php` container. Needs more investigation ...

**Comment by maxhelias** [comment]
Let's continue the discussion on the first reported ticket
