### ISSUE TITLE
extremely slow shell after `make sh` in M1

### ISSUE THREAD

**Issue by alejgarciarodriguez** [dunglas/symfony-docker#235]
Commands inside the container takes way too long in M1 macbook. Did the same in my intel+ubuntu PC desktop and everything worked as expected.

- make composer and make sf run super fast.
- After installing symfony profiler, localhost:80 shows ~25ms response time

Everything seems to work just fine except executing any command after typing `make sh`, inside the container.
E.g. `echo 'hello'` takes forerever.

If docker images are not compatible with M1 (probably thats the reason), why `make composer` and `make sf` work fine?

**Comment by dunglas** [comment]
I use these images on a M1 everyday without any issue. Could you show the content of your Makefile?

**Comment by alejgarciarodriguez** [comment]
I upgraded docker desktop and rebuilds all the images and now is working! No idea what it was tbh

Thanks @dunglas!
