### ISSUE TITLE
apcu and opcache prevent local development

### ISSUE THREAD

**Issue by freiondrej-lmc** [dunglas/symfony-docker#240]
Hello,
I'm using symfony-docker to simplify my local development (great job, it's amazing!).

I mounted the work dir into the php container as a volume `- .:/srv/app`, but the changes I did to my local files did not take effect when running php. I tried adding `opcache_reset()` and `apcu_clear_cache()` to public/index.php, but it did not help. Then I tried disabling opcache and apcu by commenting out the Dockerfile part with `docker-php-ext-enable apcu opcache;` and it indeed solved the problem. However doing it like this felt a bit cumbersome and made me think I'm probably doing something wrong, but I did not find anything about this in the README nor the docs/. Is there a way to do this? 

Thank you! 🙂

_Originally posted by @freiondrej-lmc in https://github.com/dunglas/symfony-docker/discussions/237_

**Comment by stefanpoensgen** [comment]
Try to remove the following lines from dev php ini (https://github.com/dunglas/symfony-docker/blob/main/docker/php/conf.d/symfony.dev.ini)
```
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.memory_consumption = 256
realpath_cache_size = 4096K
realpath_cache_ttl = 600
```

I don't know exactly which one is enough to remove, but maybe we don't need it anyway on local development.

**Comment by maxhelias** [comment]
Close in favor https://github.com/dunglas/symfony-docker/issues/245
