### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by tech0tron** [dunglas/symfony-docker#246]
This is a link to my full repository: https://github.com/tech0tron/civstock-symfony

When I run docker-compose build --pull --no-cache it gives this error on Step 36:

```
+ composer run-script post-install-cmd

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Error: Class "Symfony\Bundle\TwigBundle\TwigBundle" not found in /srv/app/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:131
!!  Stack trace:
!!  #0 /srv/app/vendor/symfony/http-kernel/Kernel.php(382): App\Kernel->registerBundles()
!!  #1 /srv/app/vendor/symfony/http-kernel/Kernel.php(766): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /srv/app/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
!!  #3 /srv/app/vendor/symfony/framework-bundle/Console/Application.php(166): Symfony\Component\HttpKernel\Kernel->boot()
!!  #4 /srv/app/vendor/symfony/framework-bundle/Console/Application.php(72): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #5 /srv/app/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
!!  #6 /srv/app/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(54): Symfony\Component\Console\Application->run()
!!  #7 /srv/app/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run()
!!  #8 /srv/app/bin/console(11): require_once('...')
!!  #9 {main}
!!    thrown in /srv/app/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php on line 131
!!  
Script @auto-scripts was called via post-install-cmd
The command '/bin/sh -c set -eux; 	mkdir -p var/cache var/log; 	composer install --prefer-dist --no-dev --no-progress --no-scripts --no-interaction; 	composer dump-autoload --classmap-authoritative --no-dev; 	composer symfony:dump-env prod; 	composer run-script post-install-cmd; 	chmod +x bin/console; sync' returned a non-zero code: 255
ERROR: Service 'php' failed to build : Build failed
```

**Comment by dunglas** [comment]
This doesn't look related to this repository. TwigBundle is missing in your `composer.lock` file.

**Comment by dunglas** [comment]
OPCache is enabled in CLI mode? That should probably not be the case.

**Comment by webdevilopers** [comment]
I'm not sure what you mean but it is not enabled on my local machine.

I tried to get it running yesterday by changing the workdir to e.g. "srv2/app". It was successfully changed but still some _composer.lock_ was found though it did not exist locally.
Then I deleted all kinds of files (_composer.json_ etc.) and directories (_var_, _vendor_). And I removed all docker images, volumes and containers.

Still - building everything cleaned up from scratch - some cached composer files were used.

In the end I deleted the project, moved it to a different local directory und started from scratch and it worked fine.

I really can't tell what was going on. Unfortunately I'm new to Docker. I will post if I found anything on the road!

Thanks so far for this great library!

**Comment by webdevilopers** [comment]
I can now recreate the behaviour that seems to cause the issues.

When I start the project manually in my terminal changes are recognized.

```
docker-compose up --build -d
```

Then env vars look like this:
![docker_env_ok](https://user-images.githubusercontent.com/3479626/182028615-9e67290b-0246-428e-b83a-3b057051ec3e.png)

When using the IDE (PHPStorm) by clicking the arrows for the services...
![ide_docker_compose](https://user-images.githubusercontent.com/3479626/182028657-7231bbd8-1731-40df-90c9-58d407ac41f8.png)

...which creates the following command...

```
/usr/bin/docker-compose -f /var/www/stadt-emden-funding/docker-compose.yml up -d
```

...then changes are no longer recognized. The env vars differ by one entry:
![docker_env_nok](https://user-images.githubusercontent.com/3479626/182028675-ad18eb89-90c5-427a-b3cd-cac1f1785cad.png)

It looks like it is missing the **APP_ENV=dev** entry. And I guess that is activating OPCache in the production settings.

Any idea why PHPStorm is missing it?

**Comment by dunglas** [comment]
The problem is that PHPStorm doesn't automatically loads the `docker-compose.override.yaml` file, while `docker-compose` (the CLI tool) automatically does if no explicit `-f` option is passed (the default).

This file overrides the `APP_ENV` environment variable to enable the dev mode of Symfony (which watches for file changes).

This looks like a PHPStorm bug to me.

**Comment by dunglas** [comment]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/57224/182046356-eaa27632-fed5-4da7-8fd6-57472afd9188.png">

**Comment by webdevilopers** [comment]
Also my original issue disappeared too. I no longer have to disable OPCache in dev.

**Comment by maxhelias** [comment]
With the rework the `APP_ENV` should always be defined and the dev mode of Symfony fix the original issue
