### ISSUE TITLE
ERROR: Invalid interpolation format for "build" option in service "php": "${SYMFONY_VERSION:-}"

### ISSUE THREAD

**Issue by sruj** [dunglas/symfony-docker#247]
Hi, I'm trying to use symfony docker and I'm stuck on step 2 from read.me . Command `docker-compose build --pull --no-cache` throw
`ERROR: Invalid interpolation format for "build" option in service "php": "${SYMFONY_VERSION:-}"` and google is silent for it.

I'm also fresh with Docker...

**Comment by maxhelias** [comment]
At first sight, I would have said the version of docker-compose but it doesn't look like it.
I will need more info on your environment to help you

**Comment by tutolmin** [comment]
I had the same error with an older version of docker-compose script
#ls -al /usr/bin/docker-compose
-rwxr-xr-x 1 root root 419 фев 22  2018 /usr/bin/docker-compose
#docker-compose -v
docker-compose version 1.17.1, build unknown

After reinstalling it worked like a charm:
#curl -SL https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
#chmod +x /usr/local/bin/docker-compose
#mv /usr/bin/docker-compose{,.old}
#ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
#docker-compose -v
Docker Compose version v2.6.0

**Comment by maxhelias** [comment]
In fact, it is the Docker engine that must be 17.09.0+

**Comment by sruj** [comment]
I have Docker version 20.10.18, build b40c2f6

**Comment by sruj** [comment]
Sorry, I'm new with Docker, I did't download locally Your project https://github.com/dunglas/symfony-docker
