### ISSUE TITLE
Symfony generates URLs with http://domain:443

### ISSUE THREAD

**Issue by 0x346e3730** [dunglas/symfony-docker#251]
I'm not sure what made this but since a few days when building for production, some URLs are generated as http://domain:443 instead of https://domain
I'm not sure how to debug this either, help greatly appreciated :)

**Comment by LoicBoursin** [comment]
I had the same issue with Traefik in front of Caddy, and the proposed answer fixed it. Thanks!

**Comment by maxhelias** [comment]
PR open #367

**Comment by fractalzombie** [comment]
> I went crazy for over 48 hours but since Caddy 2.5, if you have a Reverse Proxy (such as Traefik for example) in front of Caddy you need to change your Caddyfile from
> 
> ```
> php_fastcgi unix//var/run/php/php-fpm.sock
> ```
> 
> to
> 
> ```
> php_fastcgi unix//var/run/php/php-fpm.sock {
>     trusted_proxies private_ranges
> }
> ```
> 
> Don't know if it would add value to at least note this somewhere in the doc.

Thank you very much! It saves me 3 days of debugging on side symfony, on side traefik, and it was caddy...
