### ISSUE TITLE
Use Symfony CLI With PHP Binaries

### ISSUE THREAD

**Issue by TheDevick** [dunglas/symfony-docker#260]
So, i have installed a new ***WSL*** (***Ubuntu***) and, I created the containers.

Now, i have to run the ***Symfony CLI***, but it show an error: `no PHP binaries detected`

My question is: How to run ***Symfony CLI*** using the ***PHP Container***?
![image](https://user-images.githubusercontent.com/71853418/178088904-e46704cd-5774-4247-8bd0-739315ee2c20.png)

![image](https://user-images.githubusercontent.com/71853418/178088872-87822ec8-cfed-4db0-89c1-68593abfd40b.png)

**Comment by maxhelias** [comment]
Where did you install your binary ? In the WSL or in a container ?

**Comment by TheDevick** [comment]
On the Container. So i can use the PHP Binaries of Container (My WSL Not Have the PHP Installed, Because i want to use the Docker Binaries)

**Comment by maxhelias** [comment]
It looks like, on your screen, you are trying the command on your WSL and not in the container

**Comment by TheDevick** [comment]
Yes... Do you have any tips to create a `alias` for the symfony command run on docker?

Actually, i created the alias for the `php`, and the php commands are working fine, but how can i run Symfony here?

```
alias php='docker exec -it blogapi_php_1 php'
```

**Comment by stefanpoensgen** [comment]
i would recommend to take a look at https://github.com/dunglas/symfony-docker/blob/main/docs/makefile.md
everthing you need and easy to extend
