### ISSUE TITLE
It's possible to use many domains with Caddy?

### ISSUE THREAD

**Issue by Forticas** [dunglas/symfony-docker#273]
There is a way to deploy the project with many domains (sub-domains) ?

like : 

```bash
SERVER_NAME=fr.example.com, en.example.com \
APP_SECRET=ChangeMe \
CADDY_MERCURE_JWT_SECRET=ChangeMe \
docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
```

**Comment by maxhelias** [comment]
I never try, I think that should work see more detail here : https://caddy.community/t/multiple-domains/1761

**Comment by Forticas** [comment]
> I never try, I think that should work see more detail here : https://caddy.community/t/multiple-domains/1761

I'm sure that's possible but I'm asking if it can be done with the current project configuration And how

**Comment by dunglas** [comment]
This should work:

`SERVER_NAME='domain1.com, domain2.com' docker compose up -f docker-compose.yaml -f docker-compose.prod.yaml -d`
