### ISSUE TITLE
Missing files: composer.* symfony.* Line 98

### ISSUE THREAD

**Issue by nordin74** [dunglas/symfony-docker#279]
During the building process the files composer.* symfony.* are missing.

**Comment by dunglas** [comment]
This shouldn't be an issue because we use a pattern (and because our CI is green).

Please check that you aren't running an outdated version of Docker or Docker Compose.

**Comment by necobm** [comment]
Same Issue:

`Step 27/38 : COPY composer.* symfony.* ./`

running docker-compose version 1.25.0, build unknown

If there are a minimum Docker Compose version requirement for the project to work, I think it should be specified in the README file. I've installed without issues symfony-docker about two months ago, using same version of Docker Compose

**Comment by dunglas** [comment]
Can you try with Docker Compose v2 please? We upgraded the setup this week.

**Comment by necobm** [comment]
It worked with Docker Compose version v2.6.0, but I suggest to alert about this change in README file or by some another way, because this issue will be arise to another users that are using docker compose v1.x

**Comment by dunglas** [comment]
Indeed. I wonder if we cannot find a way to conditionally add these files that is compatible with both versions of Compose.

**Comment by nordin74** [comment]
We need to know during the building process the version at least of docker-engine. I was able to find these predefined variables only: https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope,  but they don't work for our case.
Maybe the best option is to stick to version 2 of docker-compose and add an environment variable to change the logic of building in case of use of version 1

**Comment by necobm** [comment]
Or maybe, don't support docker compose v1 aymore, existing projects won't break unless they update Dockerfile or dockercompose.yaml file. In the changelog of this project maybe will be a good idea warn of this change and in the section "Getting Started" of README also indicate that. Although the fact that the command `docker compose build --pull --no-cache`
is not "docker-compose" but "docker compose" without the joining character "-" is telling us that it's version 2 allready.

**Comment by filisko** [comment]
Tried with version  Docker Compose version v2.3.3 and didn't work. Updated to v2.11.2 and it worked

**Comment by TacoV** [comment]
Simple work-around if you don't want to upgrade Docker Compose (eg when you're stuck on the packager maintained version of V2): create the two files to find during build, delete them afterwards when the actual files are created.
So first `touch composer.tmp symfony.tmp`
Then run the server, let it install, and `rm composer.tmp symfony.tmp`

**Comment by maxhelias** [comment]
We have added a note to recommend the 2.10+ version
