### ISSUE TITLE
[Question] Volumes explanation

### ISSUE THREAD

**Issue by borNfreee** [dunglas/symfony-docker#28]
Could you please explain what is the trick of configured volumes inside `/src/app/var/` dir?

https://github.com/dunglas/symfony-docker/blob/49a016af2cc497b51ec0201b4b6b1311a8c5f809/docker-compose.yaml#L10-L17

Why volumes, defined on lines `14-17`, give any performance boost on Docker for Mac?

Probably, it would be nice to add the explanation to README then (or to Dockerfile).

Thank you.

**Comment by dunglas** [comment]
Because FS on Mac is slow, and the less you share between the host and the container, faster it is. There is no such problem on Linux.

**Comment by borNfreee** [comment]
Thank you.

Answer from the docker captain for the same question: https://twitter.com/BretFisher/status/1015042309338083331

> volumes are always in the "moby" Linux VM on mac/win. They are fast, but aren't easily accessible when you need to edit files in them. That's what bind-mounts are for, but bind-mounts are much slower since they are shares between two OS's
