### ISSUE TITLE
docker compose up error

### ISSUE THREAD

**Issue by Dementor828** [dunglas/symfony-docker#280]
HI)

After running docker compose up got this error

Attaching to www-root-caddy-1, www-root-php-1
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/www/way-to-project/www-root/docker/php/conf.d/app.dev.ini" to rootfs at "/usr/local/etc/php/conf.d/app.dev.ini": mount /var/www/way-to-project/www-root/docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini (via /proc/self/fd/14), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by maxhelias** [comment]
> Check if the specified host path exists and is the expected type

It seems that you have a problem with the project path `/var/www/way-to-project/www-root/docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini`

**Comment by sci3ma** [comment]
I had the same error on Ubuntu with fresh files, no any docker images in host, path to file was valid.
In my case, Docker Desktop was the cause. Closing Docker Desktop app solved it.
