### ISSUE TITLE
SSL Cert Caddy

### ISSUE THREAD

**Issue by WebPirat** [dunglas/symfony-docker#281]
Hi,

i cant figure out how to make ssl function localy i have a fresh ubuntu installation and fresh symfony docker but my browser doesnt trust the cert provided from caddy is there a way to easy fix this (troubleshoooting adivce doesnt work i dont have a root.crt)

Thanks and best regards

**Comment by maxhelias** [comment]
Hi

See the caddy log to see if the `root.crt` file is created with the same path as the troubleshooting : `{"level":"warn","ts":1663320565.8757846,"logger":"pki.ca.local","msg":"installing root certificate (you might be prompted for password)","path":"storage:pki/authorities/local/root.crt"}`

Maybe the Linux command need to be updated to approve the certificates

**Comment by mbadolato** [comment]
Similar. I have in my logs: 

```json
{"level":"warn","ts":1666306201.874214,"logger":"pki.ca.local","msg":"installing root certificate (you might be prompted for password)","path":"storage:pki/authorities/local/root.crt"}
{"level":"info","ts":1666306201.8744159,"msg":"Warning: \"certutil\" is not available, install \"certutil\" with \"apt install libnss3-tools\" or \"yum install nss-tools\" and try again"
```

**Comment by maxhelias** [comment]
@mbadolato What is similar ? According to your log you have the certificate, so the command on the [TLS section](https://github.com/dunglas/symfony-docker/blob/main/docs/tls.md) should work correctly.

@WebPirat Having no feedback from you, this should probably not be a problem anymore, so I close the issue
