### ISSUE TITLE
.env.local in dockerignore prevent to run symfony:dump-env prod correctly 

### ISSUE THREAD

**Issue by glasset** [dunglas/symfony-docker#284]
What’s the purpose of adding .env.local to the dockerignore ? 
that prevent it to copy this file and lead to don't have the right variable set when `composer symfony:dump-env prod;` is run

this image is not intended to be run in production mode ?

links: 
https://github.com/dunglas/symfony-docker/blob/main/.dockerignore#L28
https://github.com/dunglas/symfony-docker/blob/main/Dockerfile#L110
https://symfony.com/doc/current/configuration.html#configuring-environment-variables-in-production

**Comment by dunglas** [comment]
In prod with Docker, you should use Docker to set real environment variable instead of using the `.env.*` files.
