### ISSUE TITLE
Enable to start

### ISSUE THREAD

**Issue by laminr** [dunglas/symfony-docker#29]
Hello,
I am a beginner in Docker, so...
I am trying to do the `docker-composer up` but go error

```
[Symfony\Component\Console\Exception\RuntimeException]
  The "--stability" option requires a value.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

ERROR: Service 'app' failed to build: The command '/bin/sh -c composer create-project "symfony/skeleton ${SYMFONY_VERSION}" . --stability=$STABILITY --prefer-dist --no-dev --no-progress --no-scripts --no-plugins --no-interaction' returned a non-zero code: 1
```

stability is set to `stable` in the Docker file, so don't understand...
Please help

**Comment by maxhelias** [comment]
For the build of this docker, you must you choose the stability that you need like this : 
```
STABILITY=dev docker-compose up
``` 
Or : 
```
STABILITY=stable docker-compose up
```

Note: You should use it with the `-d` option to detach the terminal

**Comment by laminr** [comment]
Great it works (obviously) !
Not the subject, but how can you handle the data directly in DB (phpMyAdmin or PhpStorm direct connection) ?

**Comment by maxhelias** [comment]
To start, you need to add a data service in your docker-compose.yaml

**Comment by laminr** [comment]
Ah yes sorry, testing all I find to try to understand, I didn't that this one doesn't include it ;-)
Thx
