### ISSUE TITLE
Caddy 2.6 removed experimental_http3 option

### ISSUE THREAD

**Issue by akhimi** [dunglas/symfony-docker#290]
there is an error on Caddy started

> Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /etc/caddy/Caddyfile:7 - Error during parsing: unrecognized protocol option 'experimental_http3'

Caddy recently removed the experimental_http3 option

https://github.com/caddyserver/caddy/releases

**Comment by bkosun** [comment]
Related: #291
