### ISSUE TITLE
Is this symfony-docker comes with php?

### ISSUE THREAD

**Issue by sruj** [dunglas/symfony-docker#292]
I'm here from Symfony doc https://symfony.com/doc/current/setup/docker.html#complete-docker-environment
![image](https://user-images.githubusercontent.com/10078146/191965945-daae5d85-07ea-4dea-a14b-db912dc486da.png)
where it stands taht this docker comes with php, but when I try to run composer it says I have php 7.4 (with is true, that is the version that i have locally)
![image](https://user-images.githubusercontent.com/10078146/191966176-08e8449f-bea4-4d16-be5c-f81de4ace643.png)

**Comment by maxhelias** [comment]
You must go into your php container to execute your commands. That's what makes docker so useful.

```
docker compose exec {your service name} sh
```

You find your service name here : https://github.com/dunglas/symfony-docker/blob/7cc9d7b93ba8764a21ef23683a59453e6d2b27b6/docker-compose.yml#L4
