### ISSUE TITLE
How to install node.js using Dockerfile

### ISSUE THREAD

**Issue by sruj** [dunglas/symfony-docker#293]
Hi,
I'm new with Docker, and I have successfully using your symfony-docker. But i'm trying to install nodejs, so I follow these instruction  https://stackoverflow.com/questions/36399848/install-node-in-dockerfile/67491580#67491580 and wan't to install it using Dockerfile. So I added these lines: 
![image](https://user-images.githubusercontent.com/10078146/193258477-48031340-f1a3-4afe-a70f-db5fce6c1b3a.png)
and after building docker: 
`docker build . --progress=plain`
and doing up command:
`docker compose up`
and enter php service:
`docker compose exec php sh`
command node --version throws: node: not found

**Comment by maxhelias** [comment]
See how multi-stage works: : https://docs.docker.com/build/building/multi-stage/#use-multi-stage-builds

We have a try to add it to this project : https://github.com/dunglas/symfony-docker/pull/186/files but not finished and and discussion about it : https://github.com/dunglas/symfony-docker/issues/129

**Comment by sruj** [comment]
Thanks for reply. Sorry, I know that it's not stackoworflow, but I just want to use Your symfony-docker for local small project just to learn Symfony. Could you just tell whats wrong with my Dockerfile, should I use `WORKDIR /srv/app` like that?
![image](https://user-images.githubusercontent.com/10078146/193511453-18f3a1a0-8921-4123-85cf-ae52af9253f7.png)

**Comment by maxhelias** [comment]
An advice, don't add to many tools to learn at the same time.

Here it is not the workdir which is the problem but the multi-stage which is badly implemented.
Read the link I posted from the docker documentation which explains it very well.

> How does it work? The second FROM instruction starts a new build stage with the alpine:latest image as its base. The COPY --from=0 line copies just the built artifact from the previous stage into this new stage. The Go SDK and any intermediate artifacts are left behind, and not saved in the final image.
