### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by sebnouet** [dunglas/symfony-docker#297]
Could it be possible to chose whether PostgreSql or Mysql to install ?

**Comment by maxhelias** [comment]
Yep, this project does not provide a database service.

Otherwise, you can use the maker-bundle with the command make:docker:database to generate a database service where you can choose between MySQL / MariaDB / Postgres : https://github.com/symfony/maker-bundle/pull/640

**Comment by sebnouet** [comment]
Thanks for your answer.

The problem is that when I will require Symfony/orm-pack, it will
automatically create a PostgreSql service, which is unecessary when using
mysql. Isn't it ?

Le mar. 4 oct. 2022 à 09:49, Maxime Helias ***@***.***> a
écrit :

**Comment by maxhelias** [comment]
Yes, nothing prevents you to remove the add-on.
You can also disable docker support via Flex with the option in `composer.json` > `extra.symfony.docker: false`

**Comment by treztreiz** [comment]
> 

This is because you answer "yes" when symfony flex asks you to automatically generate the recipe. You should answer "no", then use the command `make:docker:database` in order to choose mysql or mariadb.
