### ISSUE TITLE
Wkhtmltopdf not working correctly with alpine

### ISSUE THREAD

**Issue by zairigimad** [dunglas/symfony-docker#301]
Hello, while trying to install wkhtmltopdf with the following code 
```
RUN apk add --no-cache wkhtmltopdf xvfb ttf-dejavu ttf-droid ttf-freefont ttf-liberation
RUN ln -s /usr/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf
RUN chmod +x /usr/local/bin/wkhtmltopdf
```

wkhtmltopdf not found in the alpine linux, when forcing alpine3.14 it does exist but it comes with wkhtmltopdf 0.12.6 wich is not working correctly with KnpSnappyBundle. 

any idea how to install it correctly to have 0.12.5 version ? 

thanks

**Comment by mario-fehr** [comment]
@zairigimad in our own docker images we do some magic like this

````docker
COPY --from=madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10 /bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf
COPY --from=madnight/alpine-wkhtmltopdf-builder:0.12.5-alpine3.10 /bin/wkhtmltoimage /usr/local/bin/wkhtmltoimage
````

but never tried if this works with symfony-docker
