### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Stef-Gijsberts** [dunglas/symfony-docker#309]
Hi, may I use this code for a project, and if so, under what conditions?

I could not find any license file or existing GitHub issue about this.

**Comment by maxhelias** [comment]
This project is completely open source. There is no LICENSE at the root as it is defined as template.

**Comment by dunglas** [comment]
Indeed we can't put a LICENSE file in the repository as stated by @maxhelias but it's MIT licensed (most of the code/config comes from API Platform and Symfony, which are also MIT licensed).

**Comment by dunglas** [comment]
We could add the license in the `README.md` file @maxhelias?

**Comment by maxhelias** [comment]
> We could add the license in the `README.md` file @maxhelias?

Yes we can do that :+1:
