### ISSUE TITLE
install-php-extensions  Could not resolve host

### ISSUE THREAD

**Issue by cmedi32** [dunglas/symfony-docker#313]
I am getting this interesting error, when trying to install extensions via the install-php-extenstions installer. Not sure where this issue is originating from, I have even cloned a clean symfony-docker project and this happened. Any reasons or fixes around? It happened out of nowhere some evening.

 => ERROR [symfonydockertest-php app_php  6/21] RUN set -eux;     install-php-extensions      intl      zip      apcu   opcache     ;                                                                      10.5s
------
 > [symfonydockertest-php app_php  6/21] RUN set -eux;     install-php-extensions       intl            zip             apcu            opcache     ;:
#0 0.534 + install-php-extensions intl zip apcu opcache
#0 0.537 install-php-extensions v.1.5.43
#0 0.537 #StandWithUkraine
#0 8.851 curl: (6) Could not resolve host: objects.githubusercontent.com
------
failed to solve: executor failed running [/bin/sh -c set -eux;     install-php-extensions       intl            zip             apcu            opcache     ;]: exit code: 6

**Comment by lermontex** [comment]
#302

**Comment by louia** [comment]
Style an issue

**Comment by cmedi32** [comment]
Yes, I have the Symfony 6.1, so it requires PHP > 8.1 and just changing the installer image may work but the containers won't run, for now I just removed that extensions installer and installed them manually via apk etc.

No idea where this issue is originating from, but it probably has something to do with the docker network configuration, I am not really an expert on this stuff, so I will just keep looking and update if I find anything. It's just for local development environment anyway.

is this installer image cached anywhere?

**Comment by cmedi32** [comment]
Alright, I fixed it by using a buster Debian based image.

`FROM php:${PHP_VERSION}-fpm-buster AS app_php`

then I installed the runtime deps via apt

`RUN apt update`

`RUN apt-get install -y \
		acl \
		fcgiwrap \
		file \
		gettext \
		git \
	;`


No idea if this is optimal, I don't know much around docker. But for me, it does the fix for the local development environment.
