### ISSUE TITLE
Simpler recipe

### ISSUE THREAD

**Issue by myselfhimself** [dunglas/symfony-docker#314]
Hello,

it would be nice to a have simpler recipe with:
- no caddy compilation, but use of an image instead (much faster run)
- no mercure/vulcain
- choice between mysql / postgresql
- adminer

This could be generated with a wizard shell script..

I can share docker-compose.yml Dockerfile and Caddyfile files if you want for the above setup with mysql if you want ... or postgresql (other project too).

**Comment by maxhelias** [comment]
Hello,

- It's already the case see : https://github.com/dunglas/symfony-docker/blob/4c590cd1484d810b567370ee5fd833643b3ebf53/Dockerfile#L122 or I don't know what you mean ? 
- Mercure and vulcain were created by Kevin, as was this project. So it's a choice.
- There is no database service provided with this project. Postgres can be provided with symfony recipes by default (https://github.com/dunglas/symfony-docker/blob/main/docs/extra-services.md), or the choice between MySQL, MariaDB or Postgres can be done with the "make:docker:database" command of the maker bundle (https://github.com/symfony/maker-bundle/blob/main/src/Maker/MakeDockerDatabase.php).
- And adminer is not necessary.

As a reminder, the main objective of this project is to provide the minimum necessary to launch a Symfony project and keep it production ready.

**Comment by qualeo** [comment]
@myselfhimself - See the [Caddy Image](https://hub.docker.com/_/caddy) on Docker Hub.

**Comment by myselfhimself** [comment]
Hello,

the issue with the existing Dockerfile is it takes long for xcaddy to buid with mercure and vulcain. This is not funny to use in a CI where tests run after building all images in a blank new environment.... So they take ever because of caddy extra compilation steps especially, while just pulling docker hub images with optional cache (in my case Github CI has a mutualized cache) would speed that up a lot. I even disabled building XDEBUG with a new Dockerfile ARG for the CI toolchain.

Adminer is indeed not needed for a public skeleton, sorry for mentioning it.

Thank you for posting about the extra-services documentation page, I had missed it completely and since I did not know Symfony Flex, I have wasted some time setting up a database and mailcatcher by hand.

If had not found a simple-enough LAMP-style Docker recipe with Caddy (or default SSL) for Symfony. This is what I wanted to raise here.

Thank you for having replied with solutions.

**Comment by maxhelias** [comment]
Our CI is adapted for our use case, ensuring that the project can be built.
For a Symfony application where the Docker configuration doesn't move, you should consider using a registry to optimize your build time.
More information here : 
- https://docs.docker.com/ci-cd/best-practices/
- https://docs.docker.com/ci-cd/github-actions/#optimizing-the-workflow
- https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
- https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions

**Comment by myselfhimself** [comment]
Thank you very much for commenting with links, which I have read in depth

**Comment by myselfhimself** [comment]
The use of custom Docker hubs for the symfony-docker project is not so obvious because of the docker-compose context with a single Dockerfile used for two services (caddy + php) (not just a single Dockerfile project)..
Related literature: https://stackoverflow.com/questions/53416685/docker-compose-tagging-and-pushing and https://stackoverflow.com/questions/67302866/github-actions-and-docker-compose-push-to-ghcr-io . Do you have example Github Worfklow files for pushing / pulling symfony-docker images?
Right now, I have simplified the Dockerfile steps so that whole build step takes 3 minutes before unit tests are run. With some Github container registry magic this can time can shorten a lot... just, writing adequate Github workflow scripts is not straightforward.  I hope to dig into this in the next weeks :/

**Comment by maxhelias** [comment]
This is not specific to this project, it is common to all projects and languages.
See an example here : https://medium.com/@stoyanov.veseline/pushing-docker-images-to-a-private-registry-with-docker-compose-d2797097751
