### ISSUE TITLE
fresh install caddy container stuck in restarting state

### ISSUE THREAD

**Issue by guillaumesoul** [dunglas/symfony-docker#316]
Hello,

just downloaded tar source file.  At step docker compose up -d, all containers starting correctly excepts caddy-1 that keeps on restarting.

Ports 80, 443, and 5432 are all available on my computer.

I tried docker system prune but it didn't solve it.

Can't see where to find log to troubleshoot this.

Are there any configuration that must be done ?

Env : Mac Monterey, docker for mac

**Comment by maxhelias** [comment]
Hello,

Try `docker compose logs` to find the problem in the log.

**Comment by maxhelias** [comment]
No feedback
