### ISSUE TITLE
CI Wait for services job crashes but all jobs are working locally (nektos\act)

### ISSUE THREAD

**Issue by vinceAmstoutz** [dunglas/symfony-docker#317]
I have an error only for GitHub actions (currently working entirely when I run the pipeline locally with `nektos\act`) for the CI job "Wait for services".

The database is not reachable (only on the CI pipeline again) but I'm relying on the default configurations.

[Failed pipeline link](https://github.com/vinceAmstoutz/tests-and-quality-tools/actions/runs/3336397646/jobs/5521499365#step:5:1011)

Error message: `tests-and-quality-tools-php-1       | /usr/local/bin/docker-entrypoint: line 38: bin/console: Permission denied`.

OS: WSL 2 Ubuntu & Docker Desktop

Thanks for advance!

**Comment by maxhelias** [comment]
You're principal erreur is : `tests-and-quality-tools-php-1       | The database is not up or not reachable:` 

You should adapt your `DATABASE_URL` here : https://github.com/vinceAmstoutz/tests-and-quality-tools/blob/main/.env#L25 for having something like that : `DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=14&charset=utf8"` and that corresponds to your docker configuration here : https://github.com/vinceAmstoutz/tests-and-quality-tools/blob/main/docker-compose.yml#L58-L70

And if you still have the error `tests-and-quality-tools-php-1 | /usr/local/bin/docker-entrypoint: line 38: bin/console: Permission denied` check your console file if it has execution rights.

**Comment by vinceAmstoutz** [comment]
Thanks @maxhelias 

However I tried all afternoon and I didn't succeed despite several attempts (changing what you told me, doing a `chmod` on the .sh files and other things based on the docs and research but always the same result, except in local where everything builds as it should as you can see here : 

![image](https://user-images.githubusercontent.com/46444652/198323206-02836222-f500-445f-8355-2fef3b9b5d11.png)

[Last failed pipeline](https://github.com/vinceAmstoutz/tests-and-quality-tools/actions/runs/3338038658/jobs/5525168778#step:5:103)

Sorry for the inconvenience

**Comment by maxhelias** [comment]
Do you have a `.env.local` ?

**Comment by vinceAmstoutz** [comment]
Yes stupidly I had forgotten to delete it and that explained why it was working locally. Thanks! 
 So I deleted it and it didn't work at all (no DB, no local CI).  Wich was normal at this stage.
I was able to solve the problem locally and then stay with the local CI that works but GitHub Actions still failed, again...

(From this moment I have only one `DATABSE_URL `in a .env file).
I also tried to add [this ](docker/php/docker-entrypoint.sh) in the  `docker-entrypoint.sh` but it doesn't change anything.

Why DB still not reachable?  It's not a question of timing?

- [Last pipeline status](https://github.com/vinceAmstoutz/tests-and-quality-tools/actions/runs/3346333151/jobs/5543006974#step:5:143)
-[ Strange fail](https://github.com/vinceAmstoutz/tests-and-quality-tools/actions/runs/3346205438/jobs/5542717626#step:5:258)

Sorry again for that ...

**Comment by maxhelias** [comment]
I cloned your project to see and the files that are in the "/bin" folder have no execution rights : 
<img width="631" alt="Capture d’écran 2022-10-29 à 20 41 39" src="https://user-images.githubusercontent.com/12966574/198847769-2f02aa3f-0465-48ba-a593-24badcd2236b.png">

Execute `chmod +x bin/console` & `chmod +x bin/phpunit` should fix your CI. I have observed this before but could not identify why the execution rights disappear.

**Comment by vinceAmstoutz** [comment]
I do these 2 commands after enabling git file mode (`git config core.filemode true`) and it's good 🎉!
Many thanks for all your time and your help Maxime! 🙏 

Do you want me to make an addition in the [troubleshooting.md ](https://github.com/dunglas/symfony-docker/blob/main/docs/troubleshooting.md) or elsewhere, about this issue?

**Comment by maxhelias** [comment]
First, it should be identified when the execution rights change. Normally when creating the project, the rights of the files coming from the recipes / symfony flex and shouldn't change or they are misconfigured in the recipes.
