### ISSUE TITLE
Problem to access localhost

### ISSUE THREAD

**Issue by Mis0u** [dunglas/symfony-docker#318]
Hi guys, 

 Docker build and docker-compose up works but when I try to access to https://localhost, I've got a 404 !

I tried to execute what is in the [troubleshooting page](https://github.com/dunglas/symfony-docker/blob/main/docs/troubleshooting.md) :
For Mac : docker cp $(docker compose ps -q caddy):/data/caddy/pki/authorities/local/root.crt /tmp/root.crt && sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain /tmp/root.crt And I've got this error docker cp requires exactly 2 arguments

Any idea to access the localhost ?

**Comment by maxhelias** [comment]
This is normal if you have not created any routes in your application. Symfony response a 404 if no route is available.

**Comment by maxhelias** [comment]
Now you have a 502, what do the docker logs say?

**Comment by Mis0u** [comment]
@maxhelias I tried again this morning and the 404 is back,  this is my log :
`caddy_1  | {"level":"error","ts":1667295886.0592322,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"172.21.0.1","remote_port":"56724","proto":"HTTP/2.0","method":"GET","host":"localhost","uri":"/","headers":{"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Sec-Fetch-Site":["none"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-User":["?1"],"Accept-Language":["fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7"],"Sec-Ch-Ua-Platform":["\"macOS\""],"Upgrade-Insecure-Requests":["1"],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["document"],"Accept-Encoding":["gzip, deflate, br"],"Cache-Control":["max-age=0"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"107\", \"Chromium\";v=\"107\", \"Not=A?Brand\";v=\"24\""]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"localhost"}},"user_id":"","duration":0.0002336,"size":0,"status":404,"resp_headers":{"Alt-Svc":["h3=\":443\"; ma=2592000"],"Server":["Caddy"]}}`

**Comment by maxhelias** [comment]
The 404 log doesn't really help since it's a resource problem that is not available. Create a route for the "/" resource and that will solve your 404.

**Comment by Mis0u** [comment]
@maxhelias I edited my route but still the 404 :  
```php
<?php

declare(strict_types=1);

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdminController extends AbstractController
{
    #[Route('/', name: 'back')]
    public function hello(): Response
    {
        return new Response('hello');
    }
}
```

**Comment by Mis0u** [comment]
Problem is over, I just restart Docker...

**Comment by Mis0u** [comment]
@maxhelias 
I restart Docker and now I can access to the main page
<img width="1435" alt="Capture d’écran 2022-11-01 à 12 06 27" src="https://user-images.githubusercontent.com/50833583/199219931-816f6564-b67e-43aa-a941-20ef896a5fb6.png">
But my route '/' should return 'hello' but nothing is return

**Comment by maxhelias** [comment]
I don't know what to tell you, I don't have all the information and in each message you talk about a different problem related to your application.
Staying focused on one at a time will help but this is more a problem of your application than this project itself.
