### ISSUE TITLE
Where can we set the same user and group user?

### ISSUE THREAD

**Issue by roukmoute** [dunglas/symfony-docker#325]
Hi,

I would like to know where can is the settings to set the same user and group user of local user?
I don't find it and currently everything is installed in root, so it is not possible to edit files.

Thanks in advance!

**Comment by maxhelias** [comment]
Hello,
I think you want to do that : https://github.com/dunglas/symfony-docker/blob/main/docs/troubleshooting.md#editing-permissions-on-linux ?

**Comment by roukmoute** [comment]
It does not work correctly, I have two problems with this fix:

- It keeps `var` in `root` mode:

```sh
➤  ls -la
drwxr-xr-x  2 root      root       4096 nov.   4 18:55 var
```

- It continues to generates file in root mode:

```sh
➤  docker compose exec php sh
/srv/app # docker compose run --rm php chown -R $(id -u):$(id -g) .^C
/srv/app # composer require --dev symfony/maker-bundle
Using version ^1.47 for symfony/maker-bundle
./composer.json has been updated
Running composer update symfony/maker-bundle
Loading composer repositories with package information
Updating dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking doctrine/inflector (2.0.6)
  - Locking nikic/php-parser (v4.15.1)
  - Locking symfony/maker-bundle (v1.47.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Downloading nikic/php-parser (v4.15.1)
  - Downloading doctrine/inflector (2.0.6)
  - Downloading symfony/maker-bundle (v1.47.0)
  - Installing nikic/php-parser (v4.15.1): Extracting archive
  - Installing doctrine/inflector (2.0.6): Extracting archive
  - Installing symfony/maker-bundle (v1.47.0): Extracting archive
Generating optimized autoload files
28 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Symfony operations: 1 recipe (51594e88e38a104199802ff5644e5fa4)
  - Configuring symfony/maker-bundle (>=1.0): From github.com/symfony/recipes:main
Executing script cache:clear [OK]
Executing script assets:install public [OK]
              
 What's next? 
              

Some files have been created and/or updated to configure your new packages.
Please review, edit and commit them: these files are yours.

No security vulnerability advisories found
/srv/app # bin/console make:controller

 Choose a name for your controller class (e.g. GrumpyPopsicleController):
 > EventController

 created: src/Controller/EventController.php

           
  Success! 
           

 Next: Open your new controller class and add some pages!
/srv/app # 
╭─ ~/workspace/github/symfony-docker ‹main› 
╰─➤  ls -la src/Controller               
total 12
drwxr-xr-x 2 roukmoute roukmoute 4096 nov.   4 18:58 .
drwxr-xr-x 3 roukmoute roukmoute 4096 nov.   4 18:56 ..
-rw-rw-rw- 1 root      root       510 nov.   4 18:58 EventController.php
-rw-r--r-- 1 roukmoute roukmoute    0 nov.   4 18:56 .gitignore
```

**Comment by maxhelias** [comment]
Try the command outside your container

**Comment by roukmoute** [comment]
Which command? `composer require --dev symfony/maker-bundle`?

I don't see why I should run a command outside of Docker.
Consider that I don't have PHP on my PC, so I run everything in Docker, which seems normal.
If Docker is only used to install Symfony, then I might as well use the Symfony binary.
The purpose of using Docker is that everything can be executed... in Docker, if you can't do that then you lose the interest of using Docker.

**Comment by maxhelias** [comment]
> Which command? composer require --dev symfony/maker-bundle?


I'm talking about the command you edited and that I'm talking about :
![Capture1](https://user-images.githubusercontent.com/12966574/200135040-fcf4a6eb-0f59-44af-89fc-d05043c9a440.PNG)

> I don't see why I should run a command outside of Docker.
Consider that I don't have PHP on my PC, so I run everything in Docker, which seems normal.


So up to now we are agreed except for the docker commands and that is the whole point of docker

> If Docker is only used to install Symfony, then I might as well use the Symfony binary.

Not only, you can see all the feature of the project here : https://github.com/dunglas/symfony-docker#features

> The purpose of using Docker is that everything can be executed... in Docker, if you can't do that then you lose the interest of using Docker.

Still agree

**Comment by bzoks** [comment]
@roukmoute, you should use Docker Desktop when developing (using mounted folders), this "solves" file ownership issues (except when on WSL). 
A short excerpt of behaviour in various platforms for running docker:
- Linux/Docker Engine
  - the owner ID is directly transferred in both ways (1000 remains 1000, 0 remains 0)
- Windows/Docker Engine for Windows
  - the owner ID is directly transferred in both ways (1000 remains 1000, 0 remains 0)
- Linux/Docker Engine for Linux
  - host OS owner ID is mapped to root inside the container (1000 becomes 0)
  - non-root container users' created files result in arbitrary host OS owner IDs of those files
  - consequence: containers must use only the root user
- Mac/Docker Engine for Mac
  - host OS owner is ignored, all files mounted into container are mapped to container user, new files inside container are mapped back to host OS owner (501 becomes 1000 or 501 becomes 0)
  - changing ownership inside container results in arbitrary host OS file attributes

**Comment by roukmoute** [comment]
@bzoks I can try Docker Desktop eventually but it is not the answer.
I work on Linux and I consider that I don't need Docker Desktop because there is a problem of rights on this repository.

**Comment by bzoks** [comment]
But this is how Docker works in regard to ownerships, currently there is no single approach that would work across all environments (when using bind-mounts). This project is not trying to solve this, as if it would fix the issue for one env, it would cause the issue for other env.
If you want working bind-mount permissions on Linux (without Docker Desktop), then you have to create a user with id 1000 in Dockerfile, switch to that user before starting php-fpm, and then files created inside container will have ownerships that will be compatible with the host system. But this won't work on non-native-linux docker. If you are in the Cross-OS team, then going the Docker Desktop way is the best way to unify permissions, even If it seems "redundant" to use this on Linux.

**Comment by maxhelias** [comment]
Thanks @bzoks for the explanation on ownership.

@roukmoute as explain, is not a problem of rights on this repository. If you find that the troubleshooting is not complete enough (which is true) do not hesitate to submit an PR.

**Comment by chrisVdd** [comment]
> @roukmoute, you should use Docker Desktop when developing (using mounted folders), this "solves" file ownership issues (except when on WSL). A short excerpt of behaviour in various platforms for running docker:
> 
> * Linux/Docker Engine
>   
>   * the owner ID is directly transferred in both ways (1000 remains 1000, 0 remains 0)
> * Windows/Docker Engine for Windows
>   
>   * the owner ID is directly transferred in both ways (1000 remains 1000, 0 remains 0)
> * Linux/Docker Engine for Linux
>   
>   * host OS owner ID is mapped to root inside the container (1000 becomes 0)
>   * non-root container users' created files result in arbitrary host OS owner IDs of those files
>   * consequence: containers must use only the root user
> * Mac/Docker Engine for Mac
>   
>   * host OS owner is ignored, all files mounted into container are mapped to container user, new files inside container are mapped back to host OS owner (501 becomes 1000 or 501 becomes 0)
>   * changing ownership inside container results in arbitrary host OS file attributes

Any chance you can explain how to proceed with Docker Desktop ?
I'm quite lost with this sotry about "mounted" folder and since I got the same issue with the /var folder...

Many thanks !
