### ISSUE TITLE
Some .env vars not exsits

### ISSUE THREAD

**Issue by digitaltim-de** [dunglas/symfony-docker#333]
I become the warning, that some of my .env files not exists. But thats not true. 

Inside .env is the param defined. I found this in the web [link to stackoverflow](https://stackoverflow.com/questions/50743486/environment-variables-not-found-symfony)

<img width="591" alt="image" src="https://user-images.githubusercontent.com/18602381/204117967-d2ecc044-9b21-4611-bbac-255c913ff71e.png">

**Comment by maxhelias** [comment]
And are they present in the .env file in the container?
Do you have the dotenv component that loads your variables ?

**Comment by digitaltim-de** [comment]
> And are they present in the .env file in the container? Do you have the dotenv component that loads your variables ?

Yes, they are existing in the .env file and i have the dotenv component that loads it. I think, the .env  with DIGITALOCEAN_SPACES_ENDPOINT_SCHEMA=https:// is not supported from docker and the VERSION env i never use in my apps, but for error fixing i just define it as VERSION=1 and its not working. So suspected...

**Comment by maxhelias** [comment]
Sorry, but your description is really too short for me to help you.
The problem seems to be unrelated to this project and we want to keep the board issue for problems directly related to the project.
