### ISSUE TITLE
Documentation update for current DigitalOcean Docker Image (enabling BuildKit support)

### ISSUE THREAD

**Issue by hubermic** [dunglas/symfony-docker#334]
The current Docker image provided in the DigitalOcean Marketplace is 19.03.12. Using this image, the steps mentioned in the "Deploying in Production" section need some additional configuration:

**1) BuildKit support**
The Dockerfile needs BuildKit support, otherwise you will face an error saying `dockerfile parse error line 23: Unknown flag: link`.
In order to use the Dockerfile, you need to export the following environment variables first:

`export DOCKER_BUILDKIT=1`
`export COMPOSE_DOCKER_CLI_BUILD=1`

Alternatively you can set this in `/etc/docker/daemon.json` as described here: https://docs.docker.com/build/buildkit/

**2) docker compose**
`docker compose` is not available in this image. You have to use `docker-compose`.

**Comment by Romaixn** [comment]
It seems that the image has been updated: https://marketplace.digitalocean.com/apps/docker

I tested it with a project and I didn't have any problem (while some time ago I also had this problem).

Now the versions are as follows:
- `docker` : 20.10.21
- `docker compose` : 2.12.0

**Comment by bogdaniel** [comment]
Hello,
The same issue will appear when you want to use GitHub actions to build docker images.

`
    - name: Build the Docker image
      env: 
        DOCKER_BUILDKIT: 1
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:$CURRENT_DATE
`

Thanks,
Bogdan

**Comment by maxhelias** [comment]
DigitalOcean now support v2
