### ISSUE TITLE
Using different SSL port getting ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by cakecoke** [dunglas/symfony-docker#335]
Hi, i tried running ``` SERVER_NAME="domain.com" HTTP_PORT=8000 HTTPS_PORT=4443 HTTP3_PORT=4443 docker compose up --build ``` 
and getting ERR_SSL_PROTOCOL_ERROR in chrome, i also tried creating self signed certs, but no change, does anyone know a solution ?

**Comment by maxhelias** [comment]
What is your error ? Is this a trust issue ? 
See : https://github.com/dunglas/symfony-docker/blob/main/docs/tls.md

**Comment by MisterGrouik** [comment]
Same problem using docker and WSL Ubuntu.
If I just put the following lines in .env and docker compose up again, it does not work anymore.
HTTPS_PORT=4443
HTTP3_PORT=4443

**Comment by Soup666** [comment]
Did you guys ever find a fix? Same issue

**Comment by dunglas** [comment]
Let's Encrypt only supports the standard HTTP and HTTPS ports (80 and 443). Creating a LE certificate for another port will not work, you have to use the standard ports or to configure Caddy to use another provider: https://community.letsencrypt.org/t/letsencrypt-doesnt-work-for-different-ports/17519
