### ISSUE TITLE
php_fastcgi using tcp protocol

### ISSUE THREAD

**Issue by julien-its** [dunglas/symfony-docker#340]
Hi, I'm trying to configure the php_fastcgi using a tcp socket instead of unix socket. 

here : https://github.com/dunglas/symfony-docker/blob/main/docker/caddy/Caddyfile
I replaced at line 30 : php_fastcgi 127.0.0.1:9000

Should I also change the line 6 here
https://github.com/dunglas/symfony-docker/blob/main/docker/php/php-fpm.d/zz-docker.conf
 listen = 127.0.0.1:9000

and here 
https://github.com/dunglas/symfony-docker/blob/main/docker/php/docker-healthcheck.sh
line 4 with
if env -i REQUEST_METHOD=GET SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping cgi-fcgi -bind -connect 121.0.0.1:9000; then

But i have a 502 error.
{"level":"error","ts":1670429394.4028077,"logger":"http.log.error","msg":"dialing backend: dial tcp 127.0.0.1:9000: connect: connection refused","request":{"remote_ip":"172.18.0.1","remote_port":"64410"

Do you have an idea,  what should i change in regard to work with tcp insead of socket unix ?
Thank you in advance

**Comment by julien-its** [comment]
Looks like it's working with php_fastcgi php:9000
https://github.com/dunglas/symfony-docker/blob/main/docker/caddy/Caddyfile  
line 30 :
php_fastcgi php:9000

**Comment by digitaltim-de** [comment]
Hi, i am trying the same, but not working for me i have a conneciton refused error. I am trying to do a swarm stack.

**Comment by maxhelias** [comment]
Hi @digitaltim-de, please can you open a new issue with all your information. Thanks
