### ISSUE TITLE
Error:0A000438:SSL routines::tlsv1 alert internal error for "https://caddy/.well-known/mercure"

### ISSUE THREAD

**Issue by exd-al** [dunglas/symfony-docker#342]
Hi,

When trying to publish updates on mercure, I've got this error :
Failed to send an update.
Error:0A000438:SSL routines::tlsv1 alert internal error for "https://caddy/.well-known/mercure"

My installation works well on my local Mac, but as soon as it is deployed online (Ubuntu 20.04.5 LTS / Docker version 20.10.21 / Docker Compose version v2.12.2)  I've got this error, even after making changes described here : https://github.com/dunglas/symfony-docker/blob/main/docs/tls.md

Do you have any idea where the problem is ? 

Thank you in advance

**Comment by maxhelias** [comment]
I think the self-generated certificate isn't trusted by PHP, add the self-signed certificate to the PHP bundle: [extract the local authority generated by Caddy](https://caddyserver.com/docs/automatic-https#local-https) and add it to the bundle use by curl in your php.ini (curl.cainfo = /your/custom/cacert.pem)

**Comment by maxhelias** [comment]
It's related to PHP, you find more information here : https://docs.boltcms.io/5.0/howto/curl-ca-certificates

Another possibility : https://github.com/dunglas/symfony-docker/issues/357

**Comment by anjeylink** [comment]
@exd-al I managed to fix it by changing `caddy` environment `SERVER_NAME`

```diff
  caddy:
    build:
      context: .
      target: app_caddy
    depends_on:
      - php
    environment:
-    SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
+    SERVER_NAME: "${SERVER_NAME:-localhost}, caddy:80"
   ....
```

and in my `.env`

```
SERVER_NAME=localhost
```

**Comment by ziat1988** [comment]
I have the same issue.  When deploy to VPS Digital Ocean, I have my url use https automatic.
But I had to change MERCURE_URL to `https://mydomainserver/.well-known/mercure` to get rid off this error. So basically  MERCURE_URL and MERCURE_PUBLIC_URL will be the **same**. It works, but I'm not sure this is good way.
It seems to me that caddy try to redirect "http://caddy/.well-known/mercure" to "https://caddy/.well-known/mercure" and cause this error. So is there a way to tell caddy to not to do that? 
Thanks
