### ISSUE TITLE
php container allways restart 

### ISSUE THREAD

**Issue by ZoMsi** [dunglas/symfony-docker#348]
Hi, 

I have this issue after running `docker compose up`

> 2022-12-16 20:43:42 Creating a "symfony/skeleton " project at "./tmp"
> 2022-12-16 20:43:42 
> 2022-12-16 20:43:42 In CreateProjectCommand.php line 371:
> 2022-12-16 20:43:42                                                   
> 2022-12-16 20:43:42   Project directory "/srv/app/tmp" is not empty.  
> 2022-12-16 20:43:42                                                   
> 2022-12-16 20:43:42 
> 2022-12-16 20:43:42 create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package> [<directory> [<version>]]]

so the container always restart 
Thank you in advance

**Comment by maxhelias** [comment]
#350 shoud fix your issue. Can you try to rebuild without cache and restart
