### ISSUE TITLE
Getting --link error

### ISSUE THREAD

**Issue by digitaltim-de** [dunglas/symfony-docker#356]
Docker 20.10.21 & 20.10.22:

Error:
dockerfile parse error line 23: Unknown flag: link

If i delete the --link tags it works.

Docker compose latest version 2.14.2 any idea why?

**Comment by maxhelias** [comment]
Your docker engine must be greater than [20.10.14](https://docs.docker.com/engine/release-notes/#201014)

**Comment by maxhelias** [comment]
And if you want more information about the `link` option :
- https://docs.docker.com/engine/reference/builder/#copy---link
- https://www.howtogeek.com/devops/how-to-accelerate-docker-builds-and-optimize-caching-with-copy-link/

**Comment by TacoV** [comment]
The Docker Engine versions OP uses are greater than 20.10.14.
I am experiencing the same issue on Docker Engine 20.10.17.

```$ docker compose build --pull --no-cache
Sending build context to Docker daemon  3.674kB
Sending build context to Docker daemon  3.674kB
2 errors occurred:
        * Error response from daemon: dockerfile parse error line 23: Unknown flag: link
        * Error response from daemon: dockerfile parse error line 23: Unknown flag: link
```

The trick was in the last link: "This feature is only available when using the [BuildKit](https://docs.docker.com/build/buildkit/) backend, and is ignored when using the classic builder backend."
After `export DOCKER_BUILDKIT=1` it all worked as expected

**Comment by digitaltim-de** [comment]
Can confirm, that DOCKER_BUILDKIT fix it. So closed.
