### ISSUE TITLE
Documentation about digital certificates: mention Docker Desktop to inspect ENV variables

### ISSUE THREAD

**Issue by Aerendir** [dunglas/symfony-docker#357]
I'm setting up a new project using this configuration as skeleton.

Once built the containers and copied the cert from the Caddy's container to my local machine, connecting to myapp.localhost gave an error "ERR_SSL_PROTOCOL_ERROR".

Going around to check the issue, I, in the end, discovered I wrongly set the `SERVER_NAME` env variable: in fact, I didn't added it to the `.env` file and so the `docker compose up -d` command didn't set it.

To discover this issue I checked the configuration of the container through Docker Desktop (click on the container name, then click on "Inspect"): there I discovered the `SERVER_NAME` env variable was wrongly set.

This information may be very useful to the ones who are trying to debug issues with TLS certificates and I think it could be added to the documentation.

Checking the [Troubleshooting](https://github.com/dunglas/symfony-docker/blob/main/docs/troubleshooting.md) page, however, I saw it reports back to [TLS page](https://github.com/dunglas/symfony-docker/blob/main/docs/tls.md): in this page, however, there is no help to troubleshoot issues that may happen.

So, the question is: where to add this bit of information about the use of Docker Desktop (or, at least, to double-check the `SERVER_NAME` env var is correctly set)?

**Comment by maxhelias** [comment]
I think you can add a notice here : https://github.com/dunglas/symfony-docker/blob/main/docs/build.md#customizing-the-server-name or here https://github.com/dunglas/symfony-docker/blob/main/docs/tls.md#trusting-the-authority or both

**Comment by maxhelias** [comment]
PR open #368
