### ISSUE TITLE
Vulcain Caddy deleted?

### ISSUE THREAD

**Issue by digitaltim-de** [dunglas/symfony-docker#361]
Symfony Docker Build failed because vulcain/caddy not exists.

https://github.com/dunglas/vulcain/caddy

**Comment by dunglas** [comment]
Weird, it does exist: https://github.com/dunglas/vulcain/blob/main/caddy/go.mod

**Comment by digitaltim-de** [comment]
Is this correct? Because since today, my Builds failed.
![image](https://user-images.githubusercontent.com/18602381/212444107-24a8cdf0-9f2e-4d20-a95e-d924e44daa4f.png)

**Comment by dunglas** [comment]
Can you retry with a fresh cache:

```
docker system prune -a
docker compose build --pull
```

I just tagged released versions of Vulcain and Mercure that should fix the issue.

**Comment by digitaltim-de** [comment]
Working now, Thanks!
