### ISSUE TITLE
fix documentation READ.md

### ISSUE THREAD

**Issue by smehdux** [dunglas/symfony-docker#366]
Hi,

In the READ.md it has been  mentioned : 

`Run docker compose ....`

Please fix all docker compose  by docker-compose (with hyphen): 

regards,

**Comment by bzoks** [comment]
First line in Getting started in README says

> If not already done, [install Docker Compose](https://docs.docker.com/compose/install/) (v2.10+)

`docker-compose` is deprecated, here are some more info on transition: https://docs.docker.com/compose/compose-v2/
