### ISSUE TITLE
Can't get doctrine to work

### ISSUE THREAD

**Issue by bakedbird** [dunglas/symfony-docker#370]
Hi all, 
I did a clean installation, and added doctrine, then run build.
The build fails because I commented out DATABASE_URL in .env, since it exists on docker-compose.

After uncommenting the DATABASE_URL in .env, the build worked but Symfony can't connect to the database because it's using the DATABASE_URL defined in the .env file.

Since DATABASE_URL in the docker-compose file should have precedence, I edited that one, and commented out the one in .env
After running up, symfony can't connect to the DB as it can't find the DATABASE_URL.

So, my question is, what is the proper way to install doctrine?

**Comment by maxhelias** [comment]
Hi!

The proper way is to used the DATABASE_URL with the correct configuration. 
To keep a consistency between the app and docker, I personally use this configuration line `DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}&charset=utf8"` and configure the environment variables depending on it on the `.env` file.

In the other case, if you don't want to use the DATABASE_URL variable, them you have to configure the connection in the doctrine.yaml file. You will find more information in the documentation : https://www.doctrine-project.org/projects/doctrine-bundle/en/latest/configuration.html#doctrine-dbal-configuration

**Comment by bakedbird** [comment]
Hi @maxhelias, 
so, I should add the correct DATABASE_URL in the env file as well as the docker-compose file?

**Comment by maxhelias** [comment]
There is no DATABASE_URL in the docker-compose file and no need to have it. DATABASE_URL is needed for doctrine configuration with the database and not for docker. It just has to match with the connection configuration with the docker service.

I recommend rather the first command (`docker compose exec php composer require`) and those for any package, because it will allow to install the last package available for the version of php configured for the docker container and not the php installed on your host.

**Comment by bakedbird** [comment]
Hmm, I see. Since the variable is there when creatingt the project, I thought it was needed to be configured only there and not in the .env file. I'm talking about this. line here
```
services:
  php:
    ...
    environment:
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-14}
```
So, I can remove this one, and configure it in the .env file. Did I understand correctly?
Thank you for the suggestion for installing the packages :)

**Comment by bedfir** [comment]
Here are the steps to follow.

### **in the .env**
- Comment the DATABASE_URL
`# DATABASE_URL="postgresql://ludo-user:Pomme123@127.0.0.1:5432/ludo?serverVersion=15&charset=utf8"
`
- Create 4 environment variables
```
      POSTGRES_USER=YourPostgresUser
      POSTGRES_PASSWORD=yourPassword
      POSTGRES_DB=yourDbName
      POSTGRES_VERSION=postgresVersion(current 15)
```
### **inside the docker-compose**
- And finally remove the default values defined in the DATABASE_URL
`DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}
`


_PS: you can also set up the 4 environment variables in a new **.env.local** file,  that are specific to your local machine._

**Comment by bakedbird** [comment]
Hi @bedfir,
this is exactly what I have done and am having the issue.

Step by step:

- `docker compose build --pull --no-cache`
- `docker compose up`
- `docker cp $(docker compose ps -q caddy):/data/caddy/pki/authorities/local/root.crt /tmp/root.crt && sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain /tmp/root.crt`
- `docker compose exec php composer require symfony/orm-pack`
- `docker compose down --remove-orphans`
- edit docker-compose.yml:
```
services:
  php:
    ...
    environment:
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}
```
- edit .env (comment DATABASE_URL and add the POSTGRES params)
```
...
###> doctrine/doctrine-bundle ###
# Format described at https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
# IMPORTANT: You MUST configure your server version, either here or in config/packages/doctrine.yaml
#
# DATABASE_URL="sqlite:///%kernel.project_dir%/var/data.db"
# DATABASE_URL="mysql://app:!ChangeMe!@127.0.0.1:3306/app?serverVersion=8&charset=utf8mb4"
# DATABASE_URL="postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=15&charset=utf8"
###< doctrine/doctrine-bundle ###

POSTGRES_USER=db_user
POSTGRES_PASSWORD=db_password
POSTGRES_DB=db
POSTGRES_VERSION=15
```

- `docker compose build --pull --no-cache`. After some time, I get this error:
```
0 2.188 Generated optimized autoload files (authoritative) containing 2524 classes
#0 2.201 + composer dump-env prod
#0 2.379 Successfully dumped .env files in .env.local.php
#0 2.388 + composer run-script --no-dev post-install-cmd
#0 2.566 
#0 2.566 Run composer recipes at any time to see the status of your Symfony recipes.
#0 2.566 
#0 2.569 Executing script cache:clear [KO]
#0 2.915  [KO]
#0 2.915 Script cache:clear returned with error code 1
#0 2.915 !!  
#0 2.915 !!  In EnvVarProcessor.php line 189:
#0 2.915 !!                                                     
#0 2.915 !!    Environment variable not found: "DATABASE_URL".  
#0 2.915 !!                                                     
#0 2.915 !!  
#0 2.915 !!  
#0 2.915 Script @auto-scripts was called via post-install-cmd
------
failed to solve: executor failed running [/bin/sh -c set -eux;  mkdir -p var/cache var/log;     if [ -f composer.json ]; then        composer dump-autoload --classmap-authoritative --no-dev;          composer dump-env prod;          composer run-script --no-dev post-install-cmd;             chmod +x bin/console; sync;     fi]: exit code: 1
```

**Comment by bedfir** [comment]
My apologies, yes Symfony is unable to find the "DATABASE_URL" environment variable, which is used to configure the database connection for Doctrine ORM.

- The problem: 

**The PDO is missing in the Dockerfile, there is only pdo_pgsql, as mentioned in the documentation (link below) pdo_pgsql implements PDO.**
_PDO_PGSQL is a driver that implements the [PHP Data Objects (PDO) interface](https://www.php.net/manual/en/intro.pdo.php) to enable access from PHP to PostgreSQL databases._

**To solve the problem you just have to add in the Dockerfile the PDO extension**

```
RUN set -eux; \
    install-php-extensions \
    intl \
    zip \
    apcu \
    opcache \
    pdo \             <==== Add this line
    ;
```

Then run `docker compose build --pull --no-cache`
And `docker compose up`

For the configuration of the database please follow [the steps I have edited](https://github.com/dunglas/symfony-docker/issues/370#issuecomment-1405362017)

**Comment by bakedbird** [comment]
Thank you @bedfir, adding PDO in Dockerfile fixed the issue and everything seems to be working correctly now.

My question now is, is this addition mentioned somewhere and I missed it? I've been trying to find a solution for days and I did not see this specific change mentioned somewhere.

**Comment by dunglas** [comment]
This should be handled automatically by Flex. It's maybe a bug in the Flex recipe for Doctrine ORM?

**Comment by maxhelias** [comment]
https://github.com/dunglas/symfony-docker/issues/370#issuecomment-1405063475
> I'm talking about this. line here

Oh yes, I forgot that.

> This should be handled automatically by Flex. It's maybe a bug in the Flex recipe for Doctrine ORM?

I don't think so, I did an installation last week and had no problems.  Flex did add these lines on the Dockerfile :
```
###> doctrine/doctrine-bundle ###
RUN apk add --no-cache --virtual .pgsql-deps postgresql-dev; \
	docker-php-ext-install -j$(nproc) pdo_pgsql; \
	apk add --no-cache --virtual .pgsql-rundeps so:libpq.so.5; \
	apk del .pgsql-deps
###< doctrine/doctrine-bundle ###
```
---
I am confused, I do not understand what is the real issue `Environment variable not found: "DATABASE_URL". ` or `could not find driver`

**Comment by bedfir** [comment]
Yes you're right, it's handled automatically by Flex.
No need to add the PDO in the Dockerfile and it should work with [the right config.](https://github.com/dunglas/symfony-docker/issues/370#issuecomment-1405362017)

**Comment by bakedbird** [comment]
Yes, when I install doctrine, the recipe part in Dockerfile is updated, exactly like @maxhelias mentioned. When running the build command after that, it fails with the error mentioned.

Adding the PDO in the Dockerfile fixed the error, so, maybe as @dunglas mentioned, it can be an issue on the recipe?

**Comment by maxhelias** [comment]
The `charset=utf8` can be add in the `docker-compose.yaml` file, you can submit a PR 😉 

> though I am not sure it may have caused the issue previously

Yes, I agree.
