### ISSUE TITLE
Doesn't work with the Webpack Encore

### ISSUE THREAD

**Issue by YSkrzypczyk** [dunglas/symfony-docker#372]
hello, 
I use a WEBPACK for the generation of my css and my js and so it adds a build folder in the public folder. Unfortunately this folder does not appear in the caddy container, is there a solution?

I add this :

RUN apk add --no-cache \
		...
    	nodejs \
    	npm \
		...
	;

and this : 

RUN set -eux; \
    npm install; \
    npm update; \
    npm run build;

But in this logic I have to rebuild to run the webpack again which is not perfect.

Thanks in advance

**Comment by Romaixn** [comment]
Hi, you can check https://github.com/dunglas/symfony-docker/pull/186 for an example of webpack reuse with symfony-docker  

Hope it helps you !

**Comment by YSkrzypczyk** [comment]
> Hi, you can check #186 for an example of webpack encore with symfony-docker
> 
> Hope it helps you !

The node service is run only on the   `docker-compose.override.yml` ? Do only on the dev environnement. 
It's not possible to do npm run build in the PHP container and see it in the caddy container in prod ?

**Comment by Romaixn** [comment]
Yes in production, you have to do an `npm run build` instead of launching the webpack server

**Comment by YSkrzypczyk** [comment]
Ok but if I want to rebuild the CSS I have to rebuild the container ? Do npm run build on the PHP container won't be enough ?

**Comment by maxhelias** [comment]
As @Romaixn has said, look at #186. It's not ready, we need to do some rework but you can use it as inspiration for your case.

Also as we want to offer the project ready for production, we don't want to include any asset build artifacts in the PHP container for security reasons.

BTW, run a command like this inside a container in production it's not a good practice and a good use of docker for production

**Comment by lchhieu** [comment]
Any there solution? I tried with https://github.com/dunglas/symfony-docker/pull/186 but it does not work
