### ISSUE TITLE
Use heath check feature from Caddy

### ISSUE THREAD

**Issue by maidmaid** [dunglas/symfony-docker#377]
Caddy has its own [health check feature](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#health_uri). In the next Caddy [2.6.3 version](https://github.com/caddyserver/caddy/issues/5281), the heath check will also work with `php-fpm.sock` and it will be possible to write something like :

```Caddyfile
localhost

route {
    root * /srv/app/public
    php_fastcgi unix//var/run/php/php-fpm.sock {
        health_uri /ping
    }
}
```

The advantage compared to the current [docker-healthcheck.sh](https://github.com/dunglas/symfony-docker/blob/main/docker/php/docker-healthcheck.sh) is that Caddy is really waiting php-fpm before serving traffic to it. It's very important when we build only one container with php and caddy together as in this described [here](https://github.com/dunglas/symfony-docker/issues/375).

**Comment by maidmaid** [comment]
[2.6.3 released](https://github.com/caddyserver/caddy/releases/tag/v2.6.3) :tada:

**Comment by maxhelias** [comment]
Close has explain here : https://github.com/dunglas/symfony-docker/pull/384#issuecomment-1658311145
