### ISSUE TITLE
Putting into production using docker hub instead of git clone

### ISSUE THREAD

**Issue by BliiTzZ** [dunglas/symfony-docker#382]
Hello, I have to create an end of year project for my training where we have to respect certain criteria: 
- We have to create a Symfony project that will run in a 1st container
- We have to create a database in postgreSQL which will run in a 2nd container
This project must be published on github, and with the help of github actions we must create a CI/CD to publish our code on docker HUB.
- When we go live, we just need to put a "docker-compose.prod" on the VPS which when launched, will be able to fetch our project and launch the 3 containers (php, caddy and database). 

But using your tool, we can't manage to publish on docker hub our images so we don't need to do "git clone" on our VPS to get our project and launch it. Knowing that you use a dockerFile for the 3 containers, we are not sure in which direction to go to succeed in using your tool in our case, nor how to create our docker-compose.prod.

**Comment by maxhelias** [comment]
Hello,

Here are some links that may help you:

- [docs.docker.com/ci-cd/best-practices](https://docs.docker.com/ci-cd/best-practices/)
- [docs.docker.com/ci-cd/github-actions/#optimizing-the-workflow](https://docs.docker.com/ci-cd/github-actions/#optimizing-the-workflow)
- [docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)
- [docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions)

And some article : 
 - https://medium.com/@stoyanov.veseline/pushing-docker-images-to-a-private-registry-with-docker-compose-d2797097751
 - https://api-platform.com/docs/deployment/

Hopefully this will help you to better understand how docker works

**Comment by BliiTzZ** [comment]
The problem is not in the creation of the docker-compose, nor the docker file or github action. We know how to do all the steps with a basic symfony project, we are able to make github action and the push workflow on docker hub work, and we are able to make the docker-compose.prod work on our VPS. 
The concern we have is to do the same thing but with your "symfony-docker" tool because there's this whole "caddy" aspect added, and you're using one docker file to install everything. So the problem we have is that we don't know how to push on docker hub so that the VPS comes to take the last update of the project on docker hub.
It works for a simple symfony project, but we don't understand at all the approach we have to take when using your tool. I'm not sure if it's a good idea to use your tool, but I'm not sure if it's a good idea to use your tool because it's not a good idea to use your tool because it's not a good idea to use your tool. 
I'm not sure if it's a good idea to have a command in our project to push 3 different images? Such as an image for our symfony project, an image for our caddy server, and an image for the database? 
This means that you would have to modify your DockerFile to separate it into several DockerFiles. 

I don't know if you understand our goal

**Comment by maxhelias** [comment]
The single Dockerfile it's not an issue todo this. You can use the `docker compose` command to [build](https://docs.docker.com/engine/reference/commandline/compose_build/) & [push](https://docs.docker.com/engine/reference/commandline/compose_push/) or use the `target` option like in the example on the APIP doc : https://api-platform.com/docs/deployment/minikube/#building-and-pushing-docker-images

**Comment by maxhelias** [comment]
I found this tutorial and I think it should help you : https://youtu.be/qv-P_rPFw4c?t=6216

**Comment by BliiTzZ** [comment]
J'ai effectivement trouvé la solution grace à API Platform qui utilise le même repo en expliquant comment deployer dans plusieurs images afin de les récupérer ;) Merci beaucoup. 

J'aurais une dernière petite question mais sauriez vous si docker swarm fonctionnerai avec ce repo ? Je m'explique, on dois y rajouter de la réplication mais nous ne savons pas trop ce qui est à répliqué en général. Est ce qu'il faut répliquer Caddy + php symfony + la base de donnée ? Car nous avons réussi à repliquer plusieurs fois la base de donnée, mais quand nous essayons de repliquer caddy et php mais chaque fois le 1er container de réplique fonctionne, mais quand la 2nd réplique se lance, elle crash et tente de se relancer chaque fois.

Pour le container php je recois des erreurs en rapport avec FPM.lock qui serai déjà utilisé par un autre service, je pense qu'en lancant 2 repliques de mon php j'ai l'impression que la 2nd réplique n'as pas possibilité d'accédeer aux ressources déjà utilisés par la 2nd réplique. 

Quant aux containers caddy je ne sais pas pourquoi le 2nd container crash. 

J'ai bien rajouté ça 
php:
    image: myphp
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
caddy:
 image: myimage
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  database:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

**Comment by maxhelias** [comment]
I not very familiar with docker swarm or any scalability solution but for High Availability in general you need to rethink the architecture or configuration, you can't use this project like this for HA.

Nevertheless, what I can tell you is: [caddy can load balancing](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#examples) between different backend node and each node must have its own unix socket configuration : https://github.com/dunglas/symfony-docker/blob/main/docker/php/php-fpm.d/zz-docker.conf#L6
