### ISSUE TITLE
Preparing cache during build of the Prod container fails if you use Redis for cache

### ISSUE THREAD

**Issue by WebDaMa** [dunglas/symfony-docker#383]
Seems related to this issue: https://github.com/symfony/symfony/issues/24865

```yaml
RUN set -eux; \
    mkdir -p var/cache var/log; \
    if [ -f composer.json ]; then \
        composer dump-autoload --classmap-authoritative --no-dev; \
        composer dump-env prod; \
        composer run-script --no-dev post-install-cmd; \
        chmod +x bin/console; sync; \
    fi
```
Had to remove `composer run-script --no-dev post-install-cmd; \` or it tries to connect to Redis and build fails.

Maybe this should be added in the docs?

**Comment by maxhelias** [comment]
From what I read from the symfony issue it should be fixed since the redis service cache is lazy.
If this is not the case, an issue must be (re)opened on the project concerned because this behavior is not normal and must be fixed instead of modifying our documentation temporarily
