### ISSUE TITLE
Docker container & dependency injection

### ISSUE THREAD

**Issue by vinceAmstoutz** [dunglas/symfony-docker#390]
I have a strange problem since I switched my company's application, on which we were developing with the Symfony Local Web Server, to your Docker template.

When I build and launch the containers in development mode I have lot of controllers that are not injected in the container as you can see below:

- Extract of injected controllers (that I have when I do it outside the container from my application):
![image](https://user-images.githubusercontent.com/46444652/227482686-700e64e9-dc3a-4099-84e1-2eaa75b65374.png)

- When I do it in the PHP container I have only this:
![image](https://user-images.githubusercontent.com/46444652/227482905-ef3ea3b4-7ce4-4518-a4c6-13b0b68370ed.png)

This gives me the following 500 error (for example): 
![image](https://user-images.githubusercontent.com/46444652/227484263-3bee3c6b-1a86-4c15-bb29-346474810e0f.png)

**On the other hand when I decrease the number of controllers (less than 40) and well it works perfectly.**

I tried increasing the `memory_limit`, doing the `composer install` in different ways and clearing the cache, without success.

I did not find anything about this issue.

Thanks for advance.

**Comment by maxhelias** [comment]
Hi, 

If there are a lot of files the cache configuration is probably not adapted for your project. Try to change these lines : https://github.com/dunglas/symfony-docker/blob/main/docker/php/conf.d/app.ini#L8-L13

**Comment by vinceAmstoutz** [comment]
> Hi,
> 
> If there are a lot of files the cache configuration is probably not adapted for your project. Try to change these lines : https://github.com/dunglas/symfony-docker/blob/main/docker/php/conf.d/app.ini#L8-L13

Hi @maxhelias ,
I will try these values :

```
realpath_cache_size = 8192K
realpath_cache_ttl = 600
opcache.interned_strings_buffer = 32
opcache.max_accelerated_files = 40000
opcache.memory_consumption = 1024
opcache.enable_file_override = 1
```
I also try disabled opcache and apcu in my Dockerfile (like in my local environment) but it still doesn't work : 
```
RUN apk add --no-cache \
        acl \
        fcgi \
        file \
        gettext \
        git \
        libldap \
        postgresql-libs \
    ;

RUN set -eux; \
    install-php-extensions \
        #apcu \
    	calendar \
    	intl \
        #opcache \
     	ldap \
	pdo_pgsql \
        pgsql \
    	zip \
    ;
```

**Comment by vinceAmstoutz** [comment]
And also disable xdebug install (again like in my local env) : 
```
#RUN set -eux; \
#	install-php-extensions \
#    	xdebug \
#    ;
```
but it still doesn't work and it's change nothing in my container

**Comment by maxhelias** [comment]
Are you rebuild with the `--no-cache` option ?

**Comment by maxhelias** [comment]
This is strange, I have no idea of the origin and no way to reproduce this case. 

The only difference I see is the default php.ini chosen here: https://github.com/dunglas/symfony-docker/blob/main/Dockerfile#L112

**Comment by vinceAmstoutz** [comment]
> This is strange, I have no idea of the origin and no way to reproduce this case.
> 
> The only difference I see is the default php.ini chosen here: https://github.com/dunglas/symfony-docker/blob/main/Dockerfile#L112

Tanks for your response. I will create soon a public repo with test code to reproduce.

**Comment by vinceAmstoutz** [comment]
Unfortunately, I can't reproduce the problem. It is probably our controllers that are responsible (especially the services injected into the builders) for this problem because when I regenerate 200 fresh new controllers with simple code, it works perfectly. Optimization for a project of this size may be necessary and the cause of this problem.

Thanks for all.

**Comment by vinceAmstoutz** [comment]
@maxhelias We have abandoned the use of this template because it is probably due to performance problems on the legacy project. We'll test again later when we're done refactoring and optimizing. 

For the moment we use docker-compose and a github action worklfow that uses jobs to reproduce the CI, it as well as possible.

I hope it's right and that it wiI hope it's right and that it will work.
