### ISSUE TITLE
CI fails to connect to app, no idea why

### ISSUE THREAD

**Issue by jurchiks** [dunglas/symfony-docker#394]
I created a project using this template, added `symfony/orm-pack` and changed the database user/password/dbname written in `docker-compose.yml`, as well as mapped port 5432 from container to the same port on host machine, to enable PHPStorm to connect to it.
This for some reason broke CI, even though it still works fine on my machine (and I thought Docker was supposed to get rid of this joke):
![image](https://user-images.githubusercontent.com/542788/230795437-0656350b-2a6d-4e9f-a0cb-827bc1714e3c.png)
Unfortunately, because this step of CI is not very detailed, I have no idea what exactly broke.

Am I not allowed to change the default user/password/dbname in `docker-compose.yml`?
Am I not allowed to expose port 5432 to the host machine?
If so, why not?

I changed the user/pwd/dbname because `.env` `DATABASE_URL` contained `!ChangeMe!`, but you can't really change it without changing `docker-compose.yml` (and it worked, as expected, except here), and I exposed port 5432 for PHPStorm (and it worked, as expected). If there's a better way to connect to the db container using PHPStorm without exposing that port, do tell.

The `.env` file does not contain the variables `POSTGRES_USER`, `POSTGRES_PASSWORD`, and `POSTGRES_DB`, only `DATABASE_URL`, but afaik `.env` is for Symfony, not for Docker, or is that not right?

P.S. `docker-compose.yml` `services.php.environment.DATABASE_URL` has `serverVersion=14`, but the current container version added by `doctrine/doctrine-bundle` is 15. The former should probably be updated.

**Comment by maxhelias** [comment]
You need to align this line too : https://github.com/dunglas/symfony-docker/blob/main/docker-compose.yml#L21
The best way is to create the variables you mentioned POSTGRES_USER, POSTGRES_PASSWORD, and POSTGRES_DB and align the DATABASE_URL like on the line above

**Comment by jurchiks** [comment]
I _have_ changed that line as well, that's the thing.

**Comment by maxhelias** [comment]
Can you publish a reproducer that I can watch ?

**Comment by jurchiks** [comment]
Oh wow, it actually broke even before I changed anything!
https://github.com/jurchiks/ci-break/commits/main
Looks like the problem is even bigger.

**Comment by maxhelias** [comment]
Your bin/console file has no execution rights. Give it the 755 rights and it will fix your CI

**Comment by maxhelias** [comment]
You must change the rights from your machine and not from the container. See my PR : https://github.com/jurchiks/ci-break/pull/1

The `bin/console` file already had no execution rights but in the docker-entrypoint it was not called without the orm-pack. https://github.com/jurchiks/ci-break/blob/main/docker/php/docker-entrypoint.sh#L31-L62

**Comment by jurchiks** [comment]
That's weird, because like I already showed, it IS executable on BOTH my machine AND container. I don't know why it isn't executable in the repository despite having the right settings for Git to recognise it.
I see that the Dockerfile already contains `chmod +x bin/console; sync;`, but I guess that runs inside the container?

Turns out you have to turn `core.filemode` OFF on Windows in order for `git update-index --chmod=+x bin/console` to work correctly, otherwise something keeps reverting the filemode changes instantly, and that reverted filemode change shows up in PHPStorm, but not the +x change... Makes no sense to me.

I think it should be mentioned in the project README that this is a potential issue on Windows machines, like a P.S. at the bottom or something.
