### ISSUE TITLE
Error in docker-compose build

### ISSUE THREAD

**Issue by Samir-R** [dunglas/symfony-docker#399]
Hello,

I have this error when I run -> docker-compose build --pull --no-cache : 

....
Step 29/41 : COPY --from=composer --link /composer /usr/bin/composer
 ---> a1c8c2f0b81e
Step 30/41 : COPY --from=composer --link composer.* symfony.* ./
ERROR: Service 'php' failed to build: COPY failed: no source files were specified

This corresponds to line 84 of Dockerfile

My version of docker-compose is 1.26.0, it's not v2 but i don't think that's the problem.

Thanks.
Regards.

**Comment by maxhelias** [comment]
I think it's related to your version. Try it and we'll know
