### ISSUE TITLE
Error on running Docker Compose Build

### ISSUE THREAD

**Issue by YoanADE** [dunglas/symfony-docker#402]
Hello, 

I'm trying to build my containers and I got this error message : 

 => ERROR resolve image config for docker.io/docker/dockerfile:1.4                                                                             0.4s
------
 > resolve image config for docker.io/docker/dockerfile:1.4:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: ``

Someone know how to fix the issue? Thanks

**Comment by maxhelias** [comment]
Hello,
The error indicates a credentials issue :
> failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = **error getting credentials** - err: exit status 1, out:

Based on my research, there is some issue with Docker WSL (for Window), maybe try to update to install.
