### ISSUE TITLE
Permission denied with mkdir()

### ISSUE THREAD

**Issue by ziat1988** [dunglas/symfony-docker#403]
I'm trying to create a folder in public folder with mkdir() but I got : "Failed to create "/srv/app/public/uploads": mkdir(): Permission denied":
``` php
public function index(Filesystem $fs): JsonResponse
    {
//...
        $dir = $this->getParameter('kernel.project_dir');
        $fs->mkdir($dir.'/public/uploads');

        return $this->json([
           'message'=>'OK'
        ]);
    }
```
My ls -la in container show that all directory is with root permission. My host machine is Ubuntu with user id 1000. I tried to run  `docker compose run --rm php chown -R $(id -u):$(id -g) .` but it seems not the solution.
Thanks for help.

**Comment by 7-zete-7** [comment]
@ziat1988, you can add the creation of this directory in the same way as the var directory in `Dockerfile` and setting the permissions to this directory, as for the var directory, in `docker/php/docker-entrypoint.sh`.

#### Dockerfile
```diff
 RUN set -eux; \
-    mkdir -p var/cache var/log; \
+    mkdir -p var/cache var/log public/uploads; \
     if [ -f composer.json ]; then \
         composer dump-autoload --classmap-authoritative --no-dev; \
         composer dump-env prod; \
         composer run-script --no-dev post-install-cmd; \
         chmod +x bin/console; sync; \
     fi
```

#### docker/php/docker-entrypoint.sh
```diff
-    setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX var
-    setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX var
+    setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX var public/uploads
+    setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX var public/uploads
```
