### ISSUE TITLE
cURL error 35: OpenSSL/3.1.0: error:0A000438:SSL routines::tlsv1 alert internal error

### ISSUE THREAD

**Issue by sajjad-ardekani** [dunglas/symfony-docker#406]
Hello,

I have issue when I want to send request with guzzle and HttpClient in Controller.

I'm trying to send request to https://localhost/api/test but throw this exception:

cURL error 7: Failed to connect to localhost port 443 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://localhost/api/test

and send request to http://localhost/api/test:

cURL error 7: Failed to connect to localhost port 80 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost/api/test

docker compose exec php curl --location --request GET ‘https://localhost/api/test’

curl: (7) Failed to connect to localhost port 443 after 0 ms: Couldn’t connect to server

*** curl request wokrs with Postman ***

Thanks

**Comment by rguennichi** [comment]
Probably you should not use "https" while communicating with another service internally in the same docker network, the cert is not recognised/installed in containers store (which is IMO tricky to setup for each container), HTTPS will work if you request a running app from your host machine.
