### ISSUE TITLE
Add flex support

### ISSUE THREAD

**Issue by maidmaid** [dunglas/symfony-docker#412]
Using flex could be a nice DX, compared to the [current manual setup way](https://github.com/dunglas/symfony-docker/blob/main/docs/existing-project.md). All's right after running a `composer req dunglas/symfony-docker`.

**Comment by maxhelias** [comment]
This could be an idea but with a `composer.json` at the root of the project, i'm afraid it would break the way to symfony is installed during the setup : https://github.com/dunglas/symfony-docker/blob/main/docker/php/docker-entrypoint.sh#L10-L24
And also in the docker build, which will warm up the vendor and cache in layer : https://github.com/dunglas/symfony-docker/blob/main/Dockerfile#L81-L83 & https://github.com/dunglas/symfony-docker/blob/main/Dockerfile#L92-L97

**Comment by maxhelias** [comment]
Otherwise we should create a pack and see if we can have it in official recipes with a `docker` alias ? WDYT @dunglas ?

**Comment by dunglas** [comment]
Then we'll have a chicken and egg problem: the user will need php and composer to get started... which are provided by this project.

One main goal of this project is to be able to get started without having to install anything except Docker locally.

**Comment by maxhelias** [comment]
For the reason mentioned above, I'm closing this issue.
