### ISSUE TITLE
ERROR process "RUN set -eux; \......" exit code 255

### ISSUE THREAD

**Issue by smadaman** [dunglas/symfony-docker#413]
I am trying to utilise this package to get an existing Symfony5.4 project up and going in a Docker container. I have copied all of the files into the project and then attempted to run the documented command: **docker compose build --no-cache --pull** assuming it would just work.

It ends up error'ing out with:
#31 ERROR: process "/bin/sh -c set -eux; \tmkdir -p var/cache var/log;     if [ -f composer.json ]; then \t\tcomposer dump-autoload --classmap-authoritative --no-dev; \t\tcomposer dump-env prod; \t\tcomposer run-script --no-dev post-install-cmd; \t\tchmod +x bin/console; sync;     fi" did not complete successfully: exit code: 255

I'm not massively up on Docker, just learning it, but wondering if there is something obvious in that part of the script that I may have to modify to get it to work? I haven't changed anything yet so all config is default

**Comment by maxhelias** [comment]
Nothing to do, there is something wrong thiw your existing project. 
There command should work before outside of docker otherwise the build can't be done
```
composer install --prefer-dist --no-dev --no-autoloader --no-scripts --no-progress
composer dump-autoload --classmap-authoritative --no-dev
composer dump-env prod
composer run-script --no-dev post-install-cmd
```

**Comment by smadaman** [comment]
Thanks @maxhelias. That makes sense and has pointed me in the right direction to resolve the issue
