### ISSUE TITLE
Cant build previously working container

### ISSUE THREAD

**Issue by frogtube** [dunglas/symfony-docker#419]
Hi Kevin,

I am using your bundle for quite some projects now (and thx for that :D) but recently I was unable to build images of a new project. Testing to kill the container on an on-going project and building again failed at the same step.
Here is the error messages that I see in two places :

FIRST :
 => CACHED [app_caddy 2/5] WORKDIR /srv/app                                                                                                                                                                               0.0s
 => CACHED [app_php  2/21] WORKDIR /srv/app                                                                                                                                                                               0.0s
 => ERROR [app_caddy_builder 2/2] RUN xcaddy build  --with github.com/dunglas/mercure  --with github.com/dunglas/mercure/caddy  --with github.com/dunglas/vulcain  --with github.com/dunglas/vulcain/caddy              110.3s
 => [app_php  3/21] COPY --from=php_extension_installer --link /usr/bin/install-php-extensions /usr/local/bin/                                                                                                            0.1s
 => [app_php  4/21] RUN apk add --no-cache   acl   fcgi   file   gettext   git      make  ;                                                                                                                              11.3s
 => CANCELED [app_php  5/21] RUN set -eux;     install-php-extensions      intl      zip      apcu   opcache     ;                                                                                                       99.4s
------
 > [app_caddy_builder 2/2] RUN xcaddy build     --with github.com/dunglas/mercure       --with github.com/dunglas/mercure/caddy         --with github.com/dunglas/vulcain       --with github.com/dunglas/vulcain/caddy:
#0 0.427 2023/06/16 10:00:55 [INFO] Temporary folder: /tmp/buildenv_2023-06-16-1000.985127823
#0 0.427 2023/06/16 10:00:55 [INFO] Writing main module: /tmp/buildenv_2023-06-16-1000.985127823/main.go
#0 0.427 package main
#0 0.427 
#0 0.427 import (
#0 0.427        caddycmd "github.com/caddyserver/caddy/v2/cmd"
#0 0.427 
#0 0.427        // plug in Caddy modules here
#0 0.427        _ "github.com/caddyserver/caddy/v2/modules/standard"
#0 0.427        _ "github.com/dunglas/mercure"
#0 0.427        _ "github.com/dunglas/mercure/caddy"
#0 0.427        _ "github.com/dunglas/vulcain"
#0 0.427        _ "github.com/dunglas/vulcain/caddy"
#0 0.427 )
#0 0.427 
#0 0.427 func main() {
#0 0.427        caddycmd.Main()
#0 0.427 }
#0 0.427 2023/06/16 10:00:55 [INFO] Initializing Go module
#0 0.427 2023/06/16 10:00:55 [INFO] exec (timeout=-2562047h47m16.854775808s): /usr/local/go/bin/go mod init caddy 
#0 0.450 go: creating new go.mod: module caddy
#0 0.451 go: to add module requirements and sums:
#0 0.451        go mod tidy
#0 0.452 2023/06/16 10:00:55 [INFO] Pinning versions

SECOND:

#0 108.5 github.com/dunglas/mercure/caddy imports
#0 108.5        github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile imports
#0 108.5        github.com/caddyserver/caddy/v2/modules/caddytls imports
#0 108.5        github.com/smallstep/certificates/authority/provisioner imports
#0 108.5        github.com/slackhq/nebula/cert imports
#0 108.5        crypto/ecdh: package crypto/ecdh is not in GOROOT (/usr/local/go/src/crypto/ecdh)
#0 110.2 2023/06/16 10:02:45 [FATAL] exit status 1
------
failed to solve: executor failed running [/bin/sh -c xcaddy build       --with github.com/dunglas/mercure       --with github.com/dunglas/mercure/caddy         --with github.com/dunglas/vulcain       --with github.com/dunglas/vulcain/caddy]: exit code: 1

Can you help on this ?

Many thx

**Comment by maxhelias** [comment]
Hi @frogtube,

It seems that your build is based on cache and a version without this fix : https://github.com/dunglas/symfony-docker/pull/407, update it and try a rebuild with the flag `--no-cache`

**Comment by marcelCarpinter** [comment]
Hi,
I am also having the same problem. I just got the latest source, run the command: docker compose build --pull --no-cache
But it gets an error and never builds

**Comment by frogtube** [comment]
Hi @maxhelias,

Thx for your reply. The problem was for me the same than the one described here https://github.com/dunglas/mercure/issues/770
I just made the modification in the dockerfile required by Dunglas 
-caddy:2.6-builder-alpine
+caddy:2.7-builder-alpine

Sorry for my late reply
