### ISSUE TITLE
Using Symfony Docker with an existing MySQL database

### ISSUE THREAD

**Issue by yourwebmaker** [dunglas/symfony-docker#426]
Hi, 

First of all, thanks for this project. It saves a lot of time from us on setting up a docker env with SF.

I'm trying to adapt a small project that uses an old MySql 5.7 database and some libs that execute some queries that run only in MySQL. 

After following the steps mentioned here https://github.com/dunglas/symfony-docker/blob/main/docs/existing-project.md it always end up with Postgres configuration in the Dockerfile, docker compose, `env` file, etc after the recipes step:

Here it is one from `Dockerfile`:

```
###> recipes ###
###> doctrine/doctrine-bundle ###
RUN apk add --no-cache --virtual .pgsql-deps postgresql-dev; \
	docker-php-ext-install -j"$(nproc)" pdo_pgsql; \
	apk add --no-cache --virtual .pgsql-rundeps so:libpq.so.5; \
	apk del .pgsql-deps
###< doctrine/doctrine-bundle ###
###< recipes ###
```

Will the composer docker plugin/recipe will always default to Postgres, no matter if I set the env variables to MySql?

I'm asking that before I start porting the whole project to Postgres. 

Thanks!

**Comment by maxhelias** [comment]
Hi,

We have chosen to use postgres by default in recipes.
Otherwise, you can use the maker-bundle with the command make:docker:database to generate a database service where you can choose between MySQL / MariaDB / Postgres : symfony/maker-bundle#640

**Comment by yourwebmaker** [comment]
Hi,

By checking that PR I can't see where they update the Dockerfile adding the MySQL packages (eg. pdo_mysql, etc). So I ported the whole project in the meanwhile to Postgres hehehe
