### ISSUE TITLE
Error: unexpected EOF

### ISSUE THREAD

**Issue by cdesign** [dunglas/symfony-docker#427]
Hello..

I am getting the following EOF error near the end of `docker compose build --no-cache --pull`:

```
52.54 github.com/dunglas/mercure/caddy imports
52.54   github.com/dunglas/mercure imports
52.54   github.com/kevburnsjr/skipfilter imports
52.54   github.com/RoaringBitmap/roaring/roaring64: github.com/RoaringBitmap/roaring@v1.3.0: read "https:/proxy.golang.org/@v/v1.3.0.zip": unexpected EOF
53.28 2023/07/17 20:38:57 [FATAL] exit status 1
------
failed to solve: process "/bin/sh -c xcaddy build v2.6.4 \t--with github.com/dunglas/mercure/caddy \t--with github.com/dunglas/vulcain/caddy" did not complete successfully: exit code: 1
```

Is this an issue with symfony-docker or perhaps a server-side issue with golang.org?

**Comment by maxhelias** [comment]
Hello,

Yes, I think it's a issue with the golang.org server

**Comment by cdesign** [comment]
Ok thx. Any suggestion for a workaround?

**Comment by maxhelias** [comment]
This is no longer the case with the new template update, which directly uses a compiled binary: https://github.com/dunglas/symfony-docker/pull/431

Feel free to reopen it's not.
