### ISSUE TITLE
Caddyfile variables are not replaced on build

### ISSUE THREAD

**Issue by jurchiks** [dunglas/symfony-docker#428]
When I run my development build, I can see that the `/etc/caddy/Caddyfile` in the `caddy` container is still exactly the same as the one in `docker/caddy/Caddyfile`; the `{$SERVER_NAME}` is not replaced, nor is `{env.MERCURE_PUBLISHER_JWT_KEY}`, even though they are defined in the environment variables in `docker-compose.yml`:
![image](https://github.com/dunglas/symfony-docker/assets/542788/72383e4c-f638-4723-be9e-e3576a45e9ef)
Shouldn't they be replaced?

Also, why is `{$SERVER_NAME}` prefixed with `$`, but `{env.MERCURE_PUBLISHER_JWT_KEY}` - with `env.`?

**Comment by maxhelias** [comment]
> I can see that the /etc/caddy/Caddyfile in the caddy container is still exactly the same as the one in docker/caddy/Caddyfile

It's normal, it's configured here : https://github.com/dunglas/symfony-docker/blob/main/docker-compose.override.yml#L25

> the {$SERVER_NAME} is not replaced

It's also normal, caddy and especially the env var have never worked like this 

> Also, why is {$SERVER_NAME} prefixed with $, but {env.MERCURE_PUBLISHER_JWT_KEY} - with env.?

You'll find explanations in the caddy documentation here https://caddyserver.com/docs/caddyfile/concepts#environment-variables
