### ISSUE TITLE
caddy: docker build failed

### ISSUE THREAD

**Issue by ColiZei** [dunglas/symfony-docker#434]
Hello everyone.

I just downloaded this template as zip, extracted it and ran `docker compose build --pull --no-cache`.
It fails every time at with caddy "problems".

Here some screenshots.
I am using Manjaro Linux.

![image](https://github.com/dunglas/symfony-docker/assets/13164455/def9563a-5662-444e-9cb3-fe87a7a481a4)
![image](https://github.com/dunglas/symfony-docker/assets/13164455/00d2dab4-991f-4d37-a6aa-304aaaf39713)
![image](https://github.com/dunglas/symfony-docker/assets/13164455/e081c9b3-1456-47f8-ae9e-a4bb0eaec8e2)

What can i do to get this working?
Its the first time for me trying to use this docker image for symfony development.

Thanks for your help.

**Comment by warezgibzzz** [comment]
yep, having the same issue

**Comment by dunglas** [comment]
Just remove the `v2.6.4` argument to `xcaddy build`, or better, use the brand new method of downloading Caddy we use that is way faster and doesn't suffer from this issue: https://dunglas.dev/2023/08/6x-faster-docker-builds-for-symfony-and-api-platform-projects/

Fixed in #431.
