### ISSUE TITLE
New changes in Dockerfile are caching too much. 

### ISSUE THREAD

**Issue by ishu202** [dunglas/symfony-docker#437]
I noticed a change in template of Dockerfile which leads to too much caching during a docker build locally. 
out of the box it builds in 109.s 
![Screen Shot 2023-08-04 at 11 28 16 AM](https://github.com/dunglas/symfony-docker/assets/73513328/1aa52c9d-bfdf-4921-8240-787eba2d1bd2)
now look at the amount of cache it has emptied by running docker builder prune -f.
![Screen Shot 2023-08-04 at 11 29 22 AM](https://github.com/dunglas/symfony-docker/assets/73513328/9fa639b5-64b9-46a4-9829-e1de11f7202e)
I think we will need to reduce the alias and excessive COPY to from image. 
In a hurry at the moment just reporting it will try to fix later.

**Comment by maxhelias** [comment]
I don't see what is the issue here. It's not good to have cache?
For aliases, they are there precisely to optimize build time and copy they are minimized.

**Comment by ishu202** [comment]
Hey @maxhelias you are correct I periodically run `docker builder prune -f`  to clear the build contexts and caches from the docker. that day I forgot to run it before my build script. so it's a error I made I ran it today on the ideal conditions and cache is only like 50MB which is fine that's the size of my code. so you can close this one here.

**Comment by dunglas** [comment]
Thanks for the feedback!
