### ISSUE TITLE
Error with APCU

### ISSUE THREAD

**Issue by lecneri** [dunglas/symfony-docker#438]
I'm trying this project for 1st time, and I'm getting an error informing that there's no realease available for apcu package.

I'm using WSL with docker, with docker compose version 2.20.2, and I was following README in step 2
`Run docker compose build --no-cache to build fresh images`
And the error output is:
```
42.16 No releases available for package "pecl.php.net/apcu"
failed to solve: process "/bin/sh -c set -eux;     install-php-extensions \t\tapcu \t\tintl \t\topcache \t\tzip     ;" did not complete successfully: exit code: 1
```

**Comment by lecneri** [comment]
I saw that https://github.com/mlocati/docker-php-extension-installer is the one installing extensions, I've read its documentation and I modified Dockerfile in order to use specific versions, like 5.1.22, without success.

I realized that this problem it's not directed related by your docker bootstrap files, but I really don't know what to do but remove apcu from docker file, but I don't know what it may affect the project.

**Comment by maxhelias** [comment]
Hi @lecneri !
APCu is an in-memory key-value store for PHP, so there's no impact if you don't have it, but it's too bad.
This kind of error usually comes from the availability of `pecl.php.net`. Try again later.
