### ISSUE TITLE
DevPod support?

### ISSUE THREAD

**Issue by jurchiks** [dunglas/symfony-docker#440]
Is there any chance that you might include documentation on how to get this project running via DevPod?
PhpStorm does not yet support reading `vendor` files from the Docker container, but having them synced to the host machine is absolutely killing the performance; if I exclude the `vendor` folder (uncommenting the `#- /srv/app/vendor` line in `docker-compose.override.yml`), a basic `bin/console` command goes from 4-7 seconds to ~0.2-0.4 seconds.

I have not yet found a decent way to have PhpStorm get to those files, the only thing I have found is basically `build` + `up` with the `vendor` included in the mapping, then `up` again with them excluded, but that means I have to manually edit `docker-compose.override.yml` every single time, which is obviously not an acceptable solution.

I am naively hoping that something like DevPod could help with this.

**Comment by maxhelias** [comment]
We can't and don't want include documentation for every hosting solution, whether for prod or dev.
Native docker support has been a stable solution for several years now. You'll have to take care of everything you add by yourself

**Comment by jurchiks** [comment]
Well in my experience it has proven to be everything but stable. Constant issues that I didn't expect to have.
