### ISSUE TITLE
Files not fully copied on production

### ISSUE THREAD

**Issue by latysh** [dunglas/symfony-docker#444]
I am trying to use the latest changes of Symfony docker. On dev environment everything seems to be working fine, however when I run the command to launch to prod env not all files are copied. Most files are missing. 

I have been using docker and symfony for a while now. Have copied all files pretty much. Perhaps I am doing something wrong but spent a day trying to figure out the cause. 

In my example docker-compose.deploy.yml is identical to docker-compose.yml. 

![ubuntu_ip-10-102-11-182____bbm_my_wallet](https://github.com/dunglas/symfony-docker/assets/2899033/5d1bb501-ec2e-4a43-b6a4-d92a6bceea77)

What can be the issue here? Does it work for you guys in prod?

**Comment by latysh** [comment]
When I make an API call it ends in 404

**Comment by latysh** [comment]
![ubuntu_ip-10-102-11-182____bbm_my_wallet](https://github.com/dunglas/symfony-docker/assets/2899033/2a0a1b0f-add1-45cc-a86e-f88d4a5c2928)

Why the # Prod PHP image section is getting bypassed when building the image?

**Comment by dunglas** [comment]
Could you show the command you use to build the prod images please?

**Comment by latysh** [comment]
@dunglas first make build `@$(DOCKER_COMP) build --pull` then 

`SERVER_NAME=http://DOAMIN.com \
	APP_SECRET=XXX \
	CADDY_MERCURE_JWT_SECRET=XXX \
	docker compose -f docker-compose.deploy.yml -f docker-compose.prod.yml up --wait`
	
I copied the Makefile contents as well. Thanks

**Comment by latysh** [comment]
I also noticed that composer.json is not copied to container and following one is added.

`{
    "name": "symfony/skeleton",
    "type": "project",
    "license": "MIT",
    "description": "A minimal Symfony project recommended to create bare bones applications",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=8.2.8",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "symfony/console": "6.3.*",
        "symfony/dotenv": "6.3.*",
        "symfony/flex": "^2",
        "symfony/framework-bundle": "6.3.*",
        "symfony/runtime": "6.3.*",
        "symfony/yaml": "6.3.*"
    },
    "config": {
        "allow-plugins": {
            "php-http/discovery": true,
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*",
        "symfony/polyfill-php81": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "6.3.*",
            "docker": true
        }
    }
}`

**Comment by dunglas** [comment]
> `@$(DOCKER_COMP) build --pull --no-cache`

I think that it's the problem. You need to build the prod images for prod. Try this instead:

`@$(DOCKER_COMP) build --pull --no-cache -f docker-compose.yml -f docker-compose.prod.yml`

I'm pretty sure that it will fix the issue.

**Comment by thund3rb1rd78** [comment]
docker compose -f docker-compose.yml -f docker-compose.prod.yml build --pull --no-cache
But, yes, this solved it for me

**Comment by latysh** [comment]
That was the issue. Many thanks @dunglas I will send a PR to update the documentation.
