### ISSUE TITLE
launch project

### ISSUE THREAD

**Issue by med004** [dunglas/symfony-docker#45]
hello, 
I clone project in my computer but now how to launch this project !!! when I put http://localhost I have page apache2 but when I put http://localhost/name_project/web/app_dev.php I have project

**Comment by maxhelias** [comment]
This project does not have apache2, did not yet have a process that runs parallel to port 80 ?
I think your docker nginx is not started, what does this command return to you : `docker-compose ps` ?

**Comment by med004** [comment]
this is screen shot of docker-compose ps:

https://imgur.com/LcmZNhS

**Comment by maxhelias** [comment]
Your docker is stop, look at the logs and correct the various mistakes you have.
Where it is written "exit", you should have "up"
