### ISSUE TITLE
Adding new client_host value : xdebug://gateway

### ISSUE THREAD

**Issue by Hakihiro** [dunglas/symfony-docker#454]
Hi all, thanks, for your work, this is only a proposition, it's fine if it does not fit with your needs 
It seems that the `xdebug.client_host = xdebug://gateway` can be a good choice, allowing to work on more configuration and seems to allow more configuration to work.

Not well documented on the xdebug documentation, but here is the source of information I can get : 

Source : https://bugs.xdebug.org/bug_view_page.php?bug_id=00002079
And https://docs.google.com/document/d/1W-NzNtExf5C4eOu3rRQm1WlWnbW44u3ANDDA49d3FD4/edit

I can make a PR if the proposition is accepted.

Have a nice day

**Comment by maxhelias** [comment]
Hi!

Interesting, I hadn't seen that. Off course, you can submit a PR!
The configuration is here :  https://github.com/dunglas/symfony-docker/blob/main/docker/php/conf.d/app.dev.ini

Thanks!

**Comment by Hakihiro** [comment]
Sorry for the delay, the PR is ready. 
Don't hesitate if I miss something.
