### ISSUE TITLE
Issue when execute the recipes to update Docker files

### ISSUE THREAD

**Issue by chrisVdd** [dunglas/symfony-docker#456]
Hi guys,

I try to use Symfony Docker with my existing project.

I therefore follow instructions from [Installing on an Existing Project](https://github.com/dunglas/symfony-docker/blob/main/docs/existing-project.md) but things are not going so well ;-)

At the step 3:
```bash
rm symfony.lock
composer symfony:sync-recipes --force --verbose
```
It's giving me the error:
**There are no commands defined in the "symfony" namespace.** 

Assistance could be nice ;-)

Thanks!

**Comment by maxhelias** [comment]
Hi!

I think you don't have `symfony/flex` installed on your project. This command is provided by this package

**Comment by chrisVdd** [comment]
Indeed @maxhelias ;-)
