### ISSUE TITLE
Can't succed to log from Controller in file or with serverDump

### ISSUE THREAD

**Issue by Sercurio** [dunglas/symfony-docker#457]
I tried $logger->error('test'); from controller or dump($variable) but I can't find where the logs are.

**Comment by zpi12lmm** [comment]
The log files are in the container itself, for this you need to connect to your php container, for example, to output development environment logs with a single command: `docker compose exec php cat var/log/dev.log`

**Comment by Sercurio** [comment]
I can see the server logs, but when I try to log something myself, it doesn't appear

**Comment by zpi12lmm** [comment]
If you followed [this setup](https://github.com/dunglas/symfony-docker#getting-started) and received the service in [this way](https://symfony.com/doc/current/logging.html#logging-a-message), then the logs should appear both in the Symfony Profiler and in the log file.

**Comment by Sercurio** [comment]
![image](https://github.com/dunglas/symfony-docker/assets/38528193/8fc9015c-077c-450e-96ee-37c2d7248824)

Here we can see I have made a call from chrome to the /api/login route and get a 401 but YOLOOOO is not printed

**Comment by Sercurio** [comment]
![image](https://github.com/dunglas/symfony-docker/assets/38528193/e713aa9f-47a3-4bce-94be-3e91cabf186e)

Sorry, I call the same route with the command `docker compose exec app tail -f var/log/dev.log`

But cannot see my YOLOOOOO

**Comment by Sercurio** [comment]
No, why ?

**Comment by zpi12lmm** [comment]
All right (I just wanted to be sure), try to rebuild the project, but first stop all containers and delete the `var` folder in the root of the project, it should help.

**Comment by Sercurio** [comment]
What I have do:
- docker compose down --remove-orphans
- docker system prune -a -f
- docker compose up --pull --wait
- docker compose exec app tail -f var/log/dev.log

It's weird

**Comment by maxhelias** [comment]
Please keep this board for project-related issues. You're dealing with a usability issue, not a bug.
