### ISSUE TITLE
Container caddy is unhealthy

### ISSUE THREAD

**Issue by em411** [dunglas/symfony-docker#465]
Hi,
Current Caddy Healthcheck configuration does not work with `SERVER_NAME` environment variable.

We should replace `localhost` with `SERVER_NAME` or with the default service name - `caddy`.

https://github.com/dunglas/symfony-docker/blob/253eae0e158ea3c94d66b719824e78a20620fa6b/Dockerfile#L114

I can create PR when we decide which option is more suitable.

**Comment by dunglas** [comment]
Good catch. Using the default service name looks more reliable to me. WDYT?

**Comment by dunglas** [comment]
We can even use the admin endpoint: https://github.com/api-platform/api-platform/pull/2518
