### ISSUE TITLE
Template twig error in production with FrankenPHP support

### ISSUE THREAD

**Issue by zpi12lmm** [dunglas/symfony-docker#474]
After updating the project with FrankenPHP support, I got an error in production, I tried to reproduce it in the development environment, but in this case everything works without problems, here is the error detected from the logs:

`{
    "message": "Uncaught PHP Exception TypeError: \"Twig\\Environment::getTemplateClass(): Argument #1 ($name) must be of type string, null given, called in /app/vendor/twig/twig/src/Template.php on line 319\" at /app/vendor/twig/twig/src/Environment.php line 262",
    "context": {
        "exception": {
            "class": "TypeError",
            "message": "Twig\\Environment::getTemplateClass(): Argument #1 ($name) must be of type string, null given, called in /app/vendor/twig/twig/src/Template.php on line 319",
            "code": 0,
            "file": "/app/vendor/twig/twig/src/Environment.php:262"
        }
    },
    "level": 500,
    "level_name": "CRITICAL",
    "channel": "request",
    "datetime": "2023-09-28T13:11:19.762885+00:00",
    "extra": {}
}`

Maybe this will help, I have a dashboard on my site, I'm using EasyAdmin and after successful authentication I get this error, but no errors on the public user pages, I didn't have this problem before the update.

**Comment by dunglas** [comment]
Nothing else relevant in the logs? As we already had some errors related to Alpine, could you try if the problem also exists with the Debian variant please?

**Comment by zpi12lmm** [comment]
Here are all the logs for the page where this error occurs:

`[
    {
        "request": {
            "remote_ip": "XXX.XXX.XXX.XXX",
            "remote_port": "55370",
            "client_ip": "XXX.XXX.XXX.XXX",
            "proto": "HTTP/3.0",
            "method": "POST",
            "host": "example.com",
            "uri": "/login",
            "headers": {
                "Accept": [
                    "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
                ],
                "Cache-Control": [
                    "max-age=0"
                ],
                "Sec-Ch-Ua-Platform": [
                    "\"macOS\""
                ],
                "Upgrade-Insecure-Requests": [
                    "1"
                ],
                "Origin": [
                    "https://example.com"
                ],
                "Sec-Fetch-Mode": [
                    "navigate"
                ],
                "Sec-Fetch-User": [
                    "?1"
                ],
                "Accept-Language": [
                    "uk-UA,uk;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6"
                ],
                "Sec-Ch-Ua": [
                    "\"Google Chrome\";v=\"117\", \"Not;A=Brand\";v=\"8\", \"Chromium\";v=\"117\""
                ],
                "Content-Type": [
                    "application/x-www-form-urlencoded"
                ],
                "Sec-Fetch-Dest": [
                    "document"
                ],
                "Referer": [
                    "https://example.com/login"
                ],
                "Cookie": [],
                "Content-Length": [
                    "184"
                ],
                "Sec-Ch-Ua-Mobile": [
                    "?0"
                ],
                "User-Agent": [
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
                ],
                "Sec-Fetch-Site": [
                    "same-origin"
                ],
                "Accept-Encoding": [
                    "gzip, deflate, br"
                ]
            },
            "tls": {
                "resumed": true,
                "version": 772,
                "cipher_suite": 4865,
                "proto": "h3",
                "server_name": "example.com"
            }
        },
        "bytes_read": 184,
        "user_id": "",
        "duration": 0.502832547,
        "size": 382,
        "status": 302,
        "resp_headers": {
            "Content-Type": [
                "text/html; charset=UTF-8"
            ],
            "Expires": [
                "Thu, 28 Sep 2023 19:21:21 GMT"
            ],
            "Set-Cookie": [],
            "Server": [
                "Caddy"
            ],
            "Cache-Control": [
                "max-age=0, must-revalidate, private"
            ],
            "Date": [
                "Thu, 28 Sep 2023 19:21:21 GMT"
            ],
            "Location": [
                "https://example.com/dashboard"
            ]
        }
    },
    {
        "message": "Matched route \"app_dashboard\".",
        "context": {
            "route": "app_dashboard",
            "route_parameters": {
                "_route": "app_dashboard",
                "_controller": "App\\Controller\\Admin\\DashboardController::index"
            },
            "request_uri": "https://example.com/dashboard",
            "method": "GET"
        },
        "level": 200,
        "level_name": "INFO",
        "channel": "request",
        "datetime": "2023-09-28T19:21:21.392689+00:00",
        "extra": {}
    },
    {
        "message": "Checking for authenticator support.",
        "context": {
            "firewall_name": "main",
            "authenticators": 1
        },
        "level": 100,
        "level_name": "DEBUG",
        "channel": "security",
        "datetime": "2023-09-28T19:21:21.392781+00:00",
        "extra": {}
    },
    {
        "message": "Checking support on authenticator.",
        "context": {
            "firewall_name": "main",
            "authenticator": "App\\Security\\AppAuthenticator"
        },
        "level": 100,
        "level_name": "DEBUG",
        "channel": "security",
        "datetime": "2023-09-28T19:21:21.392788+00:00",
        "extra": {}
    },
    {
        "message": "Authenticator does not support the request.",
        "context": {
            "firewall_name": "main",
            "authenticator": "App\\Security\\AppAuthenticator"
        },
        "level": 100,
        "level_name": "DEBUG",
        "channel": "security",
        "datetime": "2023-09-28T19:21:21.392795+00:00",
        "extra": {}
    },
    {
        "message": "Read existing security token from the session.",
        "context": {
            "key": "_security_main",
            "token_class": "Symfony\\Component\\Security\\Http\\Authenticator\\Token\\PostAuthenticationToken"
        },
        "level": 100,
        "level_name": "DEBUG",
        "channel": "security",
        "datetime": "2023-09-28T19:21:21.393044+00:00",
        "extra": {}
    },
    {
        "message": "User was reloaded from a user provider.",
        "context": {
            "provider": "Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider",
            "username": "admin"
        },
        "level": 100,
        "level_name": "DEBUG",
        "channel": "security",
        "datetime": "2023-09-28T19:21:21.393969+00:00",
        "extra": {}
    },
    {
        "message": "Uncaught PHP Exception TypeError: \"Twig\\Environment::getTemplateClass(): Argument #1 ($name) must be of type string, null given, called in /app/vendor/twig/twig/src/Template.php on line 319\" at /app/vendor/twig/twig/src/Environment.php line 262",
        "context": {
            "exception": {
                "class": "TypeError",
                "message": "Twig\\Environment::getTemplateClass(): Argument #1 ($name) must be of type string, null given, called in /app/vendor/twig/twig/src/Template.php on line 319",
                "code": 0,
                "file": "/app/vendor/twig/twig/src/Environment.php:262"
            }
        },
        "level": 500,
        "level_name": "CRITICAL",
        "channel": "request",
        "datetime": "2023-09-28T19:21:21.402629+00:00",
        "extra": {}
    },
    {
        "message": "Stored the security token in the session.",
        "context": {
            "key": "_security_main"
        },
        "level": 100,
        "level_name": "DEBUG",
        "channel": "security",
        "datetime": "2023-09-28T19:21:21.406748+00:00",
        "extra": {}
    },
    {
        "request": {
            "remote_ip": "XXX.XXX.XXX.XXX",
            "remote_port": "55370",
            "client_ip": "XXX.XXX.XXX.XXX",
            "proto": "HTTP/3.0",
            "method": "GET",
            "host": "example.com",
            "uri": "/dashboard",
            "headers": {
                "Cache-Control": [
                    "max-age=0"
                ],
                "Accept": [
                    "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
                ],
                "Referer": [
                    "https://example.com/login"
                ],
                "Accept-Encoding": [
                    "gzip, deflate, br"
                ],
                "Sec-Ch-Ua": [
                    "\"Google Chrome\";v=\"117\", \"Not;A=Brand\";v=\"8\", \"Chromium\";v=\"117\""
                ],
                "Sec-Ch-Ua-Platform": [
                    "\"macOS\""
                ],
                "Accept-Language": [
                    "uk-UA,uk;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6"
                ],
                "Cookie": [],
                "Sec-Ch-Ua-Mobile": [
                    "?0"
                ],
                "Upgrade-Insecure-Requests": [
                    "1"
                ],
                "User-Agent": [
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
                ],
                "Sec-Fetch-Site": [
                    "same-origin"
                ],
                "Sec-Fetch-User": [
                    "?1"
                ],
                "Sec-Fetch-Dest": [
                    "document"
                ],
                "Sec-Fetch-Mode": [
                    "navigate"
                ]
            },
            "tls": {
                "resumed": true,
                "version": 772,
                "cipher_suite": 4865,
                "proto": "h3",
                "server_name": "example.com"
            }
        },
        "bytes_read": 0,
        "user_id": "",
        "duration": 0.015919698,
        "size": 1015,
        "status": 500,
        "resp_headers": {
            "Server": [
                "Caddy"
            ],
            "Content-Type": [
                "text/html; charset=UTF-8"
            ],
            "Vary": [
                "Accept"
            ],
            "Cache-Control": [
                "max-age=0, must-revalidate, private"
            ],
            "Date": [
                "Thu, 28 Sep 2023 19:21:21 GMT"
            ],
            "Expires": [
                "Thu, 28 Sep 2023 19:21:21 GMT"
            ]
        }
    }
]`

How can I try the Debian variant, there is already a custom FrankenPHP image for that?

**Comment by dunglas** [comment]
> How can I try the Debian variant, there is already a custom FrankenPHP image for that?

Yes, the default image uses Debian. You can revert these changes: https://github.com/api-platform/api-platform/commit/54437891732786f237ea3334e6d11993cebd1a0f

**Comment by zpi12lmm** [comment]
I tried to test the Debian-based build, but there was also a problem, and most interestingly, also when I tried to run in production mode, but a different type of error:

`
maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
{"level":"info","ts":1695953298.4908578,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Error: adapting config using caddyfile: parsing caddyfile tokens for 'frankenphp': /etc/caddy/worker.Caddyfile:1 - Error during parsing: Wrong argument count or unexpected line ending after 'worker', import chain: ['/etc/caddy/Caddyfile:5 (import)']
`

As I understood, the error occurs when importing the worker for FrankenPHP, so I decided to try to manually move its config to the Caddyfile, and I commented the FRANKENPHP_CONFIG environment variable in the Dockerfile, but this did not solve anything, the error still remained, the difference was only in this place: `...import chain: ['']`

**Comment by dunglas** [comment]
It looks like you have an old version of FrankenPHP. Can you try `docker pull dunglas/frankenphp` to see if it finds a newer image?

**Comment by zpi12lmm** [comment]
> It looks like you have an old version of FrankenPHP. Can you try `docker pull dunglas/frankenphp` to see if it finds a newer image?

Yeah, that was the problem, but previously I used to run with the --pull option and it worked...🤔

Anyway, I ran the project in a Debian-based production environment: immediately after authentication I can get to the dashboard page, even some more internal pages, but one of them shows the same error again, if I refresh the error page a few times, it disappears and I can go to another page, but the funny thing is that this error somehow wreaks havoc because when I try to go to a certain page I actually go to a completely different page and when I refresh it goes to a random page and the same error pops up every now and then.

**Comment by dunglas** [comment]
Is the worker mode on? If yes, is the problem persisting when disabling it?

Also, could I get access to your repository to try debugging?

**Comment by zpi12lmm** [comment]
Yes, that's a good idea, because I'm not sure if I'm describing my problem clearly, and if you don't mind, I'd really appreciate it!
I've already pushed the changes to a separate branch for you to work on. Now I am writing from my personal account, so I will provide access from another account. I should give access for this account @dunglas, right?

**Comment by dunglas** [comment]
@zpi12lmm if the project is hosted on a public forge like GitHub or GitLab, you can invite me to the project, my username is "dunglas" on both.

**Comment by zpi12lmm** [comment]
I have a private repository on GitHub, but I can give access to it!

**Comment by zpi12lmm** [comment]
I sent you an invitation, this project will be about food recipes.

**Comment by tdumalin** [comment]
@dunglas ,

Thanks for your comment i wasn't sure that the performance are really impacted, can you help for the "good way" of disabling worker mode and logging ?
Here's how I disabled the worker:

```Dockerfile
#...
FROM frankenphp_base AS frankenphp_prod

ENV APP_ENV=prod
# Comment this line
#ENV FRANKENPHP_CONFIG="import worker.Caddyfile"
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

COPY --link frankenphp/conf.d/app.prod.ini $PHP_INI_DIR/conf.d/
# Comment this line
#COPY --link frankenphp/worker.Caddyfile /etc/caddy/worker.Caddyfile
# ...
```

**Comment by latysh** [comment]
> @dunglas ,
> 
> Thanks for your comment i wasn't sure that the performance are really impacted, can you help for the "good way" of disabling worker mode and logging ? Here's how I disabled the worker:
> 
> ```dockerfile
> #...
> FROM frankenphp_base AS frankenphp_prod
> 
> ENV APP_ENV=prod
> # Comment this line
> #ENV FRANKENPHP_CONFIG="import worker.Caddyfile"
> RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
> 
> COPY --link frankenphp/conf.d/app.prod.ini $PHP_INI_DIR/conf.d/
> # Comment this line
> #COPY --link frankenphp/worker.Caddyfile /etc/caddy/worker.Caddyfile
> # ...
> ```

https://github.com/dunglas/symfony-docker/blob/main/docs/production.md

The worker mode of FrankenPHP is enabled by default in prod. To disabled it, add the env var FRANKENPHP_CONFIG as empty to the compose.prod.yaml file.

**Comment by KDederichs** [comment]
Yeah I'm seeing the same issue with EA Twig templates and activated worker mode, with the newest version of Frankenphp

**Comment by pentiminax** [comment]
Same issue with worker mode enabled and EasyAdminBundle v4.9.1

**Comment by dunglas** [comment]
This should likely be fixed in EasyAdmin.

**Comment by KDederichs** [comment]
I got a PR there that probably should fix it, so maybe keep an eye on that :)
