### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by Razumov-Sergey** [dunglas/symfony-docker#480]
How to choose a specific php version?

**Comment by 7-zete-7** [comment]
Hello, @Razumov-Sergey

You can change PHP verion by next Dockerfile change:
```diff
-FROM dunglas/frankenphp:latest-alpine AS frankenphp_upstream
+FROM dunglas/frankenphp:latest-php8.2-alpine AS frankenphp_upstream
```

All possible PHP versions of the `dunglas/frankenphp` Docker image you can see at [this URL](https://hub.docker.com/r/dunglas/frankenphp/tags?page=1&name=latest-php%25-alpine).
