### ISSUE TITLE
[PROD] 500 errors after ~30sec

### ISSUE THREAD

**Issue by dridbae** [dunglas/symfony-docker#484]
Hello,

I am encountering an issue trying to deploy the docker in production, during ~30 sec the application is well responding but after that I only get 500 errors.

No logs on symfony side, I incresed the log level of caddy but the only message I get is this : 

alicia-php-1       | {"level":"debug","ts":1697216308.1943603,"msg":"request handling started","worker":"/app/public/index.php","url":"/index.php"}
alicia-php-1       | {"level":"debug","ts":1697216308.1991875,"logger":"http.handlers.php","msg":"request handling finished","url":"/index.php"}
alicia-php-1       | {"level":"debug","ts":1697216308.1992655,"logger":"http.handlers.php","msg":"request handling finished","url":"/index.php"}
alicia-php-1       | {"level":"debug","ts":1697216308.1993122,"msg":"waiting for request","worker":"/app/public/index.php"}
alicia-php-1       | 2023/10/13 16:58:28.199	ERROR	http.log.access.log0	handled request	{"request": {"remote_ip": "XXX", "remote_port": "49515", "client_ip": "XXX", "proto": "HTTP/3.0", "method": "GET", "host": "XXX", "uri": "/login", "headers": {"Sec-Fetch-Dest": ["document"], "Cookie": [], "Cache-Control": ["max-age=0"], "User-Agent": ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"], "Sec-Fetch-Site": ["none"], "Sec-Fetch-Mode": ["navigate"], "Upgrade-Insecure-Requests": ["1"], "Sec-Ch-Ua-Mobile": ["?0"], "Sec-Ch-Ua-Platform": ["\"Windows\""], "Accept-Encoding": ["gzip, deflate, br"], "Sec-Ch-Ua": ["\"Chromium\";v=\"118\", \"Google Chrome\";v=\"118\", \"Not=A?Brand\";v=\"99\""], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"], "Sec-Fetch-User": ["?1"], "Accept-Language": ["fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h3", "server_name": "alicia.techgo.fr"}}, "bytes_read": 0, "user_id": "", "duration": 0.005378555, "size": 841, "status": 500, "resp_headers": {"Server": ["Caddy"], "Content-Type": ["text/html; charset=UTF-8"], "Vary": ["Accept"], "Cache-Control": ["no-cache, private"], "Date": ["Fri, 13 Oct 2023 16:58:28 GMT"]}}

I used the docker files as they come and launch the docker using : 

SERVER_NAME=XXX \
APP_SECRET=XXX \
CADDY_MERCURE_JWT_SECRET=XXX \
docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --wait

Anyone encountered the same issue or have an idea ?

Tjhank you for your help.

**Comment by dunglas** [comment]
Could you please try if disabling the worker mode helps (to do so, you can comment this line: https://github.com/dunglas/symfony-docker/blob/main/Dockerfile#L74)?

**Comment by dridbae** [comment]
> Could you please try if disabling the worker mode helps (to do so, you can comment this line: https://github.com/dunglas/symfony-docker/blob/main/Dockerfile#L74)?

Thank you @dunglas it seems to have solve the problem in production env !

Do you know what could be the problem and if an update is needed in order to enable worker mode in production ?

Thank you again for your help !

**Comment by dunglas** [comment]
Could you copy the 500 error? You should have the details in `var/log/`. Are you using Doctrine? If yes this can be related to https://github.com/symfony/symfony/issues/51661, but it's hard to say without the details.

**Comment by dridbae** [comment]
Yes I am using doctrine but no logs in. var/log when the error occurs. The only log I had was the docker compose logs I pasted in my first message.

I will follow the subject.

But for this issue your solution solved the issue. Thank you again.

**Comment by dunglas** [comment]
That would be nice to find and fix the issue (the worker mode improves performance).
