### ISSUE TITLE
Best Way to adjust php.ini

### ISSUE THREAD

**Issue by fungus75** [dunglas/symfony-docker#488]
I really like your work. Great. Works like a charm.

But I want to create some kind of file-upload-service and therefore I have to adjust (at least) the upload_max_filesize parameter of php.ini.

What is the best way to adjust it?
I'm thinking of doing something that would be stored in git-repo so that it would be applied automatically as soon as I implement it on a new docker-clone (lets say: git-clone)

**Comment by dunglas** [comment]
Thanks for the kind words!
Change `frankenphp/conf.d/app.ini` directly.
