### ISSUE TITLE
Best way to host multiple sites on the same server

### ISSUE THREAD

**Issue by treztreiz** [dunglas/symfony-docker#493]
I've been using this template for several projects and I can't stop using it now, thank you so much for your great work.
I made a website for a customer using this dockerized environment, but they want me to host a new website on the same server as the first one (both sites should use https).

What is the best way to handle this situation ? I can't start both projects with the same configuration, as the port 443 is already allocated by the first container.

Can anyone point me in the right direction?

Thanks :)

**Comment by konrado** [comment]
@treztreiz it's just an idea. Let's say that your new project is stored in `/var/www/html/other` directory, so you could use volume to attach it to that container and add configuration for Caddy to handle it, such as:
```
php:
    image: ${IMAGES_PREFIX:-}app-php
    volumes:
        - /var/www/html/other:/other
    environment:
      CADDY_EXTRA_CONFIG: |
        # handle additional domains
        other.example.com {
            root /other/public/
            // additional configuration
        }
```

**Comment by maxhelias** [comment]
You can add a new host as we have done here : https://github.com/dunglas/symfony-docker/blob/main/frankenphp/Caddyfile#L16-L53
