### ISSUE TITLE
`APP_ENV=prod` doesn't seem to work properly

### ISSUE THREAD

**Issue by adriengivry** [dunglas/symfony-docker#496]
Hi there!

I cloned this repository and changed `APP_ENV=dev` to `APP_ENV=prod` in the `.env` file, then ran docker with:
```bash
docker compose up -d
```

I created a simple symfony controller returning:
```php
return new Response($_ENV['APP_ENV']);
```

And the response I get is "dev", no matter what `APP_ENV` I set.

I tried it on another project, same issue.

Am I missing something?

**Comment by dunglas** [comment]
Can you try this: `docker compose -f compose.prod.yaml -f compose.yaml up`? (https://github.com/dunglas/symfony-docker/blob/main/docs/production.md)

Or at least `docker compose -e APP_ENV=prod up`

**Comment by adriengivry** [comment]
`docker compose -e APP_ENV=prod up` isn't a valid command (`unknown shorthand flag: 'e' in -e`).

I tried `APP_ENV=prod docker compose up -d`, but same, the response is "dev".

With `docker compose -f compose.prod.yaml -f compose.yaml up`, I can't seem to see my controller anymore, I only get the phpinfo page, no matter the route I use.

This is from a freshly cloned repository, haven't changed any setting apart from `APP_ENV=prod`

**Comment by dunglas** [comment]
For the first command, you need to run `docker compose -f compose.prod.yaml -f compose.yaml build` before.

For the second one, it's `APP_ENV=prod docker compose up`, sorry.

**Comment by adriengivry** [comment]
Ok, so it looks like it's working with:

```bash
docker compose -f compose.prod.yaml -f compose.yaml build --no-cache
docker compose -f compose.prod.yaml -f compose.yaml up
```
_Effectively builds and run the app in production mode_

What I noted is:
- The `--no-cache` option is necessary if you already have images built for `dev` but need to deploy for `prod`.
- `APP_ENV` value in `.env` (`dev` or `prod`) , doesn't matter at all.
  - Building with `compose.prod.yaml` + `compose.yaml` will result into `APP_ENV=prod`
  - Building with `compose.yaml` only will result into `APP_ENV=dev`


Some recommendations:
- Being a complete Docker beginner, this is pretty confusing, a lot of people might assume changing the `APP_ENV` value would have an impact on their environment mode.
- I would update `production.md` to mention the need to rebuild images when switching from `dev` to `prod`.
- Maybe we could mention the fact that `APP_ENV` doesn't do anything, as the environment mode is ultimately controlled by the `compose*.yml` files used.

**Comment by dunglas** [comment]
Docs improvements are very welcome!

Also, we should allow overriding `APP_ENV` by adding something like `APP_ENV=${APP_ENV:-dev}` in `compose.override.yaml` to ease changing locally the environment.

**Comment by adriengivry** [comment]
Great idea. I can't seem to understand where the `APP_ENV` is ultimately set/override. There is no reference to `APP_ENV` in the whole filesystem outside of `.env`

**Comment by dunglas** [comment]
Directly in the `Dockerfile`: https://github.com/dunglas/symfony-docker/blob/main/Dockerfile#L56-L73

**Comment by adriengivry** [comment]
Got it! Yeah it would be nice if `APP_ENV` in `.env` could have the last word.

**Comment by dunglas** [comment]
I don't think that's possible. By definition values in `.env` are only used if they aren't defined in the environnement.

However, we could allow the user changing the variable in the environment by allowing to override `APP_ENV` in the `environment` section of the PHP service in `compose.override.yaml`, so `APP_ENV=prod docker compose up` will work.

**Comment by adriengivry** [comment]
Yep I think that would make a lot of sense
