### ISSUE TITLE
Have to clear Cookies and Cache in Chrome for localhost everytime i use another container

### ISSUE THREAD

**Issue by thomas-hofmann** [dunglas/symfony-docker#503]
Hi guys can someone help me. 

Everytime i am working with this project it destroys the localhost and i am getting a "ERR_CONNECTION_REFUSED" on localhost when i run other projects. 

I can only fix it when i delete all my cookies and cache in chrome. 

It will work in incoginto mode and in other browsers or a different chrome profile.

Can someone give me a hint how to fix this? :(

**Comment by maxhelias** [comment]
Hi!

I think the problem comes from the domain name "localhost" which is shared between your projects. Use domain names and that should fix it : https://github.com/dunglas/symfony-docker/blob/main/docs/build.md#customizing-the-server-name
