### ISSUE TITLE
failed with local cert 

### ISSUE THREAD

**Issue by treeindark** [dunglas/symfony-docker#504]
Hello,
I would use with local tls, then I do doc TLS

makecert for server_name betle.test
mkcert -cert-file frankenphp/certs/tls.pem -key-file frankenphp/certs/tls.key "betle.test"

 
SERVER_NAME=betle.test docker compose up --pull -d --wait
 ✔ Container symfony-docker-php-1  Started                                                                                                                                                         0.1s 
container symfony-docker-php-1 is unhealthy

log:
`2023/11/07 13:37:31.433 INFO    using provided configuration    {"config_file": "/etc/caddy/Caddyfile", "config_adapter": ""}
Error: adapting config using caddyfile: /etc/caddy/Caddyfile:16: unrecognized directive: betelgeuse.test,
Did you mean to define a second site? If so, you must use curly braces around each site to separate their configurations.`

**Comment by beejaz** [comment]
How is your Caddyfile looking on line 16? Seems you have added something called `betelgeuse.test` on line 16?

**Comment by treeindark** [comment]
no change:
{                                                                                                 
        {$CADDY_GLOBAL_OPTIONS}                                                                   
                                                                                                  
        frankenphp {                                                                              
                {$FRANKENPHP_CONFIG}                                                              
        }                                                                                         
                                                                                                  
        # https://caddyserver.com/docs/caddyfile/directives#sorting-algorithm                     
        order mercure after encode                                                                
        order vulcain after reverse_proxy                                                         
        order php_server before file_server                                                       
}                                                                                                 
                                                                                                  
{$CADDY_EXTRA_CONFIG}                                                                             
                                                                                                  
{$SERVER_NAME:localhost} {                                                                        
        log {                                                                                     
                # Redact the authorization query parameter that can be set by Mercure             
                format filter {                                                                   
                        wrap console                                                              
                        fields {                                                                  
                                uri query {                                                       
                                        replace authorization REDACTED                            
                                }                                                                 
                        }                                                                         
                }                                                                                 
        }                                                                                         
...

**Comment by jimmyMorizot** [comment]
Bonjour, j'ai un problème similaire j'ai suivi les étapes avec mkcert : https://github.com/dunglas/symfony-docker/blob/main/docs/tls.md . Mais je pense que je configure mal mon Caddyfile. En fait, j'aimerais configurer mon Caddyfile pour servir plusieurs sous domaines. Je m'explique, je fais actuellemennt un CRM pour une marque de voiture sans permis et ce CRM sera utilisé dans environ 250 concessions. Donc actuellement, je fais les api avec Symfony, api platform et j'utilise ce référentiel pour la configuration Docker. Pour le développement j'ai 3 sous domaine qui sont : 
- https://master.prestov3.local/
- https://aixam1.prestov3.local/api
- https://aixam2.prestov3.local/api

Mon Caddyfile : 
`{
	{$CADDY_GLOBAL_OPTIONS}

	frankenphp {
		{$FRANKENPHP_CONFIG}
	}

	# https://caddyserver.com/docs/caddyfile/directives#sorting-algorithm
	order mercure after encode
	order vulcain after reverse_proxy
	order php_server before file_server
}

{$CADDY_EXTRA_CONFIG}

*.prestov3.local {
	log {
		format filter {
			wrap console
			fields {
				uri query {
					replace authorization REDACTED
				}
			}
		}
	}

	root * /app/public
	encode zstd gzip

	mercure {
		# Transport to use (default to Bolt)
		transport_url {$MERCURE_TRANSPORT_URL:bolt:///data/mercure.db}
		# Publisher JWT key
		publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
		# Subscriber JWT key
		subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
		# Allow anonymous subscribers (double-check that it's what you want)
		anonymous
		# Enable the subscription API (double-check that it's what you want)
		subscriptions
		# Extra directives
		{$MERCURE_EXTRA_DIRECTIVES}
	}

	vulcain

	# Disable Topics tracking if not enabled explicitly: https://github.com/jkarlin/topics
	header ?Permissions-Policy "browsing-topics=()"

	php_server
}
`
L'erreur dans ma pipeline ci.yml : 
![Capture d’écran du 2023-11-09 09-52-17](https://github.com/dunglas/symfony-docker/assets/106068855/e04985ce-b51f-4f50-8134-c862cb6fc355)

Un petit coup de main serais la bienvenu, c'est la première fois que j'utilise Caddy et Docker !

**Comment by beejaz** [comment]
> no change:
> 
> ```
> {                                                                                                 
>         {$CADDY_GLOBAL_OPTIONS}                                                                   
>                                                                                                   
>         frankenphp {                                                                              
>                 {$FRANKENPHP_CONFIG}                                                              
>         }                                                                                         
>                                                                                                   
>         # https://caddyserver.com/docs/caddyfile/directives#sorting-algorithm                     
>         order mercure after encode                                                                
>         order vulcain after reverse_proxy                                                         
>         order php_server before file_server                                                       
> }                                                                                                 
>                                                                                                   
> {$CADDY_EXTRA_CONFIG}                                                                             
>                                                                                                   
> {$SERVER_NAME:localhost} {                    <<< line 16                                                    
>         log {                                                                                     
>                 # Redact the authorization query parameter that can be set by Mercure             
>                 format filter {                                                                   
>                         wrap console                                                              
>                         fields {                                                                  
>                                 uri query {                                                       
>                                         replace authorization REDACTED                            
>                                 }                                                                 
>                         }                                                                         
>                 }                                                                                 
>         }                                                                                         
> ...                
> ```

Line 16 says it should use environment variable SERVER_NAME which it says is defined as `betelgeuse.test` even tho you try to use `SERVER_NAME=betle.test ` in command line run command. Have you maybe added some text to your SERVER_NAME variable in `compose.yaml` line 6 ?

**Comment by jimmyMorizot** [comment]
> > pas de changement:
> > ```
> > {                                                                                                 
> >         {$CADDY_GLOBAL_OPTIONS}                                                                   
> >                                                                                                   
> >         frankenphp {                                                                              
> >                 {$FRANKENPHP_CONFIG}                                                              
> >         }                                                                                         
> >                                                                                                   
> >         # https://caddyserver.com/docs/caddyfile/directives#sorting-algorithm                     
> >         order mercure after encode                                                                
> >         order vulcain after reverse_proxy                                                         
> >         order php_server before file_server                                                       
> > }                                                                                                 
> >                                                                                                   
> > {$CADDY_EXTRA_CONFIG}                                                                             
> >                                                                                                   
> > {$SERVER_NAME:localhost} {                    <<< line 16                                                    
> >         log {                                                                                     
> >                 # Redact the authorization query parameter that can be set by Mercure             
> >                 format filter {                                                                   
> >                         wrap console                                                              
> >                         fields {                                                                  
> >                                 uri query {                                                       
> >                                         replace authorization REDACTED                            
> >                                 }                                                                 
> >                         }                                                                         
> >                 }                                                                                 
> >         }                                                                                         
> > ...                
> > ```
> 
> La ligne 16 indique qu'elle doit utiliser la variable d'environnement SERVER_NAME qui, selon elle, est définie comme `betelgeuse.test`même si vous essayez d'utiliser `SERVER_NAME=betle.test `la commande d'exécution en ligne de commande. Avez-vous peut-être ajouté du texte à votre variable SERVER_NAME à la `compose.yaml`ligne 6 ?

No, I haven't touched the basic configuration of compose.yml :
```
`version: "3.4"

services:
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      PHP_MEMORY_LIMIT: 8G
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|php$$`
```
Caddyfile :

```
{
	{$CADDY_GLOBAL_OPTIONS}

	frankenphp {
		{$FRANKENPHP_CONFIG}
	}

	# https://caddyserver.com/docs/caddyfile/directives#sorting-algorithm
	order mercure after encode
	order vulcain after reverse_proxy
	order php_server before file_server
}

{$CADDY_EXTRA_CONFIG}

*.prestov3.local {
	log {
		format filter {
			wrap console
			fields {
				uri query {
					replace authorization REDACTED
				}
			}
		}
	}

	root * /app/public
	encode zstd gzip

	mercure {
		# Transport to use (default to Bolt)
		transport_url {$MERCURE_TRANSPORT_URL:bolt:///data/mercure.db}
		# Publisher JWT key
		publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
		# Subscriber JWT key
		subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
		# Allow anonymous subscribers (double-check that it's what you want)
		anonymous
		# Enable the subscription API (double-check that it's what you want)
		subscriptions
		# Extra directives
		{$MERCURE_EXTRA_DIRECTIVES}
	}

	vulcain

	# Disable Topics tracking if not enabled explicitly: https://github.com/jkarlin/topics
	header ?Permissions-Policy "browsing-topics=()"

	php_server
}
```

**Comment by eldr0n** [comment]
It works when you put {$CADDY_EXTRA_CONFIG} inside the site block.
```
{$SERVER_NAME:localhost} {

	{$CADDY_EXTRA_CONFIG}
         
        ...
}
```
