### ISSUE TITLE
Mac M1 dev build failed

### ISSUE THREAD

**Issue by jonatanpolak** [dunglas/symfony-docker#508]
Environment:
- mac M1
- sonoma 14.1.1
- brew
- docker 24.0.6 build ed223bc

Steps:
1. clone https://github.com/dunglas/symfony-docker
2. docker compose build --no-cache

Log:
https://app.warp.dev/block/47PEquX7iqlQP8DjI8M7rp

Solution: (worked for me)
- Edit the Dockerfile
- Add `build-base` to the frankenphp_dev section :
```
        [...]
        RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
        
	RUN apk add --no-cache \
		build-base \
	;
```

**Comment by maxhelias** [comment]
I'm not able to reproduce your issue. I don't see what `build-base` brings in the stack. It seems to be more of a network issue during setup.
