### ISSUE TITLE
Issue with file compose.yml error

### ISSUE THREAD

**Issue by jitterbux** [dunglas/symfony-docker#510]
When I try to run this command: 

```
SERVER_NAME=mysuperblog.xyz \
APP_SECRET=passpass \
CADDY_MERCURE_JWT_SECRET=passpass \
docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --wait
```

I am getting this error:

```
stat /root/symfony-docker/compose.yml: no such file or directory
```

But when I do `ls` I see this:

```
Dockerfile  README.md  compose.override.yaml  compose.prod.yaml  compose.yaml  docs  frankenphp  public
```

I am running it as a root. 

Why it's not running?

**Comment by stefantalen** [comment]
Your file name references are wrong (docker-compose instead of compose)

Try this: 

``` 
SERVER_NAME=mysuperblog.xyz \
APP_SECRET=passpass \
CADDY_MERCURE_JWT_SECRET=passpass \
docker compose -f compose.yaml -f compose.prod.yaml up -d --wait
```

**Comment by jitterbux** [comment]
Yeah, I noticed that it will probably that. But the docs are not right, look, I made a screenshot:

<img width="1143" alt="Screenshot 2023-11-19 at 22 50 22" src="https://github.com/dunglas/symfony-docker/assets/102470544/9a9b5b78-4634-4870-a432-08a160936d8a">

There is even docker-compose instead of just compose as is the name when you clone the repository.

**Comment by stefantalen** [comment]
It was recently changed: https://github.com/dunglas/symfony-docker/pull/494

Looks like the docs were forgotten.🙂

**Comment by dunglas** [comment]
Oops, PR welcome!

**Comment by jitterbux** [comment]
Could you do it yourself, please. I can barely use the GUI on GitHub right now ;). Thanks in advance.
