### ISSUE TITLE
Env variables can no longer be defined

### ISSUE THREAD

**Issue by akwawa** [dunglas/symfony-docker#514]
Hello,

With the new version of frankenphp and worker.Caddyfile, env variables can no longer be defined.

If you want to reproduce the bug :
1. Clone the project
2. Add an "env" line to worker.Caddyfile (e.g.: env REMOTE_USER myUser@domain.local)
3. Build and Start with docker-compose (as in the docs)
4. Add symfony/profiler-pack and navigate to https://localhost/_profiler/phpinfo

The variable is not defined.

So, what have I done wrong ?
I need to use symfony with the "REMOTE_USER" auhenticator but I can't define a variable in the worker.

I know there is an open issue in frankenphp  but I don't know if it's the same problem : https://github.com/dunglas/frankenphp/issues/314

Thank you for your support.

**Comment by akwawa** [comment]
> It's only for the worker mode ?

Yes.
If I apply the variable in the .env.local file, I can use the "REMOTE_USER" authenticator.

But this is a problem if we want to have several workers.

**Comment by maxhelias** [comment]
I think this change fix your issue : https://github.com/dunglas/frankenphp/pull/548, you can try it on the [v1.1.0](https://github.com/dunglas/frankenphp/releases/tag/v1.1.0) of frankenphp
