### ISSUE TITLE
Folders / files are created as root 644 and can't be edited (.env, composer.json, config folder ..)

### ISSUE THREAD

**Issue by Maxldev** [dunglas/symfony-docker#526]
First of all thanks for this docker solution !

I get a working project but folders / files are created as root in 644 and i can't edit them or create files in thos folders unless i chmod them. List is :

- bin folder
- composer.json
- composer.lock
- config folder
- .env
- .gitignore
- LICENSE
- src
- symfony.lock
- var
- vendor

Steps to reproduce :
- git clone
- docker compose build --no-cache
- docker compose up --pull always -d --wait

I'm on ubuntu 22.04.

Woul appreciate any help on this.

**Comment by Perf** [comment]
@Maxldev 
please check this docs: https://github.com/dunglas/symfony-docker/blob/main/docs/troubleshooting.md#editing-permissions-on-linux

**Comment by Maxldev** [comment]
> @Maxldev please check this docs: https://github.com/dunglas/symfony-docker/blob/main/docs/troubleshooting.md#editing-permissions-on-linux

Thanks it works, sorry for not seeing this troubleshooting.md before !
