### ISSUE TITLE
How to disable tls for production env to work behind Traefik?

### ISSUE THREAD

**Issue by pyatnitsev** [dunglas/symfony-docker#530]
Hello!

Thank you for your work on this docker configuration.

The information about tls was provided in the docs, but how to disable using tis completely?

I want to use Franklin with caddy (but without mercure) behind the traefik router. How to configure caddyfile for that?

It would be great, to add some notes about disabling tls to the docs. 

Thank you!

**Comment by maxhelias** [comment]
Hello,

To disable tls you can see here : https://github.com/dunglas/symfony-docker/issues/451
And for mercure, just comment this line : https://github.com/dunglas/symfony-docker/blob/main/frankenphp/Caddyfile#L32-L45

And yes, the docs could be improve to explain the new variables available in the caddyfile to custom it like : $CADDY_GLOBAL_OPTIONS, $CADDY_EXTRA_CONFIG, $CADDY_SERVER_EXTRA_DIRECTIVES and also the mercure & franken config. 
I have created an issue to keep a reminder : https://github.com/dunglas/symfony-docker/issues/532

PR are welcome 😉
