### ISSUE TITLE
Security issue with database port

### ISSUE THREAD

**Issue by hildebro** [dunglas/symfony-docker#535]
I've noticed during development with doctrine+postgres that port 5432 is open and accessible from other machines in my network. I didn't modify any configuration files manually, just letting the recipes do what's needed. It would be more secure to only allow the php container to have access to it.  

I'd also think that in dev environment, ports 80 and 443 should only be accessible by my host machine rather than the whole network. Or at least the documentation should have a section on how to secure these things on my own.

I'm not super knowledgeable about networking, but from what I know, I could secure these ports by putting them on the loopback 127.0.0.1. But I have no idea how to do that for the symfony-docker project

**Comment by dunglas** [comment]
It's almost impossible to make dev environments secure (debug mode is on, etc), and it's not a goal of this project.

**Comment by hildebro** [comment]
@dunglas Okay fair enough. But then deploying in production should not leave ports open unless necessary. Obviously port 80 and 443 must be open for the website to work. But the database port doesn't need to be exposed.

From what I can tell, running the project in prod mode doesn't really change anything about the database ports, so it's also open to the public on a live instance right?

**Comment by dunglas** [comment]
The port is only exposed in dev: https://github.com/symfony/recipes/blob/main/doctrine/doctrine-bundle/2.9/manifest.json#L38

`docker-compose.prod.yaml` isn't used in prod mode.

**Comment by hildebro** [comment]
Alright, thanks for the info
