### ISSUE TITLE
php config file order

### ISSUE THREAD

**Issue by wizhippo** [dunglas/symfony-docker#538]
As php takes the last ini value set, in frankenphp/conf.d

The order currently is:

app.dev.ini
app.ini

Expected would be:

app.ini
app.dev.ini

Should app.dev.ini be renamed so it is loaded after app.ini?  Currently there is only one setting in app.dev.ini but more could be added and I believe the expected behavior would be it take precedence over settings in app.ini.

**Comment by maxhelias** [comment]
Yes, a PR would be welcome.
We currently have these : 
<img width="571" alt="Capture d’écran 2024-02-25 à 19 36 37" src="https://github.com/dunglas/symfony-docker/assets/12966574/8cbd2986-72c4-41e8-9b7d-eb2762cc5760">

**Comment by wizhippo** [comment]
Is there any preference?

rename it to app.zzdev.ini or zzz-app.dev.ini?

**Comment by maxhelias** [comment]
With number ? `00-app.ini` & `01-app.dev.ini` ?

**Comment by wizhippo** [comment]
> With number ? `00-app.ini` & `01-app.dev.ini` ?

Numbers will move them above the docker-php-ext-xyz.ini  I would think we want our config to supersede them so I used the z prefix to move them to the bottom as php uses the last set value.  So maybe z01-app.ini, z02-other.ini, ... Again normally the dev is loaded last so zzz-dev.ini seems most likely to be loaded last.

**Comment by leroy0211** [comment]
You could also set the `PHP_INI_SCAN_DIR` environment variable to 2 paths. 

```
ENV PHP_INI_SCAN_DIR="$PHP_INI_DIR/conf.d:$PHP_INI_DIR/app.conf.d"
```

This way the `conf.d` directory is scanned first for ini files, and then the `app.conf.d` is scanned for ini files.  

This way you can sort the app's ini files in numerical order. 

```
/usr/local/etc/php/app.conf.d/01-app.ini
/usr/local/etc/php/app.conf.d/09-app.dev.ini  - or -  /usr/local/etc/php/app.conf.d/09-app.prod.ini
```

This way you can leave some room for developers to add ini config in all locations.
