### ISSUE TITLE
Impossible to deploy in prod with a database

### ISSUE THREAD

**Issue by n1k00las** [dunglas/symfony-docker#540]
Hello, 

First of all thanks for your great work. It work really well in dev environnement but when i try to deploy it on my prod server i haves many issues with the database when cache:clear is executed.

The first one is : `php_network_get addresses: getaddrinfo for database failed: Name does not resolve` when i use `@database` in the DATABASE_URL. 

So i have change it with `127.0.0.1` and then i have a` connection refused`

When i build only the database container and connect to it i am able to access the database with the user/password i want to use.

**Comment by maxhelias** [comment]
Hello,

Yes, this line should be kept.

Instead of `127.0.0.1` in DATABASE_URL you just need to put the service name in your docker-compose file. I don't know if the `@` in your example is a typo or not but it doesn't have to be.

**Comment by n1k00las** [comment]
As i said in my second message all my issues were related to this line, if i remove it i can build the containers in production env.
Now it's working as you say with the database like in my dev env.
