### ISSUE TITLE
Frankenphp migrations

### ISSUE THREAD

**Issue by tbredillet** [dunglas/symfony-docker#545]
I install a new project and the php container restart each minute because a migration doesn't work on the file docker-entrypoint.sh line 52 :

`php bin/console doctrine:migrations:migrate --no-interaction`

In docker logs, I have this message : 
`
[critical] Error thrown while running command "doctrine:migrations:migrate --no-interaction". Message: "An exception occurred while executing a query: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "user_id_seq" already exists"
`

How can we fix this ?

**Comment by stefantalen** [comment]
Looks like it tries a migration that has already been migrated but is missing from the versions table.

Manually adding the migration to the versions table should do the trick

**Comment by tbredillet** [comment]
Indeed, it's working when I use migrations:migrate instead doctrine:schema:update

Thank you

**Comment by tbredillet** [comment]
Indeed, it's working when I use migrations:migrate instead doctrine:schema:update

Thank you
