### ISSUE TITLE
Documentation on deployment with Kamal

### ISSUE THREAD

**Issue by florentdestremau** [dunglas/symfony-docker#546]
Hi, given the recent advance in container deployment @ 37Signals, it would feel natural to use https://kamal-deploy.org/ as a recommended deploy method.

**Comment by maxhelias** [comment]
Hello,

I'm not currently familiar with kamal, so it doesn't seem immediately apparent to me. Could you please provide more details on why we should consider recommending it over other solutions? I'd appreciate some insights to better understand its advantages.

Thank you!

**Comment by florentdestremau** [comment]
I'm actually saying this because I had some issues when trying to deploy using Kamal :smile: 

I know the Symfony ecosystem is pushing for Platform.sh as the go-to deployment tool. I feel like this repo is either pointing out very hands-on deployment [here](https://github.com/dunglas/symfony-docker/blob/main/docs/production.md) or redirecting to outside docs for K8s or docker swarm.

I think it would be beneficial to have alternatives for smaller projects that do not require k8s. In pure PHP you have https://deployer.org/ that is very powerful and PHP-based so very logically it's mentioned in the [symfony docs](https://symfony.com/doc/current/deployment.html#using-build-scripts-and-other-tools). Here the equivalent of deployer (which is an equivalent of capistrano) would be Kamal which is the equivalent of capistrano by the 37Signals team for docker deployment.
