### ISSUE TITLE
No releases available for package "pecl.php.net/apcu"

### ISSUE THREAD

**Issue by karousn** [dunglas/symfony-docker#55]
fresh installation : 

Build complete.
Don't forget to run 'make test'.

Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20170718/
find . -name \*.gcno -o -name \*.gcda | xargs rm -f
find . -name \*.lo -o -name \*.o | xargs rm -f
find . -name \*.la -o -name \*.a | xargs rm -f
find . -name \*.so | xargs rm -f
find . -name .libs -a -type d|xargs rm -rf
rm -f libphp.la       modules/* libs/*
WARNING: Ignoring APKINDEX.00740ba1.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.d8b2a6f4.tar.gz: No such file or directory
(1/1) Purging .phpize-deps (20191124.165709)
OK: 272 MiB in 67 packages
\+ pecl install apcu-5.1.12
No releases available for package "pecl.php.net/apcu"
install failed
ERROR: Service 'app' failed to build: The command '/bin/sh -c set -eux  && apk add --no-cache --virtual .build-deps             $PHPIZE_DEPS            icu-dev                 zlib-dev    && docker-php-ext-install -j$(nproc)             intl            zip     && pecl install                 apcu-${APCU_VERSION}    && docker-php-ext-enable --ini-name 20-apcu.ini apcu    && docker-php-ext-enable --ini-name 05-opcache.ini opcache   && runDeps="$(         scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions             | tr ',' '\n'             | sort -u             | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }'     )"     && apk add --no-cache --virtual .api-phpexts-rundeps $runDeps' returned a non-zero code: 1

Thank for this work :)

**Comment by maxhelias** [comment]
This error is weird.. but can you provide us with more information, please ?
Which system do you use and which docker version do you have?

Also, when trying again do you still have the issue ?

**Comment by maxhelias** [comment]
@karousn any update ? Do you still have the case ?

**Comment by karousn** [comment]
yes i still have this issue on my vagrant box [bento/ubuntu-18.04](https://github.com/chef/bento/blob/master/packer_templates/ubuntu/ubuntu-18.04-amd64.json) ,
Docker version 19.03.5, build 633a0ea838
this last test i do it right now after git pull on master branch of this repo.

**Comment by maxhelias** [comment]
I'm intrigued, why are you using symfony-docker inside a vagrant box ?
And wouldn't that be a problem of vagrant conf ? Because I can't reproduce it

**Comment by karousn** [comment]
i think that i'm in the same condition like : [#81](https://github.com/DivanteLtd/open-loyalty/issues/81)
I try the suggested solution by set **pear config-set http_proxy** i don't have any change on error message.
I think it is specific condition for this project so it will try to use my personal machine for test and i will back for the result.

**Comment by maxhelias** [comment]
Maybe you can take a look #47

**Comment by maxhelias** [comment]
@karousn, I'd like to move forward on this issue, could you tell me if the #47 has fixed your issue ?

**Comment by karousn** [comment]
@maxhelias
i test the https_proxy but doesn't work for me, we use some ca files to pass throw our company network, for pear we can mention a ca files like node or other program ?

**Comment by maxhelias** [comment]
Erf 😞 For pear, i don't know i always used it in its default configuration.
I'm not sure I can help you more than that, sorry, but if you solve your problem, I would like feedback

**Comment by julien235** [comment]
that workaround (pear set-config http_proxy) works for me; but not with pecl config-set oddly. 
Once http_proxy is setted by pear set-config, i can view the value with pecl config-get http_proxy.

**Comment by maxhelias** [comment]
The information seems to come from pear's conf proxy. Let's continue the discussion on the work in progress : https://github.com/dunglas/symfony-docker/pull/47

If there is any other information that might be relevant to the outcome, please feel free to reopen it.

**Comment by devcrazygit** [comment]
Hello, guys, Is the problem solved?
