### ISSUE TITLE
services.php.environment array items[3,12] must be unique

### ISSUE THREAD

**Issue by rene-schwabe** [dunglas/symfony-docker#550]
If I run
`docker compose -f compose.yaml -f compose.prod.yaml up -d --wait
`
for production I will get:
`services.php.environment array items[3,12] must be unique`

How do I run the production containers?

**Comment by CodeCraftDevex** [comment]
In compose.prod.yaml 
these variables must be unique, as they are duplicated, causing an error:
 MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
