### ISSUE TITLE
Help with certificate

### ISSUE THREAD

**Issue by Gabb1995** [dunglas/symfony-docker#554]
I ran the linux command and it worked fine no errors (except had to use sudo).
```
09:49:20 ✗  sudo docker cp $(docker compose ps -q php):/data/caddy/pki/authorities/local/root.crt /usr/local/share/ca-certificates/root.crt && sudo update-ca-certificates
Successfully copied 2.56kB to /usr/local/share/ca-certificates/root.crt
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
Updating Mono key store
Mono Certificate Store Sync - version 6.8.0.105
Populate Mono certificate store from a concatenated list of certificates.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Importing into legacy system store:
I already trust 137, your new list has 138
Import process completed.

Importing into BTLS system store:
I already trust 136, your new list has 138
Certificate added: C=ES, CN=Autoridad de Certificacion Firmaprofesional CIF A62634068
1 new root certificates were added to your trust store.
Import process completed.
Done
done.
```

Now when I open the project in the browser when going to localhost I am still getting that its unsafe.
![image](https://github.com/dunglas/symfony-docker/assets/20728259/0c12241a-0296-4c86-ac34-d0233c97b742)

Not sure what else I need to do?

**Comment by maxhelias** [comment]
Hi,
Check that the domain associated with the certificate is the url you are requesting.

**Comment by Gabb1995** [comment]
Hi @maxhelias thanks for the reply, how do I do that? is there any documentation I can look at to help me out?

**Comment by maxhelias** [comment]
You can find the common name and other information with this tool : https://www.sslshopper.com/certificate-decoder.html or with the openssl command

**Comment by Gabb1995** [comment]
With that tool or openssl command it didn't show anything regarding the domain. I guess it could be because I'm just using localhost? Does it only work with custom domain name?

![image](https://github.com/dunglas/symfony-docker/assets/20728259/c6583cba-8f4f-4211-8182-6c54e8c020e6)
![image](https://github.com/dunglas/symfony-docker/assets/20728259/6dfa80e2-5cbb-4d8a-98a9-8d1d999652bd)
