### ISSUE TITLE
Moving to Debian

### ISSUE THREAD

**Issue by dunglas** [dunglas/symfony-docker#555]
There are some weird issues with Alpine and PHP, and I recently learned that musl isn't really actively supported by PHP. They fix bugs when reported or patched, but don't run tests with musl etc. There are also many known issues with JIT and musl.

I propose to switch back to Debian/glibc, which is officially supported by PHP.

**Comment by rccc** [comment]
Hello,
It would be nice for those who have to use python libraries.

**Comment by Perf** [comment]
Well, it seems there quite a lot of reasons to move to Debian.
Not sure how accurate is this benchmark, but definitely worth to check it.
https://stackoverflow.com/a/75371326

**Comment by dkarlovi** [comment]
The more important question is probably why isn't PHP taking musl seriously as a target. :see_no_evil:

**Comment by drupol** [comment]
How about using Nix to build it? You would have something totally reproducible for free too!
