### ISSUE TITLE
worker problem ?

### ISSUE THREAD

**Issue by treeindark** [dunglas/symfony-docker#556]
Problem with worker : 
`
500 Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Twig\Environment::getTemplateClass(): Argument #1 ($name) must be of type string, null given, called in /app/vendor/twig/twig/src/Environment.php on line 312")." at edit.html.twig line 61 | context={"exception":{"class":"Twig\\Error\\RuntimeError","message":"An exception has been thrown during the rendering of a template (\"Twig\\Environment::getTemplateClass(): Argument #1 ($name) must be of type string, null given, called in /app/vendor/twig/twig/src/Environment.php on line 312\").","code":0,"file":"/app/vendor/easycorp/easyadmin-bundle/src/Resources/views/crud/edit.html.twig:61","previous":{"class":"TypeError","message":"Twig\\Environment::getTemplateClass(): Argument #1 ($name) must be of type string, null given, called in /app/vendor/twig/twig/src/Environment.php on line 312","code":0,"file":"/app/vendor/twig/twig/src/Environment.php:262"}}} level_name=CRITICAL channel=request datetime=2024-02-01T09:02:16.384901+00:00 extra={}`

no problem when  worker disable

**Comment by treeindark** [comment]
https://github.com/dunglas/symfony-docker/issues/474

**Comment by dunglas** [comment]
Closing as duplicate.
