### ISSUE TITLE
Mercure 401 error after a long time on website

### ISSUE THREAD

**Issue by n1k00las** [dunglas/symfony-docker#561]
Hello, 

In production mode i have a issue with Mercure and the use of Turbostream. When i stay a long time on my project, i have a 401 error each time i try to connect a stream to mercure shown in browser console. 

Did i miss something in the configuration. I would like to have a constant connection or a way to reset it. Because i have to shut down my browser and go back on my app

Thanks

**Comment by maxhelias** [comment]
Hello,

We are trying to keep the issues tracker within the scope of this project. Check out the Mercure project on github for a better answer.

Thank you for your understanding.
