### ISSUE TITLE
Migrations not running when using secrets

### ISSUE THREAD

**Issue by KDederichs** [dunglas/symfony-docker#562]
From reading the `docker-entrypoint.sh` script it seems that migrations are dependant on the `DATABASE_URL` in the .env file.

When using secrets (`secrets:set`) you don't necessarily have that value in there anymore though causing migrations to not be run.

What's the best approach here? Have some kind of dummy value in there just for that or change the script?

**Comment by maxhelias** [comment]
Hello,

You are free to adapt the script to your project so that it corresponds to your use case and to remove the blocking statement.

Note : Don't forget afterwards to rebuild your docker image without using the cache so that the change is taken into account.
