### ISSUE TITLE
Add workers like the symfony cli

### ISSUE THREAD

**Issue by slappyslap** [dunglas/symfony-docker#563]
Hi !
Like the symfony cli, is there a way to define some workers in "dev" environment, for by example, watch and build the assets or consume the messenger queue.

Related symfony cli configuration: 
https://symfony.com/doc/current/setup/symfony_server.html#configuring-workers

**Comment by maxhelias** [comment]
Hello,

You should suggest this feature on the frankenphp repository.
And I see it's already been suggested: https://github.com/dunglas/frankenphp/issues/55

Thanks
