### ISSUE TITLE
Extend documention / How-to mysql

### ISSUE THREAD

**Issue by dsentker** [dunglas/symfony-docker#566]
I am familiar with MySQL and don't want to use PostgreSQL. I therefore had to make some adjustments for MySQL and there were some pitfalls. Would it make sense to expand the documentation to include this point? If there is interest I can create a PR.

**Comment by dunglas** [comment]
Completely! I don't really like maintaining variants because it can lose newcomers (too many choices to make) and it increases the maintenance load, but an entry in the doc would be great!

**Comment by dsentker** [comment]
You may lose newcomers, but you may also scare off those who have mediocre experience but don't know how to integrate MySQL. I did my best with the linked PR and I look forward to feedback.

**Comment by amir-ys** [comment]
it would be great if mysql was added .  a am also waiting for this

**Comment by maxhelias** [comment]
Closing in favor #567
