### ISSUE TITLE
Symfony profiler pointing to nginx/_profiler/

### ISSUE THREAD

**Issue by thePanz** [dunglas/symfony-docker#59]
When using the application from `https://localhost` and enabling the Symfony profiler-pack, the web-toolbar is pointing to `nginx/_profiler/xxxxx`

The issue happens only when using the `https` protocol, under `http` the link works correctly and points to `localhost/_profiler/xxxx`

**Comment by maxhelias** [comment]
@thePanz can you confirm that the #60 will correct the problem?

**Comment by maxhelias** [comment]
Fixed by #60
