### ISSUE TITLE
Installing on existing projects without local php / composer

### ISSUE THREAD

**Issue by lode** [dunglas/symfony-docker#607]
I'm trying to install this on an existing Symfony project. I'm trying to follow https://github.com/dunglas/symfony-docker/blob/main/docs/existing-project.md, however this states to run `composer` commands from outside Docker / before building Docker.

The whole reason I'm using this project is to not have a local php environment. Is there a way around this? Can I run the `composer` commands afterwards from inside the Docker console? Does I need to run other commands then?

**Comment by treeindark** [comment]
use frankenphp/docker-entry-point.sh for config et execute script in container

**Comment by maxhelias** [comment]
The config command can be done by hand, it simply edits the composer.json and the other can be done afterwards in the container without any problem.
