### ISSUE TITLE
Problem with "docker-entrypoint" under Windows

### ISSUE THREAD

**Issue by Moskito89** [dunglas/symfony-docker#609]
When I try to start the project with `docker compose up --pull always -d --wait` as described, it runs well (but slow) under macOS. Under Windows, an error appears saying 

```
exec /usr/local/bin/docker-entrypoint: no such file or directory
```

I read some information about that file and checked the encoding and some other things, but all of them seem to be fine. Has anyone got that error too? Has the [`COPY`](https://github.com/dunglas/symfony-docker/blob/e022f7333dd09029c662e32a306a4b63b48a1d28/Dockerfile#L41) under Windows problems?

**Comment by 7-zete-7** [comment]
Hello @Moskito89!

Can you show content of your's `compose.yaml`, `compose.override.yaml` and `Dockerfile` files?

**Comment by maxhelias** [comment]
For the slowness on MacOS, this has been improved on the latest versions of docker for mac. If that's not enough, have a look at these lines : https://github.com/dunglas/symfony-docker/blob/c7c788aca1080709613d1e3001ddabd7b7f4531d/compose.override.yaml#L13

For your Windows issue, I have no idea and no windows installation to try. The content of your file doesn't really help, it would be better to publish a reproducer

**Comment by maxhelias** [comment]
It seems that there are already a number of answers that should help you on [Google](https://www.google.com/search?q=exec+%2Fusr%2Flocal%2Fbin%2Fdocker-entrypoint%3A+no+such+file+or+directory)

**Comment by Moskito89** [comment]
Thank you for your advice, @maxhelias. I have already tried to remove the `vendor` folder, but could not notice any change.

I have already visited some of the sites you mentioned and, as described at the beginning, checked the issues discussed there. For example, the encoding of the file, line endings, the quotation marks, etc. None of this has helped — or rather, everything seems to be in order. I have not been able to find any errors.

I can try to set up a test repository tomorrow and will send it to you then. Thanks for your help in advance!

**Comment by Moskito89** [comment]
I‘m sorry, @7-zete-7, but I can‘t. Docker tells me, that the container needs to be run, to execute a command. So it seems like it would fail even before. 

I tried the basic example on the same system, and it ran correctly. So the problem has something to do with my configuration. Maybe I‘ll find sone time do debug that step by step, but that’s currently not the case. 

Maybe we should close the issue but mark it as unresolved.

**Comment by 7-zete-7** [comment]
@Moskito89 try the command below to start container.

```shell
docker compose run --entrypoint='' php sh
```

**Comment by enzalito** [comment]
Had the same problem, converting Windows line breaks to Unix ones fixed the issue for me.  
I think that cloning the repo on Windows causes the issue as I have the correct line breaks when I download the file directly from GitHub. If that is the case, it be a good idea to tell Windows users to run this command somewhere in the doc:
`git config --global core.autocrlf true`

**Comment by 7-zete-7** [comment]
@Moskito89 can you move your project to WSL and try to run it from there?
