### ISSUE TITLE
CURL certificate

### ISSUE THREAD

**Issue by 0ctave** [dunglas/symfony-docker#61]
Hey guys !

I'm trying to use guzzlehttp to communicate with an external api but I keep getting 

`cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

I tried to manually add the certificate in the symfony.ini as well as in the /usr/local/etc/php/php.ini, but it doesn't seem to help in any ways

```
curl.cainfo="/srv/app/docker/php/conf.d/cacert.pem"
openssl.cafile="/srv/app/docker/php/conf.d/cacert.pem"
```

Thx for your help 😄

**Comment by hacfi** [comment]
@0ctave Try adding 
```
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
```
to the `Dockerfile` and see if that resolves the issue.

**Comment by maxhelias** [comment]
Now we use caddy server with automatic https.
This should correct the problem. If it doesn't, don't hesitate to re-open the issue.

**Comment by axxox** [comment]
Ok, so those are overall changes based on @0ctave and @hacfi .

1. Added pem file `docker/php/certs/rootCA.pem`

2. Updated `docker/php/conf.d/app.dev.ini` by adding:
```ini
curl.cainfo = '/etc/ssl/private/rootCA.pem'
```

3. Updated `docker-compose.yml`, by adding into `services.php`:
```diff
    volumes:
      - php_socket:/var/run/php
+     - ./docker/php/certs/rootCA.pem:/etc/ssl/private/rootCA.pem
```

4. Updated `Dockerfile`, by adding:
```diff
# Dev image
FROM app_php AS app_php_dev

+ RUN apk update && apk add ca-certificates && update-ca-certificates && apk add --update openssl && rm -rf /var/cache/apk/*
```

And it works like a charm!
