### ISSUE TITLE
Run as a different user

### ISSUE THREAD

**Issue by Growiel** [dunglas/symfony-docker#612]
Hello there,

I do not have composer installed on my machine, or even PHP for that matter, and don't want to.

I work on a lot of different projects, each with their own PHP version so installing it locally makes little sense for me.

For this new project, I went with the official symfony-docker, but it runs as root. I did check the troubleshooting and `chown`'ed the files back to my user.

But the issue is that any NEW file I create when using `bin/console make:...` or even just `composer require ...` also belongs to root and I have to `chown` every time.

Am I missing something obvious? I tried running the container with `user: ${DEV_UID:-1000}:${DEV_GID:-1000}` but due to how the containers are built it causes other issues (unable to write to `var/cache/dev`).

Is there a way to run as my local user?

Thanks.

**Comment by maxhelias** [comment]
Hello,

See this article : https://dev.to/acro5piano/specifying-user-and-group-in-docker-i2e

**Comment by Growiel** [comment]
Hello,

This is exactly what I did, and as mentioned in my post, it does not work:

Solution 1 causes the build to fail due to permission issues when trying to move the php.ini.

Solutions 2 and 3 cause the container to never go past the "waiting for database" step, because it's unable to create the `var/cache/dev` folder, again due to permission issues.

**Comment by maxhelias** [comment]
You need to adjust your docker setup : 

Solution 1 : You need sudo privileges

Solution 1 : You must ensure that the privileges given to the service are not less than the COPY instruction of docker, which by default is root. Use the optional flag `--chown=<user>:<group>` with either the `ADD` or `COPY` commands. Doc : https://docs.docker.com/reference/dockerfile/#copy

**Comment by 7-zete-7** [comment]
Hello @Growiel!

You can edit _frankenphp/docker-entrypoint.sh_ file to add the ability to run something under a different user, while maintaining `root`'s rights to configure the container.

Add next lines at the start of your _frankenphp/docker-entrypoint.sh_ file:
```patch
+ UID="${UID:-$(id -u www-data)}"
```

Replace next line at the end of your _frankenphp/docker-entrypoint.sh_:
```patch
- exec docker-php-entrypoint "$@"
+ su -c "$(echo docker-php-entrypoint $@)" -s '/usr/bin/sh' "$(id -un "$UID")"
```

Then you can use the `UID` environment variable to set required user ID.

Examples:

```shell
$ docker compose run --rm --env UID=5 php id
uid=5(games) gid=60(games) groups=60(games)
```

```shell
$ docker compose run --rm --env UID=www-data php id
uid=33(www-data) gid=33(www-data) groups=33(www-data)
```

These file edits are not the final solution, but only the ability to run the container under a different user.

**Comment by ikerib** [comment]
I have a similar issue myself... mi current id:gid are something like this, ldap user.
1463240267:1463200513

I tried this but if I run cache:clear or composer install, the result is root as owner of the var and vendor directories instead of my id:gid:
![irudia](https://github.com/dunglas/symfony-docker/assets/333052/cbaed428-14e2-46ae-af3b-a2e1abd65aed)

And I need set correct permissions all the time. Is ther any fix?

**Comment by 7-zete-7** [comment]
Hello @ikerib!

You can use this command to change owrenship of your files to another user:
```shell
find . \( -user "$FROM_UID" -or -group "$FROM_GID" \) -print0 | xargs -0 sudo chown "$TO_UID:$TO_GID" .
```

Example: change files ownership from `root` (`0`) to custom user (`1000`):
```shell
find . \( -user 0 -or -group 0 \) -print0 | xargs -0 sudo chown 1000:1000
```

This command can be added to any place to automate ownership fixing.

**Comment by ikerib** [comment]
thx @7-zete-7 but it is not working
on host:
![irudia](https://github.com/dunglas/symfony-docker/assets/333052/71a8c326-cfd5-49fe-ab6d-4f404935a965)

on container:
![irudia](https://github.com/dunglas/symfony-docker/assets/333052/9f9ebea8-5dc6-474b-b4d1-4848d9a1570b)


I think creating a user somehpw with UID and GUI will be necesary
