### ISSUE TITLE
cdn.jsdelivr.net importmap:install ERROR Curl 

### ISSUE THREAD

**Issue by gaetanvilleneuve** [dunglas/symfony-docker#614]
Hello, 

i'm using dunglas docker with Symfony 6.4 / php 8.3
And i use importmap / AssetMapper of Symfony (the native "webpack" of symfony)
I have an error while cURL on "cdn.jsdelivr.net" for  "@gouvfr/dsfr"package.

Here is my importmap.php : 
```
<?php
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    '@symfony/stimulus-bundle' => [
        'path' => './vendor/symfony/stimulus-bundle/assets/dist/loader.js',
    ],
    '@hotwired/stimulus' => [
        'version' => '3.2.2',
    ],
    '@hotwired/turbo' => [
        'version' => '8.0.4',
    ],
    '@gouvfr/dsfr/dist/utility/utility.min.css' => [
        'version' => '1.11.2',
        'type' => 'css',
    ],
    '@gouvfr/dsfr/dist/dsfr.min.css' => [
        'version' => '1.11.2',
        'type' => 'css',
    ],
    '@gouvfr/dsfr/dist/dsfr.module.min.js' => [
        'version' => '1.11.2',
    ],
];
```

All package are imported in asset/vendor except : @gouvfr/dsfr/dist/utility/utility.min.css 

when i execute : `php bin/console importmap:install` i have this error : 
```
In CurlResponse.php line 316:

  [CONN-1-0] send: no filter connected for "https://cdn.jsdelivr.net/npm/@gouvfr/dsfr@1.11.2/dist/icons/business/window-fill.svg".

In ErrorChunk.php line 56:

  [CONN-1-0] send: no filter connected for "https://cdn.jsdelivr.net/npm/@gouvfr/dsfr@1.11.2/dist/icons/business/window-fill.svg".

In CurlResponse.php line 316:

  [CONN-1-0] send: no filter connected for "https://cdn.jsdelivr.net/npm/@gouvfr/dsfr@1.11.2/dist/icons/business/window-fill.svg".

In ErrorChunk.php line 56:

  [CONN-1-0] send: no filter connected for "https://cdn.jsdelivr.net/npm/@gouvfr/dsfr@1.11.2/dist/icons/business/slideshow-line.svg".

In CurlResponse.php line 316:

  [CONN-1-0] send: no filter connected for "https://cdn.jsdelivr.net/npm/@gouvfr/dsfr@1.11.2/dist/icons/business/slideshow-line.svg".
```

I don't understand why

Do you have this error ?
If yes, i don't know how to fix it..

I found just one guys talking about it : 
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1965052.html 
but it's on a windows local environment 
and he speak about php8.2-curl which is not in our php container linux

If i do a `whereis curl` on container it's : `usr/bin/curl`

so curl is not from php extension (curl.so)

So i tried adding `curl.so` and `curl` into `php-extension-installer` but it doesn't worked.

I'm stuck, thanks for your time and your help.

**Comment by 7-zete-7** [comment]
Hello @gaetanvilleneuve!

Can you show your `ext-curl` and `libcurl` versions?

**Comment by fstronin** [comment]
Hello! I have the same issue on trying to run multi requests through a http-client.
```failed: [CONN-0-0] send: no filter connected for```
```
curl 7.88.1 (aarch64-unknown-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.11 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0 nghttp2/1.52.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2023-02-20, security patched: 7.88.1-10+deb12u5
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

**Comment by 7-zete-7** [comment]
I found a similar problem in https://github.com/rust-lang/cargo/issues/12202.

The problem is with `libcurl`. Versions of `libcurl` _7.87.0_, _7.88.0_ and _7.88.1_ have errors.

That issue suggested ignoring these versions of `libcurl`.

**Comment by maxhelias** [comment]
Hi @gaetanvilleneuve,

No need to install `php8.2-curl` because the PHP base image have been compiled with  `--with-curl`. You should see curl support when you do a `php -m`.
If this is due to a problem with libcurl, try another version of libcurl with a PHP without the curl support on the compilation and add its support using the module.
