### ISSUE TITLE
Too stupid for recipes

### ISSUE THREAD

**Issue by l0wskilled** [dunglas/symfony-docker#619]
Hi everyone, I might be stupid.

I followed the readme. I kind of got lost how to add symfony. I looked around, only saw something about using existing projects.

I then started to create a project using the [current docs setup guide](https://symfony.com/doc/current/setup.html). I had to do this in a separate folder, as composer can't create in the same.
Anyway I then moved all the files manually into the symfony-docker folder, I thought the public folder in symfony-docker implies this.
I tried rerunning the recipes and all, uncommented the stuff with Postgres, but the recipes never executed anything on the compose or Dockerfile. I can clearly see that the 2.12 doctrine/doctrine-bundle recipe should be creating lots of stuff, in the manifest, and i want to get this done automagically.

I would create PR to extend the readme for stupid persons like me if anyone can help me set this up.

**Comment by Wordlesschunk** [comment]
Unsure if im understanding but symfony should be pulled through once you run the docker compose to build the containers

**Comment by l0wskilled** [comment]
You mean if I run the up command it populates my local folder? Is it really that easy? I'm gonna try it. Haven't expected to get symfomy via docker compose up. 

If it's that easy...

**Comment by Wordlesschunk** [comment]
Yeah i was a little shocked when it first did it, I think if you've got a pre-existing repo you can follow the steps within docs/existing-project.md havent done it yet

**Comment by l0wskilled** [comment]
<img src="https://media2.giphy.com/media/Um3ljJl8jrnHy/giphy.gif"/>
It really does... I will PR the next days to mention this in the Readme.

Thank you @Wordlesschunk
