### ISSUE TITLE
Is mecure required for production?

### ISSUE THREAD

**Issue by Wordlesschunk** [dunglas/symfony-docker#620]
Hey guys i'm wanting to use this skeleton but im not too sure why the mecure hub is required? 
i've tried to remove its references from the Caddyfile but the option CADDY_MERCURE_JWT_SECRET is still required when booting the containers in prod mode

can someone explain to me why its required and if it isnt, how can i fully remove it from my stack? cant seem to find anymore references to it

Many Thanks!

**Comment by dunglas** [comment]
It isn't.

Remove this block from `Caddyfile` if you don't want to enable the Mercure hub:

https://github.com/dunglas/symfony-docker/blob/main/frankenphp/Caddyfile#L32-L45

You can also remove everything related to Mercure in `compose*.yaml`.
