### ISSUE TITLE
Unable to connect to external database

### ISSUE THREAD

**Issue by Wordlesschunk** [dunglas/symfony-docker#622]
Hey guys 
Im currently trying to get my app up and running and am facing an issue with connecting to my external database
I've checked to make sure all required ports are open and i can connect to my database locally, just keep getting the following error: 

<img width="934" alt="image" src="https://github.com/dunglas/symfony-docker/assets/22942020/83917c31-9d04-4b45-9528-f73ae9c2d514">

I can mess around with the connections slightly and get the app to boot but i get the error 
An exception occurred in the driver: could not find driver

within my env: DATABASE_URL="mysql://blah:blah@001.eu.clouddb.ovh.net:35203/app?serverVersion=8.0.32&charset=utf8mb4"

Thanks

**Comment by leroy0211** [comment]
You have to install mysql extension yourself in your `Dockerfile`. 

```

RUN     install-php-extensions pdo_mysql
```
