### ISSUE TITLE
Unable to boot app in production mode 

### ISSUE THREAD

**Issue by Wordlesschunk** [dunglas/symfony-docker#624]
Hey guys im trying to run my app in production mode (works fine in dev mode)

When running:
`docker compose -f compose.yaml -f compose.prod.yaml up -d --wait`

I get:
<img width="950" alt="image" src="https://github.com/dunglas/symfony-docker/assets/22942020/f917def4-a3d5-4074-bacd-65d160da73b1">

With the container restarting constantly

any ideas?

**Comment by 7-zete-7** [comment]
Hello @Wordlesschunk!

Show your `Dockerfile`, `compose.yaml`, `compose.override.yaml` and `compose.prod.yaml` files.

**Comment by maxhelias** [comment]
Hi,

If you haven't touched the original template, this shouldn't happen with this instruction: 
 https://github.com/dunglas/symfony-docker/blob/bfdd75e73ffcdce57f0f9f883029b57629549195/Dockerfile#L79

Also, docker can have a cache layer, make sure you have the right build for each deployment or rebuild your project with --no-cache option to avoid cache issue.
