### ISSUE TITLE
Large number of entities cause ORM mapping to break

### ISSUE THREAD

**Issue by aelfannir** [dunglas/symfony-docker#627]
I'm facing a weird issue 2 days ago, everything was working fine until last week, when I create any file inside Entity folder, and try to generate migration, the migration drops all tables and kept only one, I thought It's a Doctrine ORM issue and opened a [ticket](https://github.com/doctrine/orm/issues/11435), also the `debug:router` don't return any entity route (using api-platform)

Today, I created a fresh docker-based project and put my entities to it, the same issue appears, then I tried to launch project without docker, and it worked.

**Comment by aelfannir** [comment]
I've tried another project with older version of symfony-docker, the same thing happened after I created 48 Entity

**Comment by maxhelias** [comment]
The first issue is probably linked to the doctrine/migration project.

The second is probably linked to the docker volume. We've already had reports of behavior like this here: 
- https://github.com/dunglas/symfony-docker/issues/226#issuecomment-1106150198
- https://github.com/dunglas/symfony-docker/issues/241#issuecomment-1116334681

**Comment by aelfannir** [comment]
Both issues caused by same problem, even api-platform entity ressources not showing when the issue appears

**Comment by aelfannir** [comment]
Fixed by [Switching to Debian](https://github.com/dunglas/symfony-docker/pull/582)

**Comment by maxhelias** [comment]
So it's another musl issue

**Comment by aelfannir** [comment]
This issue appears again, I must rebuild docker whenever it appears

**Comment by dunglas** [comment]
@aelfannir have you switch to Debian?

**Comment by aelfannir** [comment]
> @aelfannir have you switch to Debian?

I just overridden symfony-docker old skeleton (Alpine) by the new one (Debian).

**Comment by aelfannir** [comment]
I temporary fix it by rebuilding fresh images whenever it happens
