### ISSUE TITLE
Help to understand the workflow

### ISSUE THREAD

**Issue by GrandOurs35** [dunglas/symfony-docker#63]
Hello,

First of all, sorry for this kind of question, it's not an issue but i'm trying to understand how the Dockerfile and Entry Point are working but, until now, without success... So if you think it's not convenient to do it here, please be free to tell me and delete my post.

From what i understand:
1) install Flex => you say it's to speed up downloads, but i don't see why it's useful because just after you install Symfony Skeleton ?
2) create the symfony project skeleton in "production mode" in any cases at the root directory (/srv/app) (row 87)
3) In the Entry Point: install in /tmp (and move to the root after) the skeleton again but only if composer.json is missing ohterwise just install dependencies. (which makes sense)

i don't see the link between stage 2 and 3 and why there is 2 composer create project ? and why the first create is happening in every cases ? Sorry for these stupid questions...

And thank you so much for your incredible work, this repository works perfectly well but i would like to understand how it's going. I'm quite a beginner with Docker and i read carefully the dockerfile and the logs but it's still not clear for me.
Thank you for your help
Romain

**Comment by maxhelias** [comment]
Hello, thanks for your word 😃 

For how entrypoint works, i recommend you to look at the definition and example here : https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact

And next :
 1. We install Flex as a global dependency like this every command `composer` in the container even outside the project benefits of the parallale downloader.
 2. The skeleton at this level allows you to initialize a new project with the latest stable version if you have not started or will be overwritten by the COPY, to cache it in the docker layers and to use it to initialize the volume inside the container. (the last two can be useful for publishing the image and manage it with a orchestrator in production)
 3. For this point, I'm not sure (I haven't studied the problem more closely at the begining), but I think with docker-compose in dev mode the volume is reset with you host (docker-compose line 18) at the first mounting, so if you don't started a project we create the skeleton dynamically to prevent errors with ACLs with `var` folder.

The main link between stage 2 & 3 is for the project to work as well as in development or for production.

Note: By writing these lines, I realize that it would be useful to have the composer install after the COPY in the dockerfile to use the docker cache as much as possible for production 🤔

**Comment by GrandOurs35** [comment]
Hi,
thank you so much for your answer and for your detailed explanation. It's really useful and i will try now to understand all of this and run the code step by step :)
Thanks a lot for your time and for sharing your knowledge.
