### ISSUE TITLE
invalid interpolation format for services.php.environment.TRUSTED_HOSTS

### ISSUE THREAD

**Issue by steflight** [dunglas/symfony-docker#630]
When i execute this command : 
Docker compose build --no-cache

I have this result: 
invalid interpolation format for services.php.environment.TRUSTED_HOSTS: "^${SERVER_NAME:-example\\.com|localhost". You may need to escape any $ with another $.

To solve problem i added $ . 
is it an issue or it depend on my docker version ?

**Comment by maxhelias** [comment]
Yes it's your docker version. See : https://github.com/dunglas/symfony-docker/issues/616 or https://github.com/dunglas/symfony-docker/issues/247

**Comment by garak** [comment]
I'm having a similar issue: 
```
invalid interpolation format for services.php.environment.MERCURE_PUBLIC_URL.
You may need to escape any $ with another $.
https://${SERVER_NAME:-localhost
```

My docker and docker-compose versions seem to be higher than the ones declared to be compatible:

Docker version 24.0.7, build 24.0.7-0ubuntu4.1
Docker Compose version v2.15.1
