### ISSUE TITLE
Serving Symfony Welcome Page with Docker Compose Opens phpinfo() Instead

### ISSUE THREAD

**Issue by Salhi-Yassine** [dunglas/symfony-docker#632]
### Title
Serving Symfony Welcome Page with Docker Compose Opens phpinfo() Instead

### Description
I encountered an issue when trying to run the Symfony Docker setup as described in the documentation. After following the steps, I found that navigating to the server name in my browser opens the `phpinfo()` page instead of the Symfony welcome page.

### Steps to Reproduce
1. Clone the repository:
    ```bash
    git clone https://github.com/dunglas/symfony-docker.git
    cd symfony-docker
    ```
2. Build the Docker images without cache:
    ```bash
    docker compose build --no-cache
    ```
3. Run the application with the following command:
    ```bash
    SERVER_NAME=your-domain-name.example.com \
    APP_SECRET=ChangeMe \
    CADDY_MERCURE_JWT_SECRET=ChangeThisMercureHubJWTSecretKey \
    docker compose -f compose.yaml -f compose.prod.yaml up -d --wait
    ```
4. Navigate to `http://your-domain-name.example.com` in a web browser.

### Expected Behavior
I expected to see the Symfony welcome page.

### Actual Behavior
The browser opens the `phpinfo()` page instead of the Symfony welcome page.

### Additional Context
When I run the following command, the Symfony welcome page is displayed correctly:
```bash
docker run \
    -e FRANKENPHP_CONFIG="worker ./public/index.php" \
    -e APP_RUNTIME=Runtime\\FrankenPhpSymfony\\Runtime \
    -e SERVER_NAME=your-domain-name.example.com \
    -v $PWD:/app \
    -p 80:80 -p 443:443 -p 443:443/udp \
    dunglas/frankenphp

**Comment by maxhelias** [comment]
Hi,
If you configure your service with this option `-f compose.prod.yaml`, you start your application in prod mode, so no welcome, no debug, but you shouldn't have the `phpinfo` either.
Why this command : `docker compose up --pull always -d --wait ` you start your application in dev mode and you should see the welcome page.

**Comment by e-vural** [comment]
I can't fix that problem. When i try to start by prod, my codes not shows in container. Its create a new symfony project.
