### ISSUE TITLE
Cannot install some PHP extention

### ISSUE THREAD

**Issue by rccc** [dunglas/symfony-docker#633]
Hello,

No way find  a package for php8.3-mbstring or php8.3-gd:

apt install php8.3-gd give "Package 'php8.3-gd' has no installation candidat".

apt install php8.3-mbstring

 Package 'php8.3-mbstring' has no installation candidate

It seems dunglas/frankenphp:1-php8.3 is based on debian 12 bookworm, it should not be a problem.

Using this image is not so easy ...

rccc

**Comment by 7-zete-7** [comment]
Hello @rccc!

To install additional extensions to this image enough to add required extension to the [extensions list](https://github.com/dunglas/symfony-docker/blob/main/Dockerfile#L29C1-L33C8):

```diff
 RUN set -eux; \
 	install-php-extensions \
 		@composer \
 		apcu \
+		gd \
 		intl \
 		opcache \
 		zip \
 	;
```
