### ISSUE TITLE
Mariadb Connexion lost

### ISSUE THREAD

**Issue by n1k00las** [dunglas/symfony-docker#638]
Hello,

I have the issue with the connexion lost. To get it back i have to restart my project. 

I have see that this issue https://github.com/symfony/symfony/pull/53214 is suppose to resolve the problem but even after an update of the vendor, it's stille there?

Does i have to configure something in my symfony app or with the docker image/franken php? 
As the doc for this is stil in PR https://github.com/symfony/symfony-docs/issues/19827 i can't find any hint about this problem.

Thanks

**Comment by alli83** [comment]
Would it be possible to know the versions of symfony and doctrineBundle being used?

**Comment by n1k00las** [comment]
symfony it's the 7.1 and for doctrine/doctrine-bundle   it's 2.12.

**Comment by alli83** [comment]
could you update doctrine bundle to 2.13?

**Comment by n1k00las** [comment]
You are speaking about doctrine/doctrine-bundle right? 
The 2.13 is still in dev branch.

**Comment by dunglas** [comment]
@n1k00las the patch isn't in a tagged version yet. You need to use the dev branch for now.
