### ISSUE TITLE
  Symfony 4 connection on Mysql docker container

### ISSUE THREAD

**Issue by younes-dev** [dunglas/symfony-docker#64]
please i have problem to connect my project symfony to mysql container using docker.
i have the below errors when i try to create my database using doctrin cmd : 
- php bin/console doctrine:database:create

root@9b0782a498c3:/application# php bin/console doctrine:database:create
[error] Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known"

In AbstractMySQLDriver.php line 93:

An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

In PDOConnection.php line 27:

PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known

doctrine:database:create [-s|--shard SHARD] [-c|--connection [CONNECTION]] [--if-not-exists] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] 

This my DockerCompose.yml : 

version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: mystore-memcached

    mysql:
      image: mysql:8.0
      container_name: mystore-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=mystore
        - MYSQL_USER=
        - MYSQL_PASSWORD=
      ports:
        - "3308:3306"

    mariadb:
      image: mariadb:10.4
      container_name: mystore-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=mystore
        - MYSQL_USER=
        - MYSQL_PASSWORD=
      ports:
        - "3309:3306"

    webserver:
      image: nginx:alpine
      container_name: mystore-webserver
      working_dir: /application

      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: mystore-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

DockerFile : 

FROM phpdockerio/php74-fpm:latest
WORKDIR "/application"

### Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

### Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y --no-install-recommends install  php-memcached php7.4-mysql php-xdebug php7.4-xsl php-yaml \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

### Install git
RUN apt-get update \
    && apt-get -y install git \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

.env file : 
---

DATABASE_URL=mysql://root:@mysql:3306/mystore?serverVersion=5.7

**Comment by silverbackdan** [comment]
In your DATABASE_URL try:
`mysql://root:root@mariadb:3306/mystore?serverVersion=5.7`

the format is 
`mysql://username:password@hostname:port/database?serverVersion=x.x`

**Comment by silverbackdan** [comment]
In your DATABASE_URL try:
`mysql://root:root@mysql:3306/mystore?serverVersion=5.7`

the format is 
`mysql://username:password@host:port/database?serverVersion=x.x` - in docker the host can be referred to by the service name

You should really define the `MYSQL_USER` and `MYSQL_PASSWORD` variables and use those instead though instead of the root user.

Are you aware you have both a mariadb and a mysql database service?

**Comment by younes-dev** [comment]
thank you @silverbackis  yes i do i tried with mariadb and when it failed i used mysql service

**Comment by younes-dev** [comment]
Hey @silverbackdan  thank you so much i fixed the Error its really silly but its appair very complicated when we dont know from where comes .
The problem is missing the single quotes only 


     mysql:
      image: mysql:8.0
      container_name: mystore-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD= 'root'
        - MYSQL_DATABASE= 'mystore'
        - MYSQL_USER= 'root'
        - MYSQL_PASSWORD= 'root'
      ports:
        - "3308:3306"


.env file : 
DATABASE_URL=mysql://root:root@mysql:3306/mystore?serverVersion=5.7

i have only one question please if you could respond me 
if put the variables instead where i should put my credentials 


     mysql:
      image: mysql:8.0
      container_name: mystore-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}

**Comment by silverbackdan** [comment]
You should choose a different username for your MYSQL_USER other than `root` - that should be used for a root user.

You may not need the quotes if you do not have a space either. Alternatively you can format like your second example using colons instead of the equals sign.

For your second example you can use it as you have shown or by simplifying it further
```
 environment:
    MYSQL_ROOT_PASSWORD: ~
    MYSQL_DATABASE: ~
    MYSQL_USER: ~
    MYSQL_PASSWORD: ~
```

This will do the same thing and pass your system environment variables to the docker container.

You can either setup your system environment variables or create a `.env` file in the project's root directory (the same directory as the `docker-compose.yaml` file). Then when you run `docker-compose up` from the project root directory, that `.env` file will be used.

**Comment by maxhelias** [comment]
Thanks @silverbackdan for the answer 😃 
The issue seems to be fixed, let's close it

**Comment by younes-dev** [comment]
Thank you so much @silverbackdan for your help
