### ISSUE TITLE
How to correctly start symfony-docker with the database in the DEV enviroment?

### ISSUE THREAD

**Issue by RichardCheung** [dunglas/symfony-docker#653]
How to correctly start symfony-docker with the database in the DEV environment?

I tried the below steps:

1. Clone the repo
git clone https://github.com/dunglas/symfony-docker.git

3. Start the instance
docker compose up -d

4. Attach to the instance
docker exec -it symfony-docker-php-1 bash

5. Require ORM pack to support database connection
composer require symfony/orm-pack

6. Stop the instance
docker compose down --remove-orphans

8. Start the instance again with postgres database instanace
docker compose up -d

9. Check the logs
docker logs symfony-docker-database-1

> 2024-08-11 07:16:01.140 UTC [75] DETAIL:  Role "app" does not exist.
>         Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
> 2024-08-11 07:16:02.189 UTC [76] FATAL:  password authentication failed for user "app"

docker logs symfony-docker-php-1

> Still waiting for database to be ready... Or maybe the database is not reachable. 34 attempts left.

Any light? Thanks.

**Comment by 7-zete-7** [comment]
Hello @RichardCheung!

I tried to repeat this sequence of actions and got successfully started containers.

My arch is `amd64`. Maybe this is the reason.

Can you specify your arch?

**Comment by RichardCheung** [comment]
My environment is also linux/amd64.

I can start the DEV environment with the below command:

SERVER_NAME=localhost \
APP_SECRET=SECRETSECRET \
CADDY_MERCURE_JWT_SECRET=SECRETSECRETSECRETSECRETSECRETSECRET \
POSTGRES_USER=user \
POSTGRES_PASSWORD=password \
POSTGRES_DB=app \
POSTGRES_VERSION=16 \
docker compose -f compose.yaml -f compose.override.yaml up -d --pull always --wait
