### ISSUE TITLE
PHP Session in worker mode

### ISSUE THREAD

**Issue by clussiana** [dunglas/symfony-docker#657]
I had a similar issue as #470

Fixed by adding `variables_order = EGPCS` in `10-app.ini`

Maybe there were a specific reason on removing it ?

**Comment by clussiana** [comment]
**EDIT**

It turns out that the issue I reported was not related to the 'variable_order' option. The real cause is that the worker mode does not reset my services after each request. 
Closing this issue because the problem is not with the session itself but with how services are managed in worker mode.

**Comment by maxhelias** [comment]
FYI: Symfony can reset your service with this interface : https://github.com/symfony/contracts/blob/main/Service/ResetInterface.php
