### ISSUE TITLE
Cannot autowire argument $request of

### ISSUE THREAD

**Issue by younes-dev** [dunglas/symfony-docker#66]
hey friends i have a problem i cant fix it wishing your help plz.
* [Cannot autowire argument $request of "App\Controller\BlogController::add()": it references class "symfony\Component\HttpFoundation\Request" but no such service exists.
 ](https://www.dropbox.com/s/pedocscxejsfo04/ERROR.png?dl=0)

```<?php

namespace App\Controller;

use App\Entity\BlogPost;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

  /**
  * @Route("/blog")
  */

class BlogController extends AbstractController
{
    /**
     * @Route("/add", name="Blog_Add",methods={"POST"})
     */
    public function add(Request $request)
    {
        //var_dump("here");die;
        $serializer = $this->get('serializer');
        $Post= $serializer->deserialize($request->getContent(),BlogPost::class,'json');
        $em=$this->getDoctrine()->getManager();
        $em->persist($Post);
        $em->flush();
        return  $this->json($Post);
    }
}
```

**Comment by maxhelias** [comment]
Hi!

Did you try with: **S**ymfony\Component\HttpFoundation\Request ? Not with a lowercase s.

This request is not related to this project, please keep this issue tracker only on the integration of symfony with docker. You can find more help about Symfony on their Slack: https://symfony.com/support

Thanks
