### ISSUE TITLE
pull access denied

### ISSUE THREAD

**Issue by paskuale75** [dunglas/symfony-docker#664]
During:  `docker compose up --pull always -d --wait command `

I get this warning:
` ! php Warning pull access denied for app-php, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

what's wrong ? thanks

_OS: MAC SONOMA
Docker Desktop 4.34.0
Docker Compose: v2.29.2-desktop.2
Docker: v27.2.0

**Comment by dunglas** [comment]
You can safely ignore this warning.

I don't know if there is a way to disable it. Basically, we have to set an image name, and as this is a local-only name, pull fails (and it's intended).

**Comment by paskuale75** [comment]
thanks for the reply @dunglas, I don't know why but it seems I can't install the Caddy web server correctly, I closed Mamp Pro and I put the HTTP_PORT=8000
HTTPS_PORT=9443 parameters in the .env file but after the "docker compose up --pull always -d --wait" there is no way to access localhost:8000

any suggestion ? 
thanks

**Comment by paskuale75** [comment]
Ok it seems to work but there is something strange, I have to point to the url http**s**://localhost:9443 even though docker desktop in the Ports column offers me links to the same url but not of the ssl type (I attach a screenshot)
![doker-desktop-ports](https://github.com/user-attachments/assets/5195a692-f2a3-43d2-90a5-acb387fbb69d)

**Comment by maxhelias** [comment]
I'd say that docker isn't capable of knowing on a custom port whether https is required or not, even if it's mapped to one  🤷‍♂️
