### ISSUE TITLE
public/bundles missing in nginx 'symfony_nginx'

### ISSUE THREAD

**Issue by mbertoneri** [dunglas/symfony-docker#67]
Hey after figured out how to solve acl issue from 'docker-entry-point'  on my synology NAS, my app is almost OK.

** I'm new in docker and symfony, so apologizes if my wordings are incorrects **

After up and connecting to nginx container, I can see that  public/bundles is missing, the public directory looks like my source file. 
In the php no problem (I'm using FOSJsRoutingBundle without webpack).

I've done so many docker-composer build, so I've tried:
 **`docker system prune`** and also **`docker-compose build --no-cache`** but problem still not solved.

What am I missing ? (sorry for my bad English)

**Comment by maxhelias** [comment]
Can you tell me if it's ok by changing this ligne https://github.com/dunglas/symfony-docker/blob/master/docker-compose.yml#L37 by 
```yaml
./public:/srv/app/public:rw,cached
```

**Comment by mbertoneri** [comment]
Thx Maxime, it does not work, but you made me on the way :
**`./public:/srv/app/public`** : it mounts the local public witch doesn't have the 'bundles' dir.

I've made the nginx mount the php public folder and now nginx can see the public/bundles. 
Now there is something else to solve with FOSJsRoutingBundle (error 500) :)

The problem was definitely me !

**Comment by maxhelias** [comment]
Great, it's a small step forward.
For information, the bundle dir is created by `php bin/console assets:install --symlink public` and it's execute automaticly on composer install or update with Flex.

Don't hesitate to update the ticket according to your progress 😉

**Comment by mbertoneri** [comment]
Ok i was looking for why the bundles were in place without doing something ^^

**Comment by mbertoneri** [comment]
Sorry, could I ask a question ?
Should I open an issue or something for ACL issue since it's not supported by NAS Synology and I had to replace these lines: [https://github.com/dunglas/symfony-docker/blob/7ab611a755f8d08a2873ff0303396ff700b8cd53/docker/php/docker-entrypoint.sh#L32-L33](url)

by classics `chmod` and `chown`

**Comment by maxhelias** [comment]
Are you using Synology DSM ? In my memory, by default getfacl and setfacl commands aren't installed.

**Comment by mbertoneri** [comment]
Yep DSM 6. If someone is using a Synology NAS, it will have the same acl issue than me.

Maybe we can say something in readme ? Or i post my modifications here and close the issue as you prefer.

**Comment by maxhelias** [comment]
I don't know DSM well but maybe you should be able to install "acl" like on Linux.
I'm not familiar with DSM but maybe you should be able to install "acl" like on Linux. After Synology is too little used for this kind of thing IMO.

**Comment by mbertoneri** [comment]
Yep i'm agree with you, i close :)
Thx ^^
