### ISSUE TITLE
Mercure setup fails with locally generated certificates

### ISSUE THREAD

**Issue by papppeter** [dunglas/symfony-docker#673]
Hi, 

i have a locally installed certificates, created with mkcert.

site itself is working, with the suggested modifications form this issue: https://github.com/dunglas/symfony-docker/issues/604 

php:443, added extra CADDY_GLOBAL_OPTIONS: ${CADDY_GLOBAL_OPTIONS:-auto_https off}

but in this case i cannot reach http://php inside the container. Of course there is no 80 port.
if i try to reach https://php inside the container, cert check are failing

should i copy root certificatie into docker, and install it? would it be a solution?
or is there a setup where i can enable php:80 and inside the docker container i don't need to check certificates?

**Comment by maxhelias** [comment]
Hi!
Yes, you must copy it. I hope the answers provided here will help you further : https://github.com/dunglas/symfony-docker/issues/604#issuecomment-2375188692

**Comment by papppeter** [comment]
Hi,

thanks for your help, by the way copy was not neccesary to make it work. I followed #604 steps you did highlited in your comment.
