### ISSUE TITLE
Symfony/Config is undefined because of app/var

### ISSUE THREAD

**Issue by lektura0bandyta** [dunglas/symfony-docker#678]
Hi, I'm using symfony/config bundle to create framework config in PHP instead of YAML and facing issue because of this line to create volume for var directory https://github.com/dunglas/symfony-docker/blob/main/Dockerfile#L16

In know it's to keep better performance but looking solution to improve DX since Symfony/Config package is creating config classes on demand in `var/cache/{env}/Symfony/Config` so if I want to edit config files IDE shows "class is undefined" because my system can't see it outside container, files exists but only init.

Could you tell me what should be best approach for this case?

**Comment by 7-zete-7** [comment]
Hello, @lektura0bandyta!

You can add the following line in thie `compose.override.yaml` file to mount the `/app/var` directory to the corresponding directory on the host:
```patch
     volumes:
       - ./:/app
+      - ./var/:/app/var
       - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
       - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
    environment:
```

**Comment by maxhelias** [comment]
Hi!
And if you want to save performance, target the folder more precisely in the volume section.
