### ISSUE TITLE
Problem with enabling HTTPS using let's encrypt

### ISSUE THREAD

**Issue by farestayari** [dunglas/symfony-docker#687]
Hello, 

i deployed my containers on HTTP port using a public IP adress, recently i added a domain name to my server, and when i tried to use let's encrypt to add HTTPS using the command in the documentation i got these errors : 

<details><summary>Details</summary>
<p>

[
{"level":"info","ts":1731240846.91451,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""},
{"level":"warn","ts":1731240846.9194036,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":9},
{"level":"info","ts":1731240846.9214125,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//[::1]:2019","//127.0.0.1:2019","//localhost:2019"]},
{"level":"info","ts":1731240846.9215715,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443},
{"level":"info","ts":1731240846.921586,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"},
{"level":"warn","ts":1731240846.921596,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv1","http_port":80},
{"level":"info","ts":1731240846.9231548,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000471980"},
{"level":"info","ts":1731240847.6194303,"msg":"FrankenPHP started 🐘","php_version":"8.3.7"},
{"level":"info","ts":1731240847.6196232,"logger":"http","msg":"enabling HTTP/3 listener","addr":":443"},
{"level":"info","ts":1731240847.619723,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details."},
{"level":"info","ts":1731240847.6198308,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]},
{"level":"info","ts":1731240847.6198745,"logger":"http.log","msg":"server running","name":"srv1","protocols":["h1","h2","h3"]},
{"level":"info","ts":1731240847.6198795,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["myedl.lodgis.com"]},
{"level":"info","ts":1731240847.620147,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"},
{"level":"info","ts":1731240847.6201591,"msg":"serving initial configuration"},
{"level":"info","ts":1731240847.6204379,"logger":"tls.obtain","msg":"acquiring lock","identifier":"myedl.lodgis.com"},
{"level":"warn","ts":1731240847.6268766,"logger":"tls","msg":"storage cleaning happened too recently; skipping for now","storage":"FileStorage:/data/caddy","instance":"eb3444e4-73b7-4f77-9cb7-3b61d9a09367","try_again":1731327247.626875,"try_again_in":86399.999999271},
{"level":"info","ts":1731240847.6269488,"logger":"tls","msg":"finished cleaning storage units"},
{"level":"info","ts":1731240855.6220167,"msg":"[INFO][FileStorage:/data/caddy] Lock for 'issue_cert_myedl.lodgis.com' is stale (created: 2024-11-10 12:09:44.875064394 +0000 UTC, last update: 2024-11-10 12:14:05.258721225 +0000 UTC); removing then retrying: /data/caddy/locks/issue_cert_myedl.lodgis.com.lock"},
{"level":"info","ts":1731240855.626496,"logger":"tls.obtain","msg":"lock acquired","identifier":"myedl.lodgis.com"},
{"level":"info","ts":1731240855.6266384,"logger":"tls.obtain","msg":"obtaining certificate","identifier":"myedl.lodgis.com"},
{"level":"info","ts":1731240855.6273482,"logger":"http","msg":"waiting on internal rate limiter","identifiers":["myedl.lodgis.com"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":""},
{"level":"info","ts":1731240855.627365,"logger":"http","msg":"done waiting on internal rate limiter","identifiers":["myedl.lodgis.com"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":""},
{"level":"info","ts":1731240856.5765944,"logger":"http.acme_client","msg":"trying to solve challenge","identifier":"myedl.lodgis.com","challenge_type":"http-01","ca":"https://acme-v02.api.letsencrypt.org/directory"},
{"level":"error","ts":1731240857.0919561,"logger":"http.acme_client","msg":"challenge failed","identifier":"myedl.lodgis.com","challenge_type":"http-01","problem":{"type":"urn:ietf:params:acme:error:connection","title":"","detail":"91.151.65.81: Fetching http://myedl.lodgis.com/.well-known/acme-challenge/HQ-5-bdiy4kpyyopeazv_asftOF5TbgaP-GnHq1YA8Y: Connection refused","instance":"","subproblems":[]}},
{"level":"error","ts":1731240857.0919929,"logger":"http.acme_client","msg":"validating authorization","identifier":"myedl.lodgis.com","problem":{"type":"urn:ietf:params:acme:error:connection","title":"","detail":"91.151.65.81: Fetching http://myedl.lodgis.com/.well-known/acme-challenge/HQ-5-bdiy4kpyyopeazv_asftOF5TbgaP-GnHq1YA8Y: Connection refused","instance":"","subproblems":[]},"order":"https://acme-v02.api.letsencrypt.org/acme/order/2048632467/321766463037","attempt":1,"max_attempts":3},
{"level":"info","ts":1731240858.4960692,"logger":"http.acme_client","msg":"trying to solve challenge","identifier":"myedl.lodgis.com","challenge_type":"tls-alpn-01","ca":"https://acme-v02.api.letsencrypt.org/directory"},
{"level":"error","ts":1731240869.015731,"logger":"http.acme_client","msg":"challenge failed","identifier":"myedl.lodgis.com","challenge_type":"tls-alpn-01","problem":{"type":"urn:ietf:params:acme:error:connection","title":"","detail":"91.151.65.81: Timeout during connect (likely firewall problem)","instance":"","subproblems":[]}},
{"level":"error","ts":1731240869.0157998,"logger":"http.acme_client","msg":"validating authorization","identifier":"myedl.lodgis.com","problem":{"type":"urn:ietf:params:acme:error:connection","title":"","detail":"91.151.65.81: Timeout during connect (likely firewall problem)","instance":"","subproblems":[]},"order":"https://acme-v02.api.letsencrypt.org/acme/order/2048632467/321766469577","attempt":2,"max_attempts":3},
{"level":"error","ts":1731240869.0158367,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"myedl.lodgis.com","issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 400 urn:ietf:params:acme:error:connection - 91.151.65.81: Timeout during connect (likely firewall problem)"},
{"level":"warn","ts":1731240869.0159945,"logger":"http","msg":"missing email address for ZeroSSL; it is strongly recommended to set one for next time"},
{"level":"error","ts":1731240869.431213,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"myedl.lodgis.com","issuer":"acme.zerossl.com-v2-DV90","error":"account pre-registration callback: failed getting EAB credentials: HTTP 422: caddy_legacy_user_removed (code 2977)"},
{"level":"error","ts":1731240869.431275,"logger":"tls.obtain","msg":"will retry","error":"[myedl.lodgis.com] Obtain: account pre-registration callback: failed getting EAB credentials: HTTP 422: caddy_legacy_user_removed (code 2977)","attempt":1,"retrying_in":60,"elapsed":13.804757212,"max_duration":2592000}
]

</p>
</details> 

Am i missing something in my Caddyfile config ? 
Thank you for your help

**Comment by 7-zete-7** [comment]
Hi @farestayari!

Seems like you have close TCP port 80 on your server.

To obtain a certificate (complete the acme challenge), TCP port 80 must be open on the server.

You can check if the port is open using, for example, a curl request:

```shell
$ curl -v http://myedl.lodgis.com:80/
```

Can you show your Caddyfile, compose.yaml files and the environment variables the container is started with?

**Comment by farestayari** [comment]
Hello @7-zete-7  
Thank you for your help, it's true i tried to curl my domain with 80 port and it failed to connect
Here is my CaddyFile and compose.yaml for more informations if i missed something else :
```Caddyfile
{
	{$CADDY_GLOBAL_OPTIONS}

	frankenphp {
		{$FRANKENPHP_CONFIG}
	}
}

{$SERVER_NAME:localhost}

{$CADDY_EXTRA_CONFIG}

log {
	# Redact the authorization query parameter that can be set by Mercure
	format filter {
		wrap console
		fields {
			uri query {
				replace authorization REDACTED
			}
		}
	}
}

route {
	root * /app/public
	mercure {
		# Transport to use (default to Bolt)
		transport_url {$MERCURE_TRANSPORT_URL:bolt:///data/mercure.db}
		# Publisher JWT key
		publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
		# Subscriber JWT key
		subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
		# Allow anonymous subscribers (double-check that it's what you want)
		anonymous
		# Enable the subscription API (double-check that it's what you want)
		subscriptions
		# Extra directives
		{$MERCURE_EXTRA_DIRECTIVES}
	}
	vulcain

	# Add trailing slash for directory requests
	@canonicalPath {
		file {path}/index.php
		not path */
	}
	redir @canonicalPath {path}/ 308

	# If the requested file does not exist, try index files
	@indexFiles file {
		try_files {path} {path}/index.php index.php
		split_path .php
	}
	rewrite @indexFiles {http.matchers.file.relative}

	# FrankenPHP!
	@phpFiles path *.php
	php @phpFiles

	encode zstd gzip
	file_server

	respond 404
}

``` 
```compose.yaml
services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      PHP_MEMORY_LIMIT: 256M
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: xxxxxx
      MERCURE_SUBSCRIBER_JWT_KEY: xxxxxx
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|php$$
      DATABASE_URL: xxxxxx
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: xxxxxx
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-8080}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    networks:
      - my-network

volumes:
  caddy_data:
  caddy_config:
networks:
  my-network:
    driver: bridge
```

**Comment by 7-zete-7** [comment]
Seems like you using TCP port `8080` for a HTTP protocol.

Can you change default value of `HTTP_PORT` environment variable from `8080` to `80` and restart your container?

```diff
     ports:
       # HTTP
       - target: 80
-        published: ${HTTP_PORT:-8080}
+        published: ${HTTP_PORT:-80}
         protocol: tcp
       # HTTPS
       - target: 443
```
