### ISSUE TITLE
Docker compose build fails with "invalid interpolation format"

### ISSUE THREAD

**Issue by dario-nuro** [dunglas/symfony-docker#688]
After cloning the main branch and following README.md, the command:

`docker compose build --no-cache
`
fails with:

`invalid interpolation format for services.php.environment.MERCURE_PUBLIC_URL.`

**Comment by maxhelias** [comment]
Take a look at this : https://github.com/dunglas/symfony-docker/issues/630

**Comment by dario-nuro** [comment]
Thanks. I did a search before posting but I obviously missed that.
