### ISSUE TITLE
Not a Certification Authority

### ISSUE THREAD

**Issue by rafaelmiti** [dunglas/symfony-docker#69]
Following the [ssl solution](https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate/15076602#15076602) referenced in the readme, I received this message:

![cert](https://user-images.githubusercontent.com/6079888/90986312-4bcf9700-e558-11ea-82d8-ece625463ff0.png)

Any ideias?

**Comment by maxhelias** [comment]
Did you download the certificate and install it? What OS are you using ?

**Comment by rafaelmiti** [comment]
Sorry about the delay. Didn't get a notification about the response. Yes, I downloaded it. If the instalation is the import on chrome, the above image is the message I'm receiving. My OS is Ubuntu 18.04.

**Comment by maxhelias** [comment]
Now the project use Caddy server, you should no longer have this problem. Do not hesitate to reopen if the problem persists.
