### ISSUE TITLE
.editorconfig alerts in PHPSTORM

### ISSUE THREAD

**Issue by papppeter** [dunglas/symfony-docker#690]
Hi, 

maybe it is a setup issue on my side but i hope you can help me out.

![image](https://github.com/user-attachments/assets/25ff1ec8-9dd5-47a1-b199-e89427f92e56)
![image](https://github.com/user-attachments/assets/d4222349-1db6-4c50-98f5-0676057ef6c1)

did you see something like this? Is there a solution, or my IDE has some missconfiguration?

i use latest PHPSTORM

**Comment by maxhelias** [comment]
The configuration was out of date. I updated it here : https://github.com/dunglas/symfony-docker/pull/691/files
