### ISSUE TITLE
Requests to Mercure are handled using PHP

### ISSUE THREAD

**Issue by bkosun** [dunglas/symfony-docker#695]
Requests to Mercure are handled with PHP instead of Mercure

This is because after merge #694, all requests except static are redirected to PHP

https://github.com/dunglas/symfony-docker/blob/12944cb6d5f470a45faca7ff9411a0abb190f0e3/frankenphp/Caddyfile#L47

**Comment by senzowayne** [comment]
same issue for me 😉
