### ISSUE TITLE
[RFC] Switching to nginx unit

### ISSUE THREAD

**Issue by joelwurtz** [dunglas/symfony-docker#7]
It's very new and should be properly tested, but it's add a new SAPI into PHP which provide a direct http endpoint who is aim to be suitable for production in the long term.

This will definitely reduce the complexity of this repo as there will no more need to have a docker compose (only docker will be enough) for a basic usage / demo

I don't think that should be done now as nginx unit is very new, but IMO it must be osberved and integrated when it's stable enough for production.

**Comment by dunglas** [comment]
Another option would be to use mod_php right?

**Comment by maxhelias** [comment]
I allow myself to up the RFC 😅 

I am not informed on it but is that there have been updated ?
The project has evolved a bit since the RFC and I don't have the feel that is still relevant

**Comment by maxhelias** [comment]
I close this issue because, now we use caddy server.
