### ISSUE TITLE
How to use this repo ?

### ISSUE THREAD

**Issue by Nayte91** [dunglas/symfony-docker#76]
Hello all,
Not sure it's the good place to ask, but I don't know where to ask help,
I'm a rookie symfony dev and I just begin using docker,
I wanted to know how to use this ? Where do I put those files ?
I have a dev/ folder with my several symfony projects into : dev/projectA/ dev/projectB/ ...
If I have to put this in every folder, how do I git it ? Or do I download this and unzip in each project folder ?

Issue : The getting started part is for already advanced docker user :)

Thank you in advance !

**Comment by dunglas** [comment]
To create a new project, just type the commands listed in the getting started guide! A Symfony project (including the directory structure) will be created during the first run.

For existing projects, copy all the files contained in this repository in the project and type `docker-compose up`.
