### ISSUE TITLE
Trust root certificate locally

### ISSUE THREAD

**Issue by jessedobbelaere** [dunglas/symfony-docker#79]
Great repository! 

### localhost
I was fiddling with a Symfony app and Caddyserver locally. One thing I haven't cracked is to have trusted SSL certificates. The link in the README to [accept the auto-generated TLS certificate](https://stackoverflow.com/a/15076602/1352334) seems outdated and does not work very well on my Mac with Chrome :( 

![image](https://user-images.githubusercontent.com/1352979/97448982-80354a00-1931-11eb-9fdc-6559ec171c35.png)

Any recent tricks or updates on how to make it work to self-sign the Caddy certificate? **Maybe I would need to somehow extract the Caddy root certificate out of the docker container and trust it on my mac...** Like `caddy trust` does...  I'd still like to let Caddy create the certificate, so I don't have to mount certificates created via e.g. https://github.com/FiloSottile/mkcert

### hostname
In addition, I'd like to use a hostname locally, e.g. `SERVER_NAME=mywebsite.test docker-compose up`. And I run dnsmasq to map *.test domains to my localhost. But the Caddy server will start reaching out to Letsencrypt (which won't work because the hostname is not externally available). 

```
caddy_1  | {"level":"error","ts":1603895023.9278789,"logger":"tls.obtain","msg":"will retry","error":"[mywebsite.test] Obtain: [mywebsite.test] creating new order: request to https://acme-staging-v02.api.letsencrypt.org/acme/new-order failed after 1 attempts: HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Error creating new order :: Cannot issue for \"mywebsite.test\": Domain name does not end with a valid public suffix (TLD) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":3,"retrying_in":120,"elapsed":183.5167383,"max_duration":2592000}
```

Probably this can be fixed by adding `tls internal` to the Caddyfile. But then I still have the self-signed issue from above again.

**Comment by maxhelias** [comment]
Hello @jessedobbelaere,

For the trust certificate, I have updated the documentation on this subject so that it now corresponds to the use of Caddy. Please see https://github.com/dunglas/symfony-docker/pull/85

For the hostname, the project is designed to be production, development and CI ready, so I'm afraid we don't put `tls internal`.

**Comment by jessedobbelaere** [comment]
Late answer, but I just tested it out, works perfectly with the `docker cp` solution! Awesome 🙌  thank you!
