### ISSUE TITLE
Error cache in production

### ISSUE THREAD

**Issue by arnaudbagnis** [dunglas/symfony-docker#80]
Hello,
I have an error on the project.
I can't access the API platform

command :  _**SERVER_NAME=domain.tld docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d**_ 
in /api -> The server returned a "500 Internal Server Error".

in log : 
`Uncaught PHP Exception ArgumentCountError: "Too few arguments to function Symfony\Component\Cache\Adapter\AbstractAdapter::doGet(), 1 passed in /srv/app/vendor/symfony/cache/Traits/AbstractAdapterTrait.php on line 212 and at least 4 expected" at /srv/app/vendor/symfony/cache-contracts/CacheTrait.php line 44`

**Comment by dunglas** [comment]
This doesn't look related to this project but to Symfony upstream. Can you try to clear all the caches to see if it fixes the problem?

**Comment by arnaudbagnis** [comment]
I already tried, still the same problem ...

**Comment by maxhelias** [comment]
Related to https://github.com/symfony/symfony/issues/38976, it's a php bug and reported here https://bugs.php.net/bug.php?id=80307 and fixed for the next php release php 7.4.13

While waiting php release, I think that by forcing a version lower than php it will unlock you
