### ISSUE TITLE
Extra Services

### ISSUE THREAD

**Issue by 0x346e3730** [dunglas/symfony-docker#82]
According to https://github.com/dunglas/symfony-docker/blob/master/docs/extra-services.md, there are recipes for symfony/orm-packages and symfony/messenger.

However, I've changed the Dockerfile to install the full website project and not the skeleton, hence I cannot "install" symfony/orm-packages because the packages referenced in this meta-packages are already installed.

How can I look at the recipes for those package installs so that I can do what they do myself ?

**Comment by maxhelias** [comment]
You can re install all recipes with this command `composer symfony:install:recipes --force` otherwise you can look on the symfony recipes repo https://github.com/symfony/recipes
