### ISSUE TITLE
How to do subsequent deploys?

### ISSUE THREAD

**Issue by BurningDog** [dunglas/symfony-docker#95]
Once everything is set up and running, how do I do subsequent deploys? Mostly a deploy involves new php code, so I imagine the php container needs to be rebuilt.

Like so?

```
SYMFONY_VERSION=4.4.* PHP_VERSION=7.4 SERVER_NAME="example.com" docker-compose --env-file=.env.local -f docker-compose.yml -f docker-compose.prod.yml build php

SYMFONY_VERSION=4.4.* PHP_VERSION=7.4 SERVER_NAME="example.com" docker-compose --env-file=.env.local -f docker-compose.yml -f docker-compose.prod.yml up -d php
```

I'd like to do zero downtime deploys. The above method takes the php container offline while the new one is built and deployed, which takes the site offline. The [docs](https://github.com/dunglas/symfony-docker/blob/master/docs/production.md) say that Docker Swarm can be used, but after running `docker swarm init` and `docker stack deploy -c docker-compose.yml symfony` I get this error:

```
Ignoring unsupported options: build, restart

Creating network symfony_mysql
Creating network symfony_php
Creating service symfony_mysql
Creating service symfony_php
failed to create service symfony_php: Error response from daemon: rpc error: code = InvalidArgument desc = ContainerSpec: image reference must be provided
```

`Ignoring unsupported options: build, restart` - but both options are needed! (Apologies, I'm a Docker Swarm newbie so unsure exactly how this all works).

**Comment by BurningDog** [comment]
I've ended up writing a bash script which does a blue/green deployment with the php container, extending this idea here: https://coderbook.com/@marcus/how-to-do-zero-downtime-deployments-of-docker-containers/

Unfortunately that means duplicating the entire `php` service in `docker-compose.yml`, calling one `php-blue` and the other `php-green`, but it works.

I've created a new environment variable, `PHP_CONTAINER=php-blue`, and in the Caddyfile I've set `php_fastcgi {$PHP_CONTAINER}:9000`. On deploy, I check whether blue or green is active, then spin up the other. Wait 60 seconds (I don't know how to check once a container is successfully running), then tell Caddy to use it.

Like so:

```bash
#!/bin/sh
# Uses the blue-green deployment pattern to spin up a new container then tell Caddy to use it.
if [ $(docker ps -f name=php-blue -q) ]
then
    ENV="php-green"
    OLD="php-blue"
else
    ENV="php-blue"
    OLD="php-green"
fi

DOCKER_COMPOSE="SYMFONY_VERSION=4.4.* PHP_VERSION=7.4 docker-compose --env-file=.env.local -f docker-compose.yml -f docker-compose.prod.yml"

echo "Rebuilding and starting "$ENV" container"
eval $DOCKER_COMPOSE up -d --build $ENV

# I don't have a way of knowing when the new container is ready, so this is a guess.
echo "Waiting..."
sleep 60s

if [ $(docker ps -f name=$ENV -q) ]
then
  echo "$ENV container started successfully"
else
  echo "$ENV container failed to start successfully"
  docker ps -f name=$ENV
  exit 1
fi

echo "Switching Caddy from $OLD to $ENV"
docker-compose exec -e PHP_CONTAINER=$ENV caddy caddy reload -config /etc/caddy/Caddyfile
echo "Caddy switched from $OLD to $NEW"

echo "Waiting..."
sleep 5s

echo "Stopping "$OLD" container"
docker-compose stop $OLD
```

**Comment by maxhelias** [comment]
Hi @BurningDog,

1. I don't know very well either docker swarm but it seems that it is necessary to mention the `image` name on the service. Something like this :
```Dockerfile
php:
    image: php
    build:
      context: .
      target: symfony_php
   ....
```
And before, you will have to create the image beforehand and just use image property.

2. For the switch, unfortunately I couldn't help you... But look at the docker swarm side, with tags from the image, there may be a management on this side that allows to attach / detach a service juste like for the scale.

3. With redis, I recommend you to use https://github.com/snc/SncRedisBundle for session and cache.

Note: Don't forget also the managed file store for uploads or other. (the Flysytem library is very interesting for this purpose)

I hope this will help you

**Comment by maxhelias** [comment]
I closed it due to lack of activity. Do not hesitate to reopen the issue if needed.
